export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 361,
        pronunciation: "kəˈmjuːtər",
        imageUrl: "",
        word: "commuter",
        definition: "a person who travels regularly between home and work",
        synonyms: ["traveler", "passenger", "daily traveler"],
        examples: [
          "She is a daily commuter from the suburbs to the city.",
          "Many commuters use the train to get to work.",
          "The city has special lanes for bicycle commuters.",
        ],
        wordPr: "مسافر روزانه",
        definitionPr: "کسی که به طور منظم بین خانه و محل کار رفت و آمد می‌کند",
        synonymsPr: ["مسافر", "مسافر روزانه", "رفت و آمد کننده"],
        examplesPr: [
          "او مسافر روزانه از حومه به شهر است.",
          "بسیاری از مسافران روزانه برای رفتن به کار از قطار استفاده می‌کنند.",
          "شهر مسیرهای ویژه‌ای برای مسافران دوچرخه دارد.",
        ],
      },
      {
        id: 362,
        pronunciation: "kənˈfaɪn",
        imageUrl: "",
        word: "confine",
        definition: "to keep within limits; to restrict",
        synonyms: ["restrict", "limit", "imprison"],
        examples: [
          "The prisoner was confined to his cell.",
          "Please confine your comments to the topic.",
          "The illness confined her to bed for weeks.",
        ],
        wordPr: "محدود کردن، محبوس کردن",
        definitionPr: "نگه داشتن در محدوده؛ محدود کردن",
        synonymsPr: ["محدود کردن", "محبوس کردن", "محصور کردن"],
        examplesPr: [
          "زندانی به سلول خود محدود شده بود.",
          "لطفاً نظرات خود را به موضوع محدود کنید.",
          "بیماری او را برای هفته‌ها به تخت محدود کرد.",
        ],
      },
      {
        id: 363,
        pronunciation: "ˈaɪdəl",
        imageUrl: "",
        word: "idle",
        definition: "not active or in use; lazy",
        synonyms: ["inactive", "lazy", "unproductive"],
        examples: [
          "The factory has been idle for months.",
          "He was idle and did not work all day.",
          "Don't stay idle; find something to do.",
        ],
        wordPr: "بیکار، تنبل",
        definitionPr: "غیر فعال یا بلااستفاده؛ تنبل",
        synonymsPr: ["بیکار", "تنبل", "غیرفعال"],
        examplesPr: [
          "کارخانه ماه‌ها بیکار بوده است.",
          "او بیکار بود و تمام روز کار نکرد.",
          "بیکار نمان؛ کاری پیدا کن.",
        ],
      },
      {
        id: 364,
        pronunciation: "ˈaɪdəl",
        imageUrl: "",
        word: "idol",
        definition:
          "an image or object worshiped as a god; a person admired greatly",
        synonyms: ["hero", "icon", "figure"],
        examples: [
          "The singer is an idol for many young people.",
          "They worshiped idols in ancient times.",
          "He became an idol of the sports world.",
        ],
        wordPr: "بت، معبود، الگو",
        definitionPr:
          "تصویر یا شیء که به عنوان خدا پرستیده می‌شود؛ شخصی که بسیار تحسین می‌شود",
        synonymsPr: ["الگو", "بت", "نماد"],
        examplesPr: [
          "این خواننده الگوی بسیاری از جوانان است.",
          "آن‌ها در گذشته بت پرستیده‌اند.",
          "او به یک الگوی دنیای ورزش تبدیل شد.",
        ],
      },
      {
        id: 365,
        pronunciation: "dʒɛst",
        imageUrl: "",
        word: "jest",
        definition: "a joke or playful remark",
        synonyms: ["joke", "tease", "fun"],
        examples: [
          "He made a jest about the situation.",
          "Don't take his words in jest.",
          "The comment was meant as a jest.",
        ],
        wordPr: "شوخی، لطیفه",
        definitionPr: "یک شوخی یا اظهارنظر بازیگوشانه",
        synonymsPr: ["شوخی", "لطیفه", "مزاح"],
        examplesPr: [
          "او درباره وضعیت شوخی کرد.",
          "کلمات او را جدی نگیر.",
          "این جمله به عنوان شوخی گفته شد.",
        ],
      },
      {
        id: 366,
        pronunciation: "ˌpeɪtriˈɑtɪk",
        imageUrl: "",
        word: "patriotic",
        definition: "showing love and support for one's country",
        synonyms: ["nationalistic", "loyal", "devoted"],
        examples: [
          "She is very patriotic and loves her country.",
          "Patriotic songs are sung on national holidays.",
          "He showed patriotic feelings during the war.",
        ],
        wordPr: "میهن‌پرست",
        definitionPr: "نشان دادن عشق و حمایت از کشور خود",
        synonymsPr: ["میهن‌پرست", "وفادار", "وطن‌دوست"],
        examplesPr: [
          "او بسیار میهن‌پرست است و کشورش را دوست دارد.",
          "آهنگ‌های میهن‌پرستانه در تعطیلات ملی خوانده می‌شوند.",
          "او در زمان جنگ احساسات میهن‌پرستانه نشان داد.",
        ],
      },
      {
        id: 367,
        pronunciation: "dɪsˈpjuːt",
        imageUrl: "",
        word: "dispute",
        definition: "a disagreement or argument",
        synonyms: ["argument", "conflict", "debate"],
        examples: [
          "They had a dispute over the property.",
          "The dispute was resolved peacefully.",
          "The dispute between the two countries lasted years.",
        ],
        wordPr: "اختلاف، بحث",
        definitionPr: "نزاع یا مشاجره",
        synonymsPr: ["مشاجره", "نزاع", "بحث"],
        examplesPr: [
          "آن‌ها روی ملک اختلاف داشتند.",
          "اختلاف به طور مسالمت‌آمیز حل شد.",
          "اختلاف بین دو کشور سال‌ها طول کشید.",
        ],
      },
      {
        id: 368,
        pronunciation: "ˈvælər",
        imageUrl: "",
        word: "valor",
        definition: "great courage in the face of danger",
        synonyms: ["bravery", "courage", "heroism"],
        examples: [
          "The soldier showed great valor during battle.",
          "His valor was recognized with a medal.",
          "Stories of valor inspire many people.",
        ],
        wordPr: "شجاعت، دلیری",
        definitionPr: "شجاعت زیاد در مقابل خطر",
        synonymsPr: ["شجاعت", "دلیر بودن", "شهامت"],
        examplesPr: [
          "سرباز در نبرد شجاعت زیادی نشان داد.",
          "شجاعت او با مدال شناخته شد.",
          "داستان‌های شجاعت الهام‌بخش بسیاری هستند.",
        ],
      },
      {
        id: 369,
        pronunciation: "ˈluːnətɪk",
        imageUrl: "",
        word: "lunatic",
        definition: "a person who behaves in a crazy or insane way",
        synonyms: ["madman", "insane person", "crazy"],
        examples: [
          "The lunatic shouted loudly in the street.",
          "He acted like a lunatic after hearing the news.",
          "The lunatic was taken to a hospital.",
        ],
        wordPr: "دیوانه، مجنون",
        definitionPr: "شخصی که به صورت دیوانه‌وار یا غیرعادی رفتار می‌کند",
        synonymsPr: ["دیوانه", "مجنون", "عقل‌باخته"],
        examplesPr: [
          "دیوانه در خیابان فریاد زد.",
          "بعد از شنیدن خبر مثل دیوانه رفتار کرد.",
          "دیوانه به بیمارستان منتقل شد.",
        ],
      },
      {
        id: 370,
        pronunciation: "veɪn",
        imageUrl: "",
        word: "vein",
        definition: "a blood vessel that carries blood to the heart",
        synonyms: ["blood vessel", "capillary", "venule"],
        examples: [
          "The doctor checked the vein in his arm.",
          "She has a visible vein on her forehead.",
          "Veins carry blood back to the heart.",
        ],
        wordPr: "رگ",
        definitionPr: "رگ خونی که خون را به قلب می‌رساند",
        synonymsPr: ["رگ خونی", "مویرگ", "سیاهرگ"],
        examplesPr: [
          "دکتر رگ بازوی او را بررسی کرد.",
          "او رگ قابل مشاهده‌ای روی پیشانی دارد.",
          "رگ‌ها خون را به قلب بازمی‌گردانند.",
        ],
      },
      {
        id: 371,
        pronunciation: "ʌnɪˈvɛntfəl",
        imageUrl: "",
        word: "uneventful",
        definition: "without any important or interesting events",
        synonyms: ["boring", "dull", "ordinary"],
        examples: [
          "The trip was uneventful and peaceful.",
          "It was an uneventful day at work.",
          "The uneventful meeting lasted only an hour.",
        ],
        wordPr: "بی‌حادثه، کم‌حادثه",
        definitionPr: "بدون هیچ اتفاق مهم یا جالب",
        synonymsPr: ["کسل‌کننده", "خسته‌کننده", "عادی"],
        examplesPr: [
          "سفر بی‌حادثه و آرام بود.",
          "روز کاری بی‌حادثه‌ای بود.",
          "جلسه کم‌حادثه فقط یک ساعت طول کشید.",
        ],
      },
      {
        id: 372,
        pronunciation: "ˈfɜːrtəl",
        imageUrl: "",
        word: "fertile",
        definition: "able to produce crops or offspring; productive",
        synonyms: ["productive", "fruitful", "rich"],
        examples: [
          "The fertile soil produces many vegetables.",
          "She has a fertile imagination.",
          "Farmers prefer fertile land for planting.",
        ],
        wordPr: "حاصلخیز، بارور",
        definitionPr: "توانایی تولید محصول یا نسل؛ پربار",
        synonymsPr: ["حاصلخیز", "پربار", "بارور"],
        examplesPr: [
          "خاک حاصلخیز بسیاری از سبزیجات را تولید می‌کند.",
          "او تخیل پرباری دارد.",
          "کشاورزان زمین حاصلخیز برای کاشت ترجیح می‌دهند.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
