export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 133,
        pronunciation: "/ɪɡˈnaɪt/",
        imageUrl: "",
        word: "ignite",
        definition: "to catch fire or cause to catch fire",
        synonyms: ["light", "kindle", "spark"],
        examples: [
          "The match ignited the dry leaves.",
          "His speech ignited the crowd's enthusiasm.",
          "The gas leak could ignite at any moment.",
        ],
        wordPr: "آتش زدن",
        definitionPr: "آتش گرفتن یا باعث آتش گرفتن شدن",
        synonymsPr: ["روشن کردن", "برافروختن"],
        examplesPr: [
          "کبریت برگ‌های خشک را آتش زد.",
          "سخنرانی او اشتیاق جمعیت را برانگیخت.",
          "نشت گاز هر لحظه ممکن بود آتش بگیرد.",
        ],
      },
      {
        id: 134,
        pronunciation: "/əˈbɑːlɪʃ/",
        imageUrl: "",
        word: "abolish",
        definition:
          "to formally put an end to a system, practice, or institution",
        synonyms: ["eliminate", "eradicate", "terminate"],
        examples: [
          "The government abolished the outdated law.",
          "Slavery was abolished in the 19th century.",
          "They voted to abolish the death penalty.",
        ],
        wordPr: "لغو کردن",
        definitionPr: "به طور رسمی به سیستم، روش یا نهادی پایان دادن",
        synonymsPr: ["از بین بردن", "منسوخ کردن"],
        examplesPr: [
          "دولت قانون منسوخ را لغو کرد.",
          "برده‌داری در قرن نوزدهم لغو شد.",
          "آن‌ها به لغو مجازات اعدام رأی دادند.",
        ],
      },
      {
        id: 135,
        pronunciation: "/ˈɜːrbən/",
        imageUrl: "",
        word: "urban",
        definition: "relating to a city or town",
        synonyms: ["city", "metropolitan", "municipal"],
        examples: [
          "Urban areas are usually more crowded than rural ones.",
          "She studies urban development at university.",
          "The urban population continues to grow rapidly.",
        ],
        wordPr: "شهری",
        definitionPr: "مربوط به شهر یا شهرک",
        synonymsPr: ["متروپولیتن", "شهرداری"],
        examplesPr: [
          "مناطق شهری معمولاً از مناطق روستایی شلوغ‌تر هستند.",
          "او در دانشگاه توسعه شهری مطالعه می‌کند.",
          "جمعیت شهری به سرعت در حال رشد است.",
        ],
      },
      {
        id: 136,
        pronunciation: "/ˌpɑːpjuˈleɪʃn/",
        imageUrl: "",
        word: "population",
        definition: "all the inhabitants of a particular place",
        synonyms: ["inhabitants", "residents", "citizens"],
        examples: [
          "The population of the city is about two million.",
          "The local population opposed the new construction.",
          "The world population continues to increase.",
        ],
        wordPr: "جمعیت",
        definitionPr: "تمام ساکنان یک مکان خاص",
        synonymsPr: ["ساکنان", "مردم"],
        examplesPr: [
          "جمعیت این شهر حدود دو میلیون نفر است.",
          "جمعیت محلی با ساخت‌وساز جدید مخالفت کرد.",
          "جمعیت جهان همچنان در حال افزایش است.",
        ],
      },
      {
        id: 137,
        pronunciation: "/fræŋk/",
        imageUrl: "",
        word: "frank",
        definition: "open, honest, and direct in speech or writing",
        synonyms: ["candid", "straightforward", "blunt"],
        examples: [
          "Let me be frank - your work is not good enough.",
          "She gave a frank assessment of the situation.",
          "I appreciate your frank opinion.",
        ],
        wordPr: "صریح",
        definitionPr: "در گفتار یا نوشتار باز، صادق و مستقیم",
        synonymsPr: ["رک", "بی‌پرده"],
        examplesPr: [
          "بگذار صریح باشم - کار شما به اندازه کافی خوب نیست.",
          "او ارزیابی صریحی از وضعیت ارائه داد.",
          "من از نظر صریح شما قدردانی می‌کنم.",
        ],
      },
      {
        id: 138,
        pronunciation: "/pəˈluːt/",
        imageUrl: "",
        word: "pollute",
        definition: "to contaminate with harmful or poisonous substances",
        synonyms: ["contaminate", "poison", "taint"],
        examples: [
          "Factories pollute the air with smoke.",
          "The river was polluted by chemical waste.",
          "Plastic bags are polluting our oceans.",
        ],
        wordPr: "آلوده کردن",
        definitionPr: "با مواد مضر یا سمی آلوده کردن",
        synonymsPr: ["مسموم کردن", "نجس کردن"],
        examplesPr: [
          "کارخانه‌ها هوا را با دود آلوده می‌کنند.",
          "رودخانه توسط ضایعات شیمیایی آلوده شد.",
          "کیسه‌های پلاستیکی اقیانوس‌های ما را آلوده می‌کنند.",
        ],
      },
      {
        id: 139,
        pronunciation: "/rɪˈviːl/",
        imageUrl: "",
        word: "reveal",
        definition: "to make previously unknown information known to others",
        synonyms: ["disclose", "uncover", "expose"],
        examples: [
          "The investigation revealed serious problems.",
          "She refused to reveal her sources.",
          "The test results will be revealed tomorrow.",
        ],
        wordPr: "فاش کردن",
        definitionPr: "اطلاعات قبلاً ناشناخته را به دیگران شناساندن",
        synonymsPr: ["آشکار کردن", "برملا کردن"],
        examplesPr: [
          "تحقیق مشکلات جدی را آشکار کرد.",
          "او از فاش کردن منابعش خودداری کرد.",
          "نتایج آزمایش فردا فاش خواهد شد.",
        ],
      },
      {
        id: 140,
        pronunciation: "/prəˈhɪbɪt/",
        imageUrl: "",
        word: "prohibit",
        definition: "to formally forbid by law, rule, or other authority",
        synonyms: ["ban", "forbid", "outlaw"],
        examples: [
          "Smoking is prohibited in this building.",
          "The law prohibits discrimination based on race.",
          "Signs prohibit parking here during rush hour.",
        ],
        wordPr: "ممنوع کردن",
        definitionPr: "به طور رسمی توسط قانون، مقررات یا مرجع دیگر منع کردن",
        synonymsPr: ["قدغن کردن", "حرام کردن"],
        examplesPr: [
          "سیگار کشیدن در این ساختمان ممنوع است.",
          "قانون تبعیض نژادی را ممنوع می‌کند.",
          "تابلوها پارک کردن در اینجا را در ساعت‌های شلوغی ممنوع می‌کنند.",
        ],
      },
      {
        id: 141,
        pronunciation: "/ˈɜːrdʒənt/",
        imageUrl: "",
        word: "urgent",
        definition: "requiring immediate action or attention",
        synonyms: ["pressing", "critical", "imperative"],
        examples: [
          "This is an urgent message - please respond immediately.",
          "The patient needs urgent medical attention.",
          "There's an urgent need for clean water in the area.",
        ],
        wordPr: "فوری",
        definitionPr: "نیازمند اقدام یا توجه فوری",
        synonymsPr: ["اضطراری", "حیاتی"],
        examplesPr: [
          "این یک پیام فوری است - لطفاً فوراً پاسخ دهید.",
          "بیمار به مراقبت پزشکی فوری نیاز دارد.",
          "نیاز فوری به آب تمیز در این منطقه وجود دارد.",
        ],
      },
      {
        id: 142,
        pronunciation: "/ˈædɪkwət/",
        imageUrl: "",
        word: "adequate",
        definition: "satisfactory or acceptable in quality or quantity",
        synonyms: ["sufficient", "acceptable", "suitable"],
        examples: [
          "The food was adequate but not exceptional.",
          "Make sure you have adequate insurance coverage.",
          "His performance was adequate but not outstanding.",
        ],
        wordPr: "کافی",
        definitionPr: "از نظر کیفیت یا کمیت رضایت‌بخش یا قابل قبول",
        synonymsPr: ["مناسب", "قابل قبول"],
        examplesPr: [
          "غذا کافی بود اما استثنایی نبود.",
          "مطمئن شوید که پوشش بیمه کافی دارید.",
          "عملکرد او کافی بود اما برجسته نبود.",
        ],
      },
      {
        id: 143,
        pronunciation: "/dɪˈkriːs/",
        imageUrl: "",
        word: "decrease",
        definition:
          "to become smaller or fewer in size, amount, intensity, or degree",
        synonyms: ["reduce", "lessen", "diminish"],
        examples: [
          "The temperature decreased overnight.",
          "We need to decrease our expenses.",
          "There has been a decrease in violent crime.",
        ],
        wordPr: "کاهش دادن",
        definitionPr: "کوچک‌تر یا کمتر شدن در اندازه، مقدار، شدت یا درجه",
        synonymsPr: ["کم کردن", "تقلیل دادن"],
        examplesPr: [
          "دما در طول شب کاهش یافت.",
          "ما باید هزینه‌هایمان را کاهش دهیم.",
          "کاهش در جرایم خشونت‌آمیز وجود داشته است.",
        ],
      },
      {
        id: 144,
        pronunciation: "/ˈɔːdəbl/",
        imageUrl: "",
        word: "audible",
        definition: "able to be heard",
        synonyms: ["hearable", "perceptible", "distinct"],
        examples: [
          "Her voice was barely audible over the noise.",
          "The alarm was clearly audible throughout the building.",
          "There was an audible sigh of relief.",
        ],
        wordPr: "قابل شنیدن",
        definitionPr: "قابل شنیده شدن",
        synonymsPr: ["شنیدنی", "ملموس"],
        examplesPr: [
          "صدای او به زودی بالای سر و صدا شنیده می‌شد.",
          "هشدار به وضوح در سراسر ساختمان شنیده می‌شد.",
          "یک آهنگ قابل شنیدن از آسودگی وجود داشت.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
