export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 444,
        pronunciation: "baɪˈɒɡrəfi",
        imageUrl: "",
        word: "biography",
        definition: "a written account of someone's life",
        synonyms: ["life story", "memoir", "profile"],
        examples: [
          "He read a biography of Albert Einstein.",
          "The biography details her struggles and successes.",
          "This biography was written by a close friend.",
        ],
        wordPr: "زندگینامه",
        definitionPr: "روایتی مکتوب از زندگی یک شخص",
        synonymsPr: ["زندگی‌نامه", "شرح حال", "خاطرات"],
        examplesPr: [
          "او زندگینامه آلبرت اینشتین را خواند.",
          "این زندگینامه جزئیات تلاش‌ها و موفقیت‌های او را شرح می‌دهد.",
          "این زندگینامه توسط یکی از دوستان نزدیکش نوشته شده است.",
        ],
      },
      {
        id: 445,
        pronunciation: "drɛntʃ",
        imageUrl: "",
        word: "drench",
        definition: "to make someone or something completely wet",
        synonyms: ["soak", "wet", "saturate"],
        examples: [
          "The rain drenched us completely.",
          "He was drenched in sweat.",
          "They were drenched after falling in the river.",
        ],
        wordPr: "خیس کردن، غرق در آب کردن",
        definitionPr: "کاملاً خیس یا اشباع از مایع کردن کسی یا چیزی",
        synonymsPr: ["خیس کردن", "اشباع کردن", "تر کردن"],
        examplesPr: [
          "باران ما را کاملاً خیس کرد.",
          "او در عرق غرق شده بود.",
          "بعد از افتادن در رودخانه کاملاً خیس شدند.",
        ],
      },
      {
        id: 446,
        pronunciation: "swɔːm",
        imageUrl: "",
        word: "swarm",
        definition: "a large number of insects or people moving together",
        synonyms: ["crowd", "flock", "horde"],
        examples: [
          "A swarm of bees attacked the farmer.",
          "Tourists swarmed the market.",
          "Swarm of locusts destroyed the crops.",
        ],
        wordPr: "گروه، ازدحام",
        definitionPr: "تعداد زیادی از حشرات یا مردم که با هم حرکت می‌کنند",
        synonymsPr: ["ازدحام", "دسته", "گله"],
        examplesPr: [
          "دسته‌ای از زنبورها به کشاورز حمله کردند.",
          "گردشگران بازار را پر کردند.",
          "ازدحام ملخ‌ها محصولات را نابود کرد.",
        ],
      },
      {
        id: 447,
        pronunciation: "ˈwɒbl",
        imageUrl: "",
        word: "wobble",
        definition: "to move unsteadily from side to side",
        synonyms: ["shake", "sway", "totter"],
        examples: [
          "The table wobbles because one leg is short.",
          "He wobbled on his bike before falling.",
          "The jelly wobbled on the plate.",
        ],
        wordPr: "لق زدن، تلو تلو خوردن",
        definitionPr: "حرکت ناپایدار یا رفت و برگشتی از یک طرف به طرف دیگر",
        synonymsPr: ["لرزیدن", "تکان خوردن", "تلو خوردن"],
        examplesPr: [
          "میز لق می‌زند چون یکی از پایه‌هایش کوتاه است.",
          "او قبل از افتادن روی دوچرخه تلو تلو خورد.",
          "ژله روی بشقاب تکان می‌خورد.",
        ],
      },
      {
        id: 448,
        pronunciation: "ˈtjuːmʌlt",
        imageUrl: "",
        word: "tumult",
        definition: "a loud, confused noise, often caused by a crowd",
        synonyms: ["uproar", "commotion", "chaos"],
        examples: [
          "A tumult broke out during the protest.",
          "The speech caused a tumult in the audience.",
          "We couldn't hear over the tumult of the crowd.",
        ],
        wordPr: "هیاهو، آشوب",
        definitionPr: "صدای بلند و گیج‌کننده، معمولاً از یک جمعیت",
        synonymsPr: ["آشوب", "شلوغی", "هیاهو"],
        examplesPr: [
          "در طول اعتراض، آشوبی به پا شد.",
          "سخنرانی باعث هیاهو در میان حضار شد.",
          "به‌خاطر شلوغی جمعیت نمی‌توانستیم چیزی بشنویم.",
        ],
      },
      {
        id: 449,
        pronunciation: "niːl",
        imageUrl: "",
        word: "kneel",
        definition: "to rest on one or both knees",
        synonyms: ["genuflect", "bow", "bend down"],
        examples: [
          "She knelt to pray.",
          "He knelt before the queen.",
          "The child knelt to tie his shoes.",
        ],
        wordPr: "زانو زدن",
        definitionPr: "روی یک یا هر دو زانو نشستن یا ایستادن",
        synonymsPr: ["خم شدن", "زانو زدن", "تعظیم کردن"],
        examplesPr: [
          "او برای دعا زانو زد.",
          "او در مقابل ملکه زانو زد.",
          "کودک برای بستن بند کفشش زانو زد.",
        ],
      },
      {
        id: 450,
        pronunciation: "dɪˈdʒɛktɪd",
        imageUrl: "",
        word: "dejected",
        definition: "sad and depressed",
        synonyms: ["downcast", "gloomy", "disheartened"],
        examples: [
          "He looked dejected after failing the test.",
          "She sat in a dejected silence.",
          "The team felt dejected after the loss.",
        ],
        wordPr: "دل‌سرد، افسرده",
        definitionPr: "غمگین و ناامید",
        synonymsPr: ["افسرده", "دل‌سرد", "غمگین"],
        examplesPr: [
          "او بعد از رد شدن در آزمون ناراحت به نظر می‌رسید.",
          "او در سکوتی غمگین نشست.",
          "تیم بعد از شکست احساس ناامیدی داشت.",
        ],
      },
      {
        id: 451,
        pronunciation: "əˈbiːdiənt",
        imageUrl: "",
        word: "obedient",
        definition: "willing to do what one is told",
        synonyms: ["compliant", "submissive", "dutiful"],
        examples: [
          "The obedient dog followed every command.",
          "She is an obedient student.",
          "They expected obedient behavior from the children.",
        ],
        wordPr: "مطیع، فرمان‌بردار",
        definitionPr: "مایل به انجام دستورات یا پیروی از قوانین",
        synonymsPr: ["فرمان‌بردار", "تابع", "مطیع"],
        examplesPr: [
          "سگ مطیع از همه دستورات پیروی کرد.",
          "او دانش‌آموزی مطیع است.",
          "آن‌ها از کودکان رفتار مطیعانه انتظار داشتند.",
        ],
      },
      {
        id: 452,
        pronunciation: "rɪˈsiːd",
        imageUrl: "",
        word: "recede",
        definition: "to move back or away",
        synonyms: ["retreat", "withdraw", "ebb"],
        examples: [
          "The floodwaters finally receded.",
          "His hairline is starting to recede.",
          "The pain gradually receded.",
        ],
        wordPr: "عقب رفتن، فروکش کردن",
        definitionPr: "عقب‌نشینی کردن یا کاهش یافتن",
        synonymsPr: ["پس رفتن", "عقب‌نشینی کردن", "فروکش کردن"],
        examplesPr: [
          "آب‌های سیل بالاخره فروکش کردند.",
          "خط موی او شروع به عقب رفتن کرده است.",
          "درد به تدریج کاهش یافت.",
        ],
      },
      {
        id: 453,
        pronunciation: "ˈtaɪrənt",
        imageUrl: "",
        word: "tyrant",
        definition: "a cruel and oppressive ruler",
        synonyms: ["dictator", "despot", "oppressor"],
        examples: [
          "The tyrant ruled with an iron fist.",
          "People rose up against the tyrant.",
          "He acted like a tyrant to his employees.",
        ],
        wordPr: "ستمگر، حاکم ظالم",
        definitionPr: "رهبر ظالم و بی‌رحم",
        synonymsPr: ["دیکتاتور", "ستمگر", "ظالم"],
        examplesPr: [
          "حاکم ستمگر با مشت آهنین حکومت می‌کرد.",
          "مردم علیه حاکم ظالم قیام کردند.",
          "او با کارکنانش مانند یک ستمگر رفتار می‌کرد.",
        ],
      },
      {
        id: 454,
        pronunciation: "ˈtʃærɪti",
        imageUrl: "",
        word: "charity",
        definition: "help or gifts given to those in need",
        synonyms: ["aid", "donation", "philanthropy"],
        examples: [
          "They gave money to charity.",
          "She works for a children’s charity.",
          "Charity begins at home.",
        ],
        wordPr: "خیریه، کمک به نیازمندان",
        definitionPr: "کمک یا هدایایی برای افراد نیازمند",
        synonymsPr: ["بخشندگی", "امداد", "نیکوکاری"],
        examplesPr: [
          "آن‌ها پولی به خیریه اهدا کردند.",
          "او در یک خیریه کودکان کار می‌کند.",
          "نیکوکاری از خانه آغاز می‌شود.",
        ],
      },
      {
        id: 455,
        pronunciation: "ˈvɜːrdɪkt",
        imageUrl: "",
        word: "verdict",
        definition: "a decision made by a jury in a court",
        synonyms: ["judgment", "decision", "ruling"],
        examples: [
          "The jury returned a guilty verdict.",
          "The verdict surprised everyone.",
          "They waited anxiously for the verdict.",
        ],
        wordPr: "حکم، رأی (دادگاه)",
        definitionPr: "تصمیم یا رأی صادر شده توسط هیئت منصفه در دادگاه",
        synonymsPr: ["حکم", "رأی", "تصمیم قضایی"],
        examplesPr: [
          "هیئت منصفه رأی به گناهکار بودن داد.",
          "رأی همه را شگفت‌زده کرد.",
          "آن‌ها با اضطراب منتظر رأی دادگاه بودند.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
