export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 408,
        pronunciation: "veɪg",
        imageUrl: "",
        word: "vague",
        definition: "not clear or specific",
        synonyms: ["unclear", "indefinite", "ambiguous"],
        examples: [
          "His explanation was vague and confusing.",
          "I have a vague memory of that day.",
          "The instructions were vague and hard to follow.",
        ],
        wordPr: "مبهم، نامشخص",
        definitionPr: "غیر واضح یا مشخص نبودن",
        synonymsPr: ["مبهم", "نامشخص", "گنگ"],
        examplesPr: [
          "توضیح او مبهم و گیج‌کننده بود.",
          "یک خاطره مبهم از آن روز دارم.",
          "دستورالعمل‌ها مبهم و سخت برای دنبال کردن بودند.",
        ],
      },
      {
        id: 409,
        pronunciation: "ˈɛləˌveɪt",
        imageUrl: "",
        word: "elevate",
        definition: "to raise or lift something to a higher position",
        synonyms: ["raise", "lift", "heighten"],
        examples: [
          "The platform was elevated for better viewing.",
          "He was elevated to manager last year.",
          "Exercise can elevate your mood.",
        ],
        wordPr: "بالا بردن، ارتقاء دادن",
        definitionPr: "بالا بردن یا بلند کردن به موقعیت بالاتر",
        synonymsPr: ["بالا بردن", "ارتقاء دادن", "بلند کردن"],
        examplesPr: [
          "سکو برای دید بهتر بالا برده شد.",
          "او سال گذشته به مدیر ارتقاء یافت.",
          "ورزش می‌تواند حالت روحی شما را بالا ببرد.",
        ],
      },
      {
        id: 410,
        pronunciation: "ˈlɑːtəri",
        imageUrl: "",
        word: "lottery",
        definition: "a game where people buy tickets for a chance to win money",
        synonyms: ["raffle", "drawing", "sweepstakes"],
        examples: [
          "He won the lottery and bought a new house.",
          "The lottery ticket costs two dollars.",
          "Many people dream of winning the lottery.",
        ],
        wordPr: "لاتاری، قرعه‌کشی",
        definitionPr:
          "بازی‌ای که در آن مردم بلیت می‌خرند تا شانس برنده شدن پول داشته باشند",
        synonymsPr: ["قرعه‌کشی", "لاتاری", "بخت‌آزمایی"],
        examplesPr: [
          "او لاتاری برد و خانه جدیدی خرید.",
          "قیمت بلیت لاتاری دو دلار است.",
          "بسیاری از مردم آرزوی برنده شدن در لاتاری دارند.",
        ],
      },
      {
        id: 411,
        pronunciation: "ˈfaɪnæns",
        imageUrl: "",
        word: "finance",
        definition:
          "management of money, especially by governments or companies",
        synonyms: ["funding", "budgeting", "economics"],
        examples: [
          "The company needs finance to expand.",
          "He studied finance at university.",
          "The government manages public finance.",
        ],
        wordPr: "امور مالی، تأمین مالی",
        definitionPr: "مدیریت پول، مخصوصا توسط دولت‌ها یا شرکت‌ها",
        synonymsPr: ["تأمین مالی", "بودجه‌بندی", "اقتصاد"],
        examplesPr: [
          "شرکت برای گسترش به تأمین مالی نیاز دارد.",
          "او امور مالی را در دانشگاه مطالعه کرد.",
          "دولت امور مالی عمومی را مدیریت می‌کند.",
        ],
      },
      {
        id: 412,
        pronunciation: "əbˈteɪn",
        imageUrl: "",
        word: "obtain",
        definition: "to get or acquire something",
        synonyms: ["get", "acquire", "secure"],
        examples: [
          "You must obtain permission before entering.",
          "He obtained a degree in engineering.",
          "They obtained the necessary documents.",
        ],
        wordPr: "دریافت کردن، به دست آوردن",
        definitionPr: "گرفتن یا به دست آوردن چیزی",
        synonymsPr: ["به دست آوردن", "کسب کردن", "دریافت کردن"],
        examplesPr: [
          "قبل از ورود باید اجازه بگیرید.",
          "او مدرک مهندسی گرفت.",
          "آن‌ها مدارک لازم را دریافت کردند.",
        ],
      },
      {
        id: 413,
        pronunciation: "ˈsɪnəmə",
        imageUrl: "",
        word: "cinema",
        definition: "a place where movies are shown",
        synonyms: ["movie theater", "film theater", "picture house"],
        examples: [
          "We went to the cinema to watch a new film.",
          "The cinema was crowded last night.",
          "She loves going to the cinema.",
        ],
        wordPr: "سینما",
        definitionPr: "محلی که فیلم‌ها نمایش داده می‌شوند",
        synonymsPr: ["سینما", "سالن نمایش فیلم", "سینما"],
        examplesPr: [
          "ما برای دیدن فیلم جدید به سینما رفتیم.",
          "دیشب سینما شلوغ بود.",
          "او عاشق رفتن به سینما است.",
        ],
      },
      {
        id: 414,
        pronunciation: "ɪˈvɛnt",
        imageUrl: "",
        word: "event",
        definition: "something that happens, especially important",
        synonyms: ["occasion", "incident", "happening"],
        examples: [
          "The concert was a major event.",
          "Many people attended the event.",
          "The event took place last weekend.",
        ],
        wordPr: "رویداد، اتفاق",
        definitionPr: "چیزی که اتفاق می‌افتد، مخصوصا مهم",
        synonymsPr: ["رویداد", "واقعه", "اتفاق"],
        examplesPr: [
          "کنسرت یک رویداد مهم بود.",
          "بسیاری از مردم در رویداد شرکت کردند.",
          "رویداد آخر هفته گذشته برگزار شد.",
        ],
      },
      {
        id: 415,
        pronunciation: "dɪsˈkɑrd",
        imageUrl: "",
        word: "discard",
        definition: "to throw something away",
        synonyms: ["throw away", "get rid of", "dispose"],
        examples: [
          "He discarded the old newspapers.",
          "Please discard any expired food.",
          "The company discarded defective products.",
        ],
        wordPr: "دور انداختن",
        definitionPr: "چیزی را دور انداختن",
        synonymsPr: ["دور انداختن", "رها کردن", "بیرون ریختن"],
        examplesPr: [
          "او روزنامه‌های قدیمی را دور انداخت.",
          "لطفا غذاهای تاریخ گذشته را دور بریزید.",
          "شرکت محصولات معیوب را دور انداخت.",
        ],
      },
      {
        id: 416,
        pronunciation: "sɔːr",
        imageUrl: "",
        word: "soar",
        definition: "to fly or rise high quickly",
        synonyms: ["rise", "fly high", "increase rapidly"],
        examples: [
          "The eagle soared high in the sky.",
          "Prices soared after the announcement.",
          "His popularity continues to soar.",
        ],
        wordPr: "اوچ گرفتن، اوج گرفتن",
        definitionPr: "به سرعت بالا رفتن یا پرواز کردن",
        synonymsPr: ["بالا رفتن", "اوج گرفتن", "افزایش سریع"],
        examplesPr: [
          "عقاب در آسمان بالا اوج گرفت.",
          "قیمت‌ها بعد از اعلام افزایش یافت.",
          "محبوبیت او همچنان در حال افزایش است.",
        ],
      },
      {
        id: 417,
        pronunciation: "ˈsʌbsɪkwənt",
        imageUrl: "",
        word: "subsequent",
        definition: "happening after something else",
        synonyms: ["following", "ensuing", "later"],
        examples: [
          "Subsequent events proved him right.",
          "The subsequent chapters explain more.",
          "The subsequent meeting was canceled.",
        ],
        wordPr: "بعدی، متعاقب",
        definitionPr: "بعد از چیزی اتفاق افتادن",
        synonymsPr: ["بعدی", "متعاقب", "پس از"],
        examplesPr: [
          "رویدادهای بعدی او را درست ثابت کردند.",
          "فصل‌های بعدی بیشتر توضیح می‌دهند.",
          "جلسه بعدی لغو شد.",
        ],
      },
      {
        id: 418,
        pronunciation: "rɪˈleɪt",
        imageUrl: "",
        word: "relate",
        definition: "to show or make a connection between things",
        synonyms: ["connect", "link", "associate"],
        examples: [
          "I can relate to your feelings.",
          "The story relates events from the past.",
          "Try to relate the facts logically.",
        ],
        wordPr: "مرتبط بودن، ارتباط دادن",
        definitionPr: "نشان دادن یا برقرار کردن ارتباط بین چیزها",
        synonymsPr: ["مرتبط بودن", "ارتباط دادن", "وصل کردن"],
        examplesPr: [
          "من با احساسات تو ارتباط برقرار می‌کنم.",
          "داستان رویدادهای گذشته را تعریف می‌کند.",
          "سعی کن حقایق را منطقی ارتباط دهی.",
        ],
      },
      {
        id: 419,
        pronunciation: "ˈsteɪʃəˌnɛri",
        imageUrl: "",
        word: "stationary",
        definition: "not moving or changing",
        synonyms: ["still", "motionless", "fixed"],
        examples: [
          "The car remained stationary at the traffic light.",
          "Prices have been stationary for months.",
          "The bicycle was stationary on the ground.",
        ],
        wordPr: "ثابت، بی‌حرکت",
        definitionPr: "حرکت نکردن یا تغییر نکردن",
        synonymsPr: ["ثابت", "بی‌حرکت", "ساکن"],
        examplesPr: [
          "ماشین در چراغ قرمز ثابت ماند.",
          "قیمت‌ها ماه‌ها ثابت بوده‌اند.",
          "دوچرخه روی زمین بی‌حرکت بود.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
