export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 432,
        pronunciation: "ɛr",
        imageUrl: "",
        word: "heir",
        definition:
          "a person who will legally receive someone's money or property after they die",
        synonyms: ["successor", "inheritor", "beneficiary"],
        examples: [
          "The prince is the heir to the throne.",
          "She was named the sole heir in the will.",
          "As an heir, he inherited a large estate.",
        ],
        wordPr: "وارث",
        definitionPr:
          "شخصی که به‌طور قانونی پس از مرگ کسی، اموال یا دارایی او را به ارث می‌برد",
        synonymsPr: ["جانشین", "وارث", "ذینفع"],
        examplesPr: [
          "شاهزاده وارث تاج و تخت است.",
          "او به عنوان تنها وارث در وصیت‌نامه نام برده شد.",
          "به‌عنوان وارث، او ملکی بزرگ به ارث برد.",
        ],
      },
      {
        id: 433,
        pronunciation: "məˈdʒɛstɪk",
        imageUrl: "",
        word: "majestic",
        definition: "having or showing impressive beauty or dignity",
        synonyms: ["grand", "magnificent", "noble"],
        examples: [
          "The mountain looked majestic in the sunlight.",
          "The king entered the hall in a majestic manner.",
          "They stood in awe of the majestic palace.",
        ],
        wordPr: "باشکوه، باعظمت",
        definitionPr: "دارای زیبایی یا شکوه تأثیرگذار",
        synonymsPr: ["باابهت", "مجلل", "باوقار"],
        examplesPr: [
          "کوه در نور آفتاب بسیار باعظمت به نظر می‌رسید.",
          "پادشاه به‌صورت باشکوه وارد تالار شد.",
          "آن‌ها با احترام به کاخ باعظمت نگاه کردند.",
        ],
      },
      {
        id: 434,
        pronunciation: "ˈdwɪndl",
        imageUrl: "",
        word: "dwindle",
        definition: "to gradually become smaller or less",
        synonyms: ["decrease", "diminish", "shrink"],
        examples: [
          "Their savings gradually dwindled.",
          "The crowd began to dwindle after the event.",
          "Resources are dwindling fast.",
        ],
        wordPr: "کاهش یافتن، رفته‌رفته کم شدن",
        definitionPr: "کم یا کوچک‌تر شدن تدریجی",
        synonymsPr: ["کاهش یافتن", "کم شدن", "کوچک شدن"],
        examplesPr: [
          "پس‌انداز آن‌ها به‌تدریج کاهش یافت.",
          "بعد از مراسم، جمعیت شروع به کم شدن کرد.",
          "منابع به‌سرعت در حال کاهش هستند.",
        ],
      },
      {
        id: 435,
        pronunciation: "ˈsɜːrpləs",
        imageUrl: "",
        word: "surplus",
        definition: "an amount that is more than what is needed",
        synonyms: ["excess", "extra", "overflow"],
        examples: [
          "We had a surplus of food after the party.",
          "The company sold its surplus inventory.",
          "They donated the surplus to charity.",
        ],
        wordPr: "مازاد، اضافی",
        definitionPr: "مقداری که بیش از نیاز است",
        synonymsPr: ["اضافی", "مازاد", "باقی‌مانده"],
        examplesPr: [
          "بعد از مهمانی غذای اضافی داشتیم.",
          "شرکت موجودی مازاد خود را فروخت.",
          "آن‌ها مازاد را به خیریه اهدا کردند.",
        ],
      },
      {
        id: 436,
        pronunciation: "ˈtreɪtər",
        imageUrl: "",
        word: "traitor",
        definition:
          "a person who betrays their country, friends, or principles",
        synonyms: ["betrayer", "turncoat", "deceiver"],
        examples: [
          "He was considered a traitor for revealing secrets.",
          "The traitor was caught and punished.",
          "Betraying one’s country makes you a traitor.",
        ],
        wordPr: "خائن",
        definitionPr: "شخصی که به کشور، دوستان یا اصول خود خیانت می‌کند",
        synonymsPr: ["خائن", "فریبکار", "جاسوس"],
        examplesPr: [
          "او به‌خاطر افشای اسرار، خائن شناخته شد.",
          "خائن دستگیر و مجازات شد.",
          "خیانت به کشور، تو را خائن می‌کند.",
        ],
      },
      {
        id: 437,
        pronunciation: "dɪˈlɪbərət",
        imageUrl: "",
        word: "deliberate",
        definition: "done intentionally and carefully",
        synonyms: ["intentional", "planned", "purposeful"],
        examples: [
          "It was a deliberate attempt to confuse us.",
          "She spoke in a slow and deliberate way.",
          "His actions were not accidental; they were deliberate.",
        ],
        wordPr: "عمدی، حساب‌شده",
        definitionPr: "با قصد قبلی و با دقت انجام شده",
        synonymsPr: ["عمدی", "برنامه‌ریزی‌شده", "آگاهانه"],
        examplesPr: [
          "این تلاش عمدی برای گیج کردن ما بود.",
          "او آهسته و حساب‌شده صحبت کرد.",
          "کارهایش تصادفی نبود؛ عمدی بودند.",
        ],
      },
      {
        id: 438,
        pronunciation: "ˈvændl",
        imageUrl: "",
        word: "vandal",
        definition: "a person who deliberately destroys or damages property",
        synonyms: ["destroyer", "hoodlum", "hooligan"],
        examples: [
          "Vandals broke the windows of the school.",
          "The statue was damaged by vandals.",
          "Police caught the vandal responsible for the graffiti.",
        ],
        wordPr: "خرابکار (اموال عمومی)",
        definitionPr: "فردی که به‌عمد اموال را تخریب یا آسیب می‌زند",
        synonymsPr: ["خرابکار", "متجاوز", "اشرار"],
        examplesPr: [
          "خرابکاران شیشه‌های مدرسه را شکستند.",
          "مجسمه توسط خرابکاران آسیب دید.",
          "پلیس خرابکاری که گرافیتی کشیده بود را دستگیر کرد.",
        ],
      },
      {
        id: 439,
        pronunciation: "draʊt",
        imageUrl: "",
        word: "drought",
        definition: "a long period of dry weather without rain",
        synonyms: ["dry spell", "aridity", "water shortage"],
        examples: [
          "The drought ruined many crops.",
          "Farmers struggled during the drought.",
          "A long drought affected the entire region.",
        ],
        wordPr: "خشکسالی",
        definitionPr: "دوره‌ای طولانی بدون بارندگی",
        synonymsPr: ["بی‌آبی", "خشکی", "کمبود آب"],
        examplesPr: [
          "خشکسالی محصولات زیادی را نابود کرد.",
          "کشاورزان در طول خشکسالی با مشکل روبرو بودند.",
          "خشکسالی طولانی تمام منطقه را تحت تاثیر قرار داد.",
        ],
      },
      {
        id: 440,
        pronunciation: "əˈbaɪd",
        imageUrl: "",
        word: "abide",
        definition: "to accept or follow rules or decisions",
        synonyms: ["obey", "accept", "follow"],
        examples: [
          "You must abide by the rules.",
          "He cannot abide dishonesty.",
          "We will abide by the decision.",
        ],
        wordPr: "پایبند بودن، رعایت کردن",
        definitionPr: "پذیرفتن یا تبعیت از قوانین یا تصمیمات",
        synonymsPr: ["رعایت کردن", "اطاعت کردن", "پذیرفتن"],
        examplesPr: [
          "باید از قوانین پیروی کنید.",
          "او نمی‌تواند با دروغ کنار بیاید.",
          "ما از تصمیم تبعیت خواهیم کرد.",
        ],
      },
      {
        id: 441,
        pronunciation: "ˈjuːnɪfaɪ",
        imageUrl: "",
        word: "unify",
        definition: "to bring together and make one",
        synonyms: ["combine", "merge", "integrate"],
        examples: [
          "The leader’s speech helped unify the people.",
          "We need to unify our efforts.",
          "The country was unified after the war.",
        ],
        wordPr: "متحد کردن، یکپارچه ساختن",
        definitionPr: "با هم ترکیب کردن و یکپارچه ساختن",
        synonymsPr: ["یکپارچه کردن", "ترکیب کردن", "متحد کردن"],
        examplesPr: [
          "سخنرانی رهبر باعث اتحاد مردم شد.",
          "باید تلاش‌هایمان را یکپارچه کنیم.",
          "کشور بعد از جنگ متحد شد.",
        ],
      },
      {
        id: 442,
        pronunciation: "ˈsʌmɪt",
        imageUrl: "",
        word: "summit",
        definition: "the highest point; a meeting of leaders",
        synonyms: ["peak", "top", "conference"],
        examples: [
          "They climbed to the summit of the mountain.",
          "The summit meeting was attended by world leaders.",
          "Reaching the summit took several hours.",
        ],
        wordPr: "قله، اجلاس سران",
        definitionPr: "بالاترین نقطه یا جلسه‌ای بین رهبران",
        synonymsPr: ["قله", "نقطه اوج", "اجلاس"],
        examplesPr: [
          "آن‌ها به قله کوه صعود کردند.",
          "اجلاس سران با حضور رهبران جهان برگزار شد.",
          "رسیدن به قله چندین ساعت طول کشید.",
        ],
      },
      {
        id: 443,
        pronunciation: "hiːd",
        imageUrl: "",
        word: "heed",
        definition: "to pay attention to or take notice of",
        synonyms: ["notice", "observe", "follow"],
        examples: [
          "He failed to heed the warning.",
          "You should heed your doctor’s advice.",
          "The driver did not heed the red light.",
        ],
        wordPr: "توجه کردن، گوش دادن",
        definitionPr: "توجه یا دقت کردن به چیزی",
        synonymsPr: ["توجه کردن", "گوش دادن", "ملاحظه کردن"],
        examplesPr: [
          "او به هشدار توجه نکرد.",
          "باید به توصیه‌های پزشک خود گوش دهی.",
          "راننده به چراغ قرمز توجه نکرد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
