export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 61,
        pronunciation: "əˈproʊtʃ",
        imageUrl: "",
        word: "approach",
        definition: "come near or nearer to",
        synonyms: ["come near", "move toward"],
        examples: [
          "The lawyers approached the judge with their questions.",
          "As we approached the airport, we saw planes taking off.",
          "Winter is approaching.",
        ],
        wordPr: "نزدیک شدن",
        definitionPr: "نزدیک شدن یا نزدیک‌تر شدن به چیزی",
        synonymsPr: ["نزدیک شدن", "روبرو شدن"],
        examplesPr: [
          "وکیلان با سوالات خود به قاضی نزدیک شدند.",
          "وقتی به فرودگاه نزدیک شدیم، هواپیماها را دیدیم که بلند می‌شوند.",
          "زمستان در حال نزدیک شدن است.",
        ],
      },
      {
        id: 62,
        pronunciation: "dɪˈtɛkt",
        imageUrl: "",
        word: "detect",
        definition: "find out; discover",
        synonyms: ["discover", "notice"],
        examples: [
          "The police detective tried to detect who committed the crime.",
          "It is not easy to detect a lie.",
          "Doctors can detect some diseases early.",
        ],
        wordPr: "کشف کردن، پی بردن",
        definitionPr: "پیدا کردن یا کشف کردن",
        synonymsPr: ["کشف کردن", "پی بردن"],
        examplesPr: [
          "کارآگاه پلیس سعی کرد بفهمد چه کسی جرم را مرتکب شده است.",
          "تشخیص یک دروغ آسان نیست.",
          "پزشکان می‌توانند برخی بیماری‌ها را زود تشخیص دهند.",
        ],
      },
      {
        id: 63,
        pronunciation: "ˈdiːfɛkt",
        imageUrl: "",
        word: "defect",
        definition: "fault; that which is wrong",
        synonyms: ["fault", "flaw"],
        examples: [
          "There was a defect in the machine.",
          "The car was recalled because of a defect.",
          "Every system has some defects.",
        ],
        wordPr: "عیب، نقص",
        definitionPr: "اشکال یا نقص",
        synonymsPr: ["عیب", "نقص"],
        examplesPr: [
          "در دستگاه یک عیب وجود داشت.",
          "ماشین به خاطر نقص بازگردانده شد.",
          "هر سیستمی برخی نقص‌ها دارد.",
        ],
      },
      {
        id: 64,
        pronunciation: "ɪmˈplɔɪiː",
        imageUrl: "",
        word: "employee",
        definition: "a person who works for pay",
        synonyms: ["worker", "staff"],
        examples: [
          "The company has many employees.",
          "Every employee must wear an ID badge.",
          "She is a loyal employee.",
        ],
        wordPr: "کارمند",
        definitionPr: "شخصی که برای حقوق کار می‌کند",
        synonymsPr: ["کارمند", "کارگر"],
        examplesPr: [
          "شرکت کارمندان زیادی دارد.",
          "هر کارمند باید کارت شناسایی داشته باشد.",
          "او کارمند وفاداری است.",
        ],
      },
      {
        id: 65,
        pronunciation: "nɪˈɡlɛkt",
        imageUrl: "",
        word: "neglect",
        definition: "give too little care or attention to",
        synonyms: ["ignore", "disregard"],
        examples: [
          "He neglected his homework.",
          "The building fell into disrepair because of neglect.",
          "Don't neglect your health.",
        ],
        wordPr: "غفلت کردن، بی‌توجهی",
        definitionPr: "توجه یا مراقبت کافی نکردن",
        synonymsPr: ["غفلت کردن", "بی‌توجهی"],
        examplesPr: [
          "او به تکالیفش بی‌توجهی کرد.",
          "ساختمان به خاطر بی‌توجهی خراب شد.",
          "به سلامت خود بی‌توجهی نکن.",
        ],
      },
      {
        id: 66,
        pronunciation: "dɪˈsiːv",
        imageUrl: "",
        word: "deceive",
        definition: "make someone believe as true something that is false",
        synonyms: ["mislead", "trick"],
        examples: [
          "He deceived me about the cost.",
          "Appearances can deceive.",
          "She was deceived by his words.",
        ],
        wordPr: "فریب دادن",
        definitionPr: "باوراندن چیزی نادرست به کسی",
        synonymsPr: ["فریب دادن", "گول زدن"],
        examplesPr: [
          "او درباره هزینه من را فریب داد.",
          "ظاهر می‌تواند فریب‌دهنده باشد.",
          "او با حرف‌هایش فریب خورد.",
        ],
      },
      {
        id: 67,
        pronunciation: "ʌnˈdaʊtɪdli",
        imageUrl: "",
        word: "undoubtedly",
        definition: "certainly; beyond doubt",
        synonyms: ["certainly", "surely"],
        examples: [
          "He is undoubtedly the best player on the team.",
          "This will undoubtedly cause problems.",
          "She is undoubtedly talented.",
        ],
        wordPr: "بدون شک",
        definitionPr: "قطعاً؛ بدون تردید",
        synonymsPr: ["قطعاً", "بدون شک"],
        examplesPr: [
          "او بدون شک بهترین بازیکن تیم است.",
          "این بدون شک مشکلاتی ایجاد خواهد کرد.",
          "او بدون شک با استعداد است.",
        ],
      },
      {
        id: 68,
        pronunciation: "ˈpɑːpjələr",
        imageUrl: "",
        word: "popular",
        definition: "liked by many people",
        synonyms: ["well-liked", "favored"],
        examples: [
          "Soccer is a popular sport worldwide.",
          "She is very popular at school.",
          "This song is popular among teenagers.",
        ],
        wordPr: "محبوب",
        definitionPr: "دوست‌داشتنی برای بسیاری از مردم",
        synonymsPr: ["محبوب", "پرطرفدار"],
        examplesPr: [
          "فوتبال یک ورزش محبوب در سراسر جهان است.",
          "او در مدرسه بسیار محبوب است.",
          "این آهنگ بین نوجوانان محبوب است.",
        ],
      },
      {
        id: 69,
        pronunciation: "ˈθʌroʊ",
        imageUrl: "",
        word: "thorough",
        definition: "being all that is needed; complete",
        synonyms: ["complete", "detailed"],
        examples: [
          "She gave the room a thorough cleaning.",
          "The police made a thorough search.",
          "He is thorough in his work.",
        ],
        wordPr: "کامل، دقیق",
        definitionPr: "کامل؛ با جزئیات",
        synonymsPr: ["کامل", "دقیق"],
        examplesPr: [
          "او اتاق را کاملاً تمیز کرد.",
          "پلیس جستجوی کاملی انجام داد.",
          "او در کارش دقیق است.",
        ],
      },
      {
        id: 70,
        pronunciation: "ˈklaɪənt",
        imageUrl: "",
        word: "client",
        definition: "person for whom a lawyer, accountant, etc. is acting",
        synonyms: ["customer", "patron"],
        examples: [
          "The lawyer met with her client.",
          "We have many clients in Europe.",
          "The company values its clients.",
        ],
        wordPr: "مشتری، موکل",
        definitionPr: "کسی که از خدمات حرفه‌ای استفاده می‌کند",
        synonymsPr: ["مشتری", "موکل"],
        examplesPr: [
          "وکیل با موکلش ملاقات کرد.",
          "ما مشتریان زیادی در اروپا داریم.",
          "شرکت برای مشتریانش ارزش قائل است.",
        ],
      },
      {
        id: 71,
        pronunciation: "ˌkɑːmprɪˈhɛnsɪv",
        imageUrl: "",
        word: "comprehensive",
        definition: "including much; covering completely",
        synonyms: ["complete", "inclusive"],
        examples: [
          "She gave a comprehensive explanation.",
          "The exam was comprehensive.",
          "We need a comprehensive plan.",
        ],
        wordPr: "جامع، فراگیر",
        definitionPr: "شامل همه چیز؛ کامل",
        synonymsPr: ["جامع", "فراگیر"],
        examplesPr: [
          "او توضیح جامعی داد.",
          "امتحان جامع بود.",
          "ما به یک برنامه جامع نیاز داریم.",
        ],
      },
      {
        id: 72,
        pronunciation: "dɪˈfrɔːd",
        imageUrl: "",
        word: "defraud",
        definition: "take money, rights, etc. away by cheating",
        synonyms: ["cheat", "swindle"],
        examples: [
          "He was accused of defrauding the company.",
          "They tried to defraud the bank.",
          "She was defrauded of her savings.",
        ],
        wordPr: "کلاهبرداری کردن",
        definitionPr: "گرفتن پول یا حقوق با تقلب",
        synonymsPr: ["کلاهبرداری کردن", "فریب دادن"],
        examplesPr: [
          "او به کلاهبرداری از شرکت متهم شد.",
          "آنها سعی کردند از بانک کلاهبرداری کنند.",
          "پس‌اندازش را از او کلاهبرداری کردند.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
