export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 157,
        pronunciation: "/ʌnˈruːli/",
        imageUrl: "",
        word: "unruly",
        definition:
          "disorderly and disruptive and not amenable to discipline or control",
        synonyms: ["disobedient", "unmanageable", "wild"],
        examples: [
          "The teacher struggled with the unruly class.",
          "His unruly hair stuck out in all directions.",
          "The protest started to become unruly.",
        ],
        wordPr: "نافرمان",
        definitionPr: "بی‌نظم، مختل‌کننده و غیرقابل کنترل",
        synonymsPr: ["سرکش", "آشفته"],
        examplesPr: [
          "معلم با کلاس نافرمان دست و پنجه نرم می‌کرد.",
          "موهای آشفته‌اش به همه طرف торع می‌زد.",
          "اعتراض شروع به تبدیل شدن به وضعیتی ناآرام کرد.",
        ],
      },
      {
        id: 158,
        pronunciation: "/ˈraɪvl/",
        imageUrl: "",
        word: "rival",
        definition:
          "a person or thing competing with another for the same objective or for superiority",
        synonyms: ["competitor", "opponent", "challenger"],
        examples: [
          "The two companies have been rivals for years.",
          "He defeated his main rival in the election.",
          "No computer can rival a human brain for complexity.",
        ],
        wordPr: "رقیب",
        definitionPr:
          "شخص یا چیزی که برای همان هدف یا برتری با دیگری رقابت می‌کند",
        synonymsPr: ["حریف", "همچشم"],
        examplesPr: [
          "این دو شرکت سال‌هاست که رقیب هم هستند.",
          "او در انتخابات رقیب اصلی خود را شکست داد.",
          "هیچ کامپیوتری نمی‌تواند با پیچیدگی مغز انسان رقابت کند.",
        ],
      },
      {
        id: 159,
        pronunciation: "/ˈvaɪələnt/",
        imageUrl: "",
        word: "violent",
        definition:
          "using or involving physical force intended to hurt, damage, or kill",
        synonyms: ["brutal", "aggressive", "fierce"],
        examples: [
          "The movie contains violent scenes.",
          "He had a violent temper when provoked.",
          "The protest turned violent in the afternoon.",
        ],
        wordPr: "خشونت‌آمیز",
        definitionPr: "استفاده از نیروی فیزیکی با قصد آسیب، تخریب یا کشتن",
        synonymsPr: ["خشن", "وحشیانه"],
        examplesPr: [
          "فیلم شامل صحنه‌های خشونت‌آمیز است.",
          "وقتی عصبانی می‌شد خلق‌وخوی خشنی داشت.",
          "اعتراضات بعدازظهر به خشونت کشیده شد.",
        ],
      },
      {
        id: 160,
        pronunciation: "/ˈbruːtl/",
        imageUrl: "",
        word: "brutal",
        definition: "savagely violent; extremely ruthless or cruel",
        synonyms: ["savage", "vicious", "merciless"],
        examples: [
          "The murder was particularly brutal.",
          "The team suffered a brutal defeat.",
          "The summer heat was brutal this year.",
        ],
        wordPr: "وحشیانه",
        definitionPr: "به شکل وحشیانه‌ای خشن؛ بی‌رحم یا ظالم",
        synonymsPr: ["خشن", "بی‌رحم"],
        examplesPr: [
          "قتل به ویژه وحشیانه بود.",
          "تیم شکست سختی متحمل شد.",
          "گرمای تابستان امسال بسیار شدید بود.",
        ],
      },
      {
        id: 161,
        pronunciation: "/əˈpoʊnənt/",
        imageUrl: "",
        word: "opponent",
        definition:
          "someone who competes against or fights another in a contest, game, or argument",
        synonyms: ["rival", "adversary", "competitor"],
        examples: [
          "He shook hands with his opponent after the match.",
          "She's a fierce opponent of the new law.",
          "The champion defeated all his opponents.",
        ],
        wordPr: "حریف",
        definitionPr:
          "کسی که در مسابقه، بازی یا بحث با دیگری رقابت یا مبارزه می‌کند",
        synonymsPr: ["رقیب", "مخالف"],
        examplesPr: [
          "او پس از مسابقه با حریفش دست داد.",
          "او مخالف سرسخت قانون جدید است.",
          "قهرمان همه حریفان خود را شکست داد.",
        ],
      },
      {
        id: 162,
        pronunciation: "/brɔːl/",
        imageUrl: "",
        word: "brawl",
        definition: "a rough or noisy fight or quarrel",
        synonyms: ["fight", "scuffle", "fracas"],
        examples: [
          "A brawl broke out in the bar.",
          "The political debate turned into a verbal brawl.",
          "Two players were ejected for brawling on the field.",
        ],
        wordPr: "دعوا",
        definitionPr: "یک نزاع یا مشاجره خشن یا پرسر و صدا",
        synonymsPr: ["زدوخورد", "جنجال"],
        examplesPr: [
          "در بار دعوایی شروع شد.",
          "مناظره سیاسی به یک مشاجره لفظی تبدیل شد.",
          "دو بازیکن به دلیل دعوا در زمین اخراج شدند.",
        ],
      },
      {
        id: 163,
        pronunciation: "/ˈduːplɪkeɪt/",
        imageUrl: "",
        word: "duplicate",
        definition:
          "exactly like something else, especially through having been copied",
        synonyms: ["copy", "replica", "reproduction"],
        examples: [
          "Keep the original and give me the duplicate.",
          "The thief used duplicate keys to enter the house.",
          "The experiment was duplicated in three different labs.",
        ],
        wordPr: "تکراری",
        definitionPr: "دقیقاً شبیه چیز دیگری، مخصوصاً از طریق کپی شدن",
        synonymsPr: ["کپی", "همانند"],
        examplesPr: [
          "اصل را نگه دار و کپی را به من بده.",
          "دزد از کلیدهای تکراری برای ورود به خانه استفاده کرد.",
          "آزمایش در سه آزمایشگاه مختلف تکرار شد.",
        ],
      },
      {
        id: 164,
        pronunciation: "/ˈvɪʃəs/",
        imageUrl: "",
        word: "vicious",
        definition: "deliberately cruel or violent",
        synonyms: ["savage", "brutal", "ferocious"],
        examples: [
          "The dog gave him a vicious bite.",
          "She launched a vicious attack on her opponent.",
          "The storm caused vicious damage to the coast.",
        ],
        wordPr: "شرور",
        definitionPr: "عمداً ظالم یا خشن",
        synonymsPr: ["خبیث", "وحشی"],
        examplesPr: [
          "سگ او را به طور وحشیانه‌ای گاز گرفت.",
          "او حمله شرورانه‌ای به حریفش ترتیب داد.",
          "طوفان خسارات شدیدی به ساحل وارد کرد.",
        ],
      },
      {
        id: 165,
        pronunciation: "/ˈwɜːrlɪŋ/",
        imageUrl: "",
        word: "whirling",
        definition: "moving rapidly in circles; spinning",
        synonyms: ["spinning", "rotating", "twirling"],
        examples: [
          "The leaves were whirling in the wind.",
          "Dancers performed whirling movements.",
          "He felt his head was whirling after the accident.",
        ],
        wordPr: "چرخان",
        definitionPr: "حرکت سریع به صورت دایره‌ای؛ چرخیدن",
        synonymsPr: ["چرخنده", "پیچان"],
        examplesPr: [
          "برگ‌ها در باد می‌چرخیدند.",
          "رقصندگان حرکات چرخشی انجام دادند.",
          "او پس از حادثه احساس می‌کرد سرش می‌چرخد.",
        ],
      },
      {
        id: 166,
        pronunciation: "/ˈʌndərdɔːɡ/",
        imageUrl: "",
        word: "underdog",
        definition: "a competitor thought to have little chance of winning",
        synonyms: ["longshot", "outsider", "dark horse"],
        examples: [
          "Everyone loves to cheer for the underdog.",
          "The team was considered the underdog in the tournament.",
          "The underdog candidate surprisingly won the election.",
        ],
        wordPr: "تیم ضعیف",
        definitionPr: "رقمی که تصور می‌شود شانس کمی برای برنده شدن دارد",
        synonymsPr: ["بازنده احتمالی", "غیرمحتمل"],
        examplesPr: [
          "همه دوست دارند برای تیم ضعیف تر هواداری کنند.",
          "این تیم در مسابقات به عنوان تیم ضعیف‌تر در نظر گرفته می‌شد.",
          "کاندیدای ضعیف به طور غیرمنتظره‌ای انتخابات را برد.",
        ],
      },
      {
        id: 167,
        pronunciation: "/θrʌst/",
        imageUrl: "",
        word: "thrust",
        definition: "to push suddenly or violently in a specified direction",
        synonyms: ["shove", "push", "propel"],
        examples: [
          "He thrust the money into his pocket.",
          "The sword thrust pierced his armor.",
          "The company is thrust into a leadership position.",
        ],
        wordPr: "فشار دادن",
        definitionPr: "ناگهانی یا با خشونت به جهتی خاص هل دادن",
        synonymsPr: ["پرتاب کردن", "هل دادن"],
        examplesPr: [
          "او پول را به جیبش فرو کرد.",
          "ضربه شمشیر زره او را سوراخ کرد.",
          "شرکت به موقعیت رهبری پرتاب شد.",
        ],
      },
      {
        id: 168,
        pronunciation: "/bɪˈwɪldərd/",
        imageUrl: "",
        word: "bewildered",
        definition: "perplexed and confused; very puzzled",
        synonyms: ["confused", "baffled", "disoriented"],
        examples: [
          "The complex instructions left him completely bewildered.",
          "She looked around with a bewildered expression.",
          "The sudden change of plans bewildered everyone.",
        ],
        wordPr: "گیج",
        definitionPr: "سردرگم و آشفته؛ بسیار متحیر",
        synonymsPr: ["متحیر", "سرگردان"],
        examplesPr: [
          "دستورالعمل‌های پیچیده او را کاملاً گیج کرد.",
          "او با چهره‌ای متحیر به اطراف نگاه کرد.",
          "تغییر ناگهانی برنامه‌ها همه را گیج کرد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
