export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      [
        {
          id: 156,
          pronunciation: "/ˈdʒɜːrnəlɪst/",
          imageUrl: "",
          word: "journalist",
          definition:
            "a person who writes for newspapers, magazines, or news websites or prepares news to be broadcast",
          synonyms: ["reporter", "correspondent", "columnist"],
          examples: [
            "The journalist interviewed the president for an hour.",
            "She works as a journalist for a major newspaper.",
            "Several journalists were covering the royal wedding.",
          ],
          wordPr: "روزنامه‌نگار",
          definitionPr:
            "شخصی که برای روزنامه‌ها، مجلات یا وبسایت‌های خبری می‌نویسد یا اخبار را برای پخش آماده می‌کند",
          synonymsPr: ["گزارشگر", "خبرنگار"],
          examplesPr: [
            "روزنامه‌نگار به مدت یک ساعت با رئیس‌جمهور مصاحبه کرد.",
            "او به عنوان روزنامه‌نگار برای یک روزنامه بزرگ کار می‌کند.",
            "چندین روزنامه‌نگار در حال پوشش خبری عروسی سلطنتی بودند.",
          ],
        },
        {
          id: 145,
          pronunciation: "/ˈfæmɪn/",
          imageUrl: "",
          word: "famine",
          definition: "extreme scarcity of food",
          synonyms: ["starvation", "hunger", "food shortage"],
          examples: [
            "The drought caused widespread famine in the region.",
            "Millions died during the Irish potato famine.",
            "International aid helped relieve the famine.",
          ],
          wordPr: "قحطی",
          definitionPr: "کمبود شدید غذا",
          synonymsPr: ["گرسنگی", "کمبود مواد غذایی"],
          examplesPr: [
            "خشکسالی باعث قحطی گسترده در منطقه شد.",
            "میلیون‌ها نفر در طول قحطی سیب‌زمینی ایرلند جان باختند.",
            "کمک‌های بین‌المللی به کاهش قحطی کمک کرد.",
          ],
        },
        {
          id: 146,
          pronunciation: "/rɪˈvaɪv/",
          imageUrl: "",
          word: "revive",
          definition: "to restore to life or consciousness",
          synonyms: ["resuscitate", "renew", "restore"],
          examples: [
            "Doctors managed to revive the heart attack victim.",
            "The rain revived the dying plants.",
            "They're trying to revive interest in classical music.",
          ],
          wordPr: "زنده کردن",
          definitionPr: "به زندگی یا هوشیاری بازگرداندن",
          synonymsPr: ["نوسازی کردن", "بازگرداندن"],
          examplesPr: [
            "پزشکان توانستند قربانی حمله قلبی را احیا کنند.",
            "باران گیاهان در حال مرگ را احیا کرد.",
            "آنها در حال تلاش برای احیای علاقه به موسیقی کلاسیک هستند.",
          ],
        },
        {
          id: 147,
          pronunciation: "/kəˈmens/",
          imageUrl: "",
          word: "commence",
          definition: "to begin",
          synonyms: ["start", "initiate", "launch"],
          examples: [
            "The ceremony will commence at noon.",
            "Construction is scheduled to commence next month.",
            "She commenced her speech with a joke.",
          ],
          wordPr: "شروع کردن",
          definitionPr: "آغاز کردن",
          synonymsPr: ["آغاز کردن", "راه انداختن"],
          examplesPr: [
            "مراسم ظهر آغاز خواهد شد.",
            "ساخت و ساز برای ماه آینده برنامه‌ریزی شده است.",
            "او سخنرانی خود را با یک لطیفه آغاز کرد.",
          ],
        },
        {
          id: 148,
          pronunciation: "/əbˈzɜːrvənt/",
          imageUrl: "",
          word: "observant",
          definition: "quick to notice things",
          synonyms: ["perceptive", "attentive", "alert"],
          examples: [
            "An observant neighbor noticed the broken window.",
            "She's very observant of people's moods.",
            "The observant child saw the bird first.",
          ],
          wordPr: "توجه‌کننده",
          definitionPr: "سریع در متوجه شدن چیزها",
          synonymsPr: ["هوشیار", "زیرک"],
          examplesPr: [
            "یک همسایه تیزبین پنجره شکسته را متوجه شد.",
            "او به حالات مردم بسیار توجه می‌کند.",
            "کودک تیزبین پرنده را اول دید.",
          ],
        },
        {
          id: 149,
          pronunciation: "/aɪˈdentɪfaɪ/",
          imageUrl: "",
          word: "identify",
          definition:
            "to recognize or establish as being a particular person or thing",
          synonyms: ["recognize", "distinguish", "determine"],
          examples: [
            "Can you identify the man in this photo?",
            "The test will help identify any problems.",
            "She identified strongly with the main character.",
          ],
          wordPr: "شناسایی کردن",
          definitionPr: "تشخیص دادن یا ثابت کردن اینکه شخص یا چیز خاصی است",
          synonymsPr: ["تشخیص دادن", "تمیز دادن"],
          examplesPr: [
            "آیا می‌توانید مرد موجود در این عکس را شناسایی کنید؟",
            "آزمایش به شناسایی هرگونه مشکل کمک خواهد کرد.",
            "او به شدت با شخصیت اصلی همذات‌پنداری کرد.",
          ],
        },
        {
          id: 150,
          pronunciation: "/ˈmaɪɡreɪt/",
          imageUrl: "",
          word: "migrate",
          definition: "to move from one region or habitat to another",
          synonyms: ["relocate", "move", "travel"],
          examples: [
            "Many birds migrate south for the winter.",
            "People migrated to cities for work.",
            "The whales migrate along the coast.",
          ],
          wordPr: "مهاجرت کردن",
          definitionPr: "از یک منطقه یا زیستگاه به منطقه دیگر نقل مکان کردن",
          synonymsPr: ["جابجا شدن", "کوچ کردن"],
          examplesPr: [
            "بسیاری از پرندگان برای زمستان به جنوب مهاجرت می‌کنند.",
            "مردم برای کار به شهرها مهاجرت کردند.",
            "نهنگ‌ها در امتداد ساحل مهاجرت می‌کنند.",
          ],
        },
        {
          id: 151,
          pronunciation: "/ˈvesl/",
          imageUrl: "",
          word: "vessel",
          definition: "a ship or large boat; a hollow container for liquids",
          synonyms: ["ship", "boat", "container"],
          examples: [
            "The vessel sank during the storm.",
            "Blood flows through the blood vessels.",
            "She poured the liquid into a glass vessel.",
          ],
          wordPr: "کشتی/رگ",
          definitionPr: "یک کشتی یا قایق بزرگ؛ ظرف توخالی برای مایعات",
          synonymsPr: ["سفینه", "ظرف"],
          examplesPr: [
            "کشتی در طول طوفان غرق شد.",
            "خون از طریق رگ‌های خونی جریان می‌یابد.",
            "او مایع را در یک ظرف شیشه‌ای ریخت.",
          ],
        },
        {
          id: 152,
          pronunciation: "/pərˈsɪst/",
          imageUrl: "",
          word: "persist",
          definition: "to continue firmly in spite of difficulty or opposition",
          synonyms: ["continue", "persevere", "endure"],
          examples: [
            "If symptoms persist, consult a doctor.",
            "He persisted in asking difficult questions.",
            "The rain persisted all day.",
          ],
          wordPr: "پافشاری کردن",
          definitionPr: "با وجود مشکل یا مخالفت به طور محکم ادامه دادن",
          synonymsPr: ["استقامت کردن", "ادامه دادن"],
          examplesPr: [
            "اگر علائم ادامه یافت، به پزشک مراجعه کنید.",
            "او به پرسیدن سوالات دشوار ادامه داد.",
            "باران تمام روز ادامه داشت.",
          ],
        },
        {
          id: 153,
          pronunciation: "/ˈheɪzi/",
          imageUrl: "",
          word: "hazy",
          definition: "covered by a haze; vague or unclear",
          synonyms: ["foggy", "misty", "indistinct"],
          examples: [
            "The mountains were hazy in the distance.",
            "I have only a hazy memory of that day.",
            "The photo was too hazy to recognize anyone.",
          ],
          wordPr: "مه‌آلود",
          definitionPr: "پوشیده از مه؛ مبهم یا نامشخص",
          synonymsPr: ["غبارآلود", "مبهم"],
          examplesPr: [
            "کوه‌ها در دوردست مه‌آلود بودند.",
            "من فقط خاطره مبهمی از آن روز دارم.",
            "عکس خیلی مه‌آلود بود و نمی‌شد کسی را تشخیص داد.",
          ],
        },
        {
          id: 154,
          pronunciation: "/ɡliːm/",
          imageUrl: "",
          word: "gleam",
          definition: "to shine brightly, especially with reflected light",
          synonyms: ["glow", "shine", "glisten"],
          examples: [
            "The polished wood gleamed in the sunlight.",
            "I saw a gleam of light in the darkness.",
            "Her eyes gleamed with excitement.",
          ],
          wordPr: "درخشیدن",
          definitionPr: "به شدت درخشیدن، مخصوصاً با نور منعکس شده",
          synonymsPr: ["تابیدن", "برق زدن"],
          examplesPr: [
            "چوب صیقلی در نور خورشید می‌درخشید.",
            "من درخششی از نور را در تاریکی دیدم.",
            "چشمانش از هیجان می‌درخشید.",
          ],
        },
        {
          id: 155,
          pronunciation: "/ˈedɪtər/",
          imageUrl: "",
          word: "editor",
          definition: "a person who prepares material for publication",
          synonyms: ["publisher", "reviser", "proofreader"],
          examples: [
            "The editor suggested changes to my article.",
            "She works as an editor for a fashion magazine.",
            "The film editor assembled the final cut.",
          ],
          wordPr: "ویراستار",
          definitionPr: "شخصی که مطالب را برای انتشار آماده می‌کند",
          synonymsPr: ["ناشر", "بازبین"],
          examplesPr: [
            "ویراستار تغییراتی را به مقاله من پیشنهاد داد.",
            "او به عنوان ویراستار برای یک مجله مد کار می‌کند.",
            "ویراستار فیلم نسخه نهایی را مونتاژ کرد.",
          ],
        },
      ],
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
