export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 337,
        pronunciation: "tɔɪl",
        imageUrl: "",
        word: "toil",
        definition: "to work hard and continuously",
        synonyms: ["labor", "work hard", "drudge"],
        examples: [
          "They toiled all day in the fields.",
          "She toiled to finish the project on time.",
          "Farmers toil under the hot sun.",
        ],
        wordPr: "زحمت کشیدن، سخت کار کردن",
        definitionPr: "سخت و پیوسته کار کردن",
        synonymsPr: ["زحمت کشیدن", "سخت کار کردن", "کوشیدن"],
        examplesPr: [
          "آن‌ها تمام روز در مزرعه زحمت کشیدند.",
          "او برای به موقع تمام کردن پروژه زحمت کشید.",
          "کشاورزان زیر آفتاب داغ سخت کار می‌کنند.",
        ],
      },
      {
        id: 338,
        pronunciation: "ˈblʌndər",
        imageUrl: "",
        word: "blunder",
        definition: "a careless or stupid mistake",
        synonyms: ["mistake", "error", "slip"],
        examples: [
          "He made a blunder in the report.",
          "The blunder cost them the game.",
          "She apologized for her blunder.",
        ],
        wordPr: "اشتباه بزرگ، خطا",
        definitionPr: "یک اشتباه بی‌دقت یا احمقانه",
        synonymsPr: ["اشتباه", "خطا", "لغزش"],
        examplesPr: [
          "او در گزارش اشتباه بزرگی کرد.",
          "این اشتباه باعث باخت آن‌ها شد.",
          "او بابت اشتباهش عذرخواهی کرد.",
        ],
      },
      {
        id: 339,
        pronunciation: "deɪz",
        imageUrl: "",
        word: "daze",
        definition: "a state of confusion or stunned feeling",
        synonyms: ["stun", "confuse", "bewilder"],
        examples: [
          "The accident left him in a daze.",
          "She was in a daze after hearing the news.",
          "The bright lights caused a daze.",
        ],
        wordPr: "گیجی، منگ شدن",
        definitionPr: "حالت گیجی یا احساس شوکه شدن",
        synonymsPr: ["شوک", "گیجی", "حیرت"],
        examplesPr: [
          "تصادف او را گیج کرد.",
          "او پس از شنیدن خبر در حالت گیجی بود.",
          "نورهای روشن باعث گیجی شدند.",
        ],
      },
      {
        id: 340,
        pronunciation: "mɔrn",
        imageUrl: "",
        word: "mourn",
        definition: "to feel or show sorrow for someone who has died",
        synonyms: ["grieve", "lament", "bewail"],
        examples: [
          "They mourned the loss of their friend.",
          "The whole town mourned the tragedy.",
          "She mourns her grandmother deeply.",
        ],
        wordPr: "سوگواری کردن، عزاداری کردن",
        definitionPr: "احساس یا نشان دادن غم برای کسی که فوت کرده",
        synonymsPr: ["غمگین شدن", "سوگواری", "اندوه"],
        examplesPr: [
          "آن‌ها برای از دست دادن دوستشان عزاداری کردند.",
          "تمام شهر برای آن فاجعه عزادار بود.",
          "او برای مادربزرگش بسیار عزادار است.",
        ],
      },
      {
        id: 341,
        pronunciation: "səbˈsaɪd",
        imageUrl: "",
        word: "subside",
        definition: "to become less strong or intense",
        synonyms: ["lessen", "decrease", "abate"],
        examples: [
          "The storm began to subside after midnight.",
          "His anger finally subsided.",
          "Floodwaters subsided slowly.",
        ],
        wordPr: "کم شدن، فروکش کردن",
        definitionPr: "ضعیف‌تر یا کمتر شدن شدت چیزی",
        synonymsPr: ["کم شدن", "فروکش کردن", "تضعیف شدن"],
        examplesPr: [
          "طوفان بعد از نیمه‌شب فروکش کرد.",
          "خشم او بالاخره کم شد.",
          "آب سیل به آرامی فروکش کرد.",
        ],
      },
      {
        id: 342,
        pronunciation: "meɪm",
        imageUrl: "",
        word: "maim",
        definition: "to injure someone seriously causing permanent damage",
        synonyms: ["injure", "cripple", "disable"],
        examples: [
          "The explosion maimed several people.",
          "He was maimed in the accident.",
          "War can maim innocent civilians.",
        ],
        wordPr: "مجروح کردن، ناقص کردن",
        definitionPr: "آسیب جدی رساندن به کسی که باعث نقص دائمی شود",
        synonymsPr: ["آسیب زدن", "نقص عضو", "از کار انداختن"],
        examplesPr: [
          "انفجار چند نفر را مجروح کرد.",
          "او در حادثه دچار نقص عضو شد.",
          "جنگ می‌تواند غیرنظامیان بی‌گناه را مجروح کند.",
        ],
      },
      {
        id: 343,
        pronunciation: "ˌkɑmprɪˈhɛnd",
        imageUrl: "",
        word: "comprehend",
        definition: "to understand fully",
        synonyms: ["understand", "grasp", "realize"],
        examples: [
          "She could not comprehend the question.",
          "It’s hard to comprehend such a tragedy.",
          "He finally comprehended the problem.",
        ],
        wordPr: "درک کردن، فهمیدن",
        definitionPr: "به طور کامل فهمیدن",
        synonymsPr: ["فهمیدن", "دریافتن", "درک کردن"],
        examplesPr: [
          "او نمی‌توانست سؤال را درک کند.",
          "درک چنین فاجعه‌ای سخت است.",
          "او بالاخره مشکل را فهمید.",
        ],
      },
      {
        id: 344,
        pronunciation: "kəˈmɛnd",
        imageUrl: "",
        word: "commend",
        definition: "to praise or express approval",
        synonyms: ["praise", "applaud", "recommend"],
        examples: [
          "The teacher commended her for good work.",
          "He was commended for bravery.",
          "We commend you on your success.",
        ],
        wordPr: "تحسین کردن، تمجید کردن",
        definitionPr: "ستایش یا ابراز تأیید",
        synonymsPr: ["تحسین کردن", "تمجید کردن", "تشویق کردن"],
        examplesPr: [
          "معلم برای کار خوبش او را تحسین کرد.",
          "او به خاطر شجاعتش تحسین شد.",
          "ما موفقیت شما را تحسین می‌کنیم.",
        ],
      },
      {
        id: 345,
        pronunciation: "ˈfaɪnəl",
        imageUrl: "",
        word: "final",
        definition: "last or concluding",
        synonyms: ["last", "ultimate", "conclusive"],
        examples: [
          "This is the final decision.",
          "The final exam was difficult.",
          "They reached the final stage of the competition.",
        ],
        wordPr: "نهایی، آخرین",
        definitionPr: "آخرین یا نتیجه‌گیری",
        synonymsPr: ["نهایی", "آخرین", "قطعی"],
        examplesPr: [
          "این تصمیم نهایی است.",
          "آزمون نهایی سخت بود.",
          "آن‌ها به مرحله نهایی مسابقه رسیدند.",
        ],
      },
      {
        id: 346,
        pronunciation: "ɪɡˈzɛmpt",
        imageUrl: "",
        word: "exempt",
        definition: "free from an obligation or rule",
        synonyms: ["excused", "excluded", "immune"],
        examples: [
          "Students with special needs are exempt from exams.",
          "He was exempt from paying taxes.",
          "Some employees are exempt from overtime.",
        ],
        wordPr: "معاف شده",
        definitionPr: "رها شده از یک تعهد یا قانون",
        synonymsPr: ["معاف", "مستثنی", "بی‌نیاز"],
        examplesPr: [
          "دانش‌آموزان با نیازهای ویژه از امتحانات معاف هستند.",
          "او از پرداخت مالیات معاف بود.",
          "برخی کارکنان از اضافه‌کاری معاف هستند.",
        ],
      },
      {
        id: 347,
        pronunciation: "veɪn",
        imageUrl: "",
        word: "vain",
        definition: "having too much pride in oneself; unsuccessful",
        synonyms: ["proud", "conceited", "futile"],
        examples: [
          "He is so vain about his appearance.",
          "Their efforts were in vain.",
          "She made a vain attempt to fix it.",
        ],
        wordPr: "خودبین، بیهوده",
        definitionPr: "داشتن غرور زیاد نسبت به خود؛ بی‌نتیجه",
        synonymsPr: ["خودبین", "متکبر", "بی‌فایده"],
        examplesPr: [
          "او نسبت به ظاهرش بسیار خودبین است.",
          "تلاش‌های آن‌ها بیهوده بود.",
          "او تلاش بیهوده‌ای برای رفع آن کرد.",
        ],
      },
      {
        id: 348,
        pronunciation: "ˌrɛpɪˈtɪʃən",
        imageUrl: "",
        word: "repetition",
        definition: "the act of doing something again",
        synonyms: ["repeat", "iteration", "recurrence"],
        examples: [
          "Repetition helps to memorize vocabulary.",
          "The repetition of the exercise improved her skills.",
          "Too much repetition can be boring.",
        ],
        wordPr: "تکرار",
        definitionPr: "عمل انجام دادن چیزی دوباره",
        synonymsPr: ["تکرار", "تکرار مجدد", "دوباره انجام دادن"],
        examplesPr: [
          "تکرار به حفظ لغات کمک می‌کند.",
          "تکرار تمرین مهارت‌های او را بهتر کرد.",
          "تکرار زیاد می‌تواند خسته‌کننده باشد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
