export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 193,
        pronunciation: "/əˈpiːl/",
        imageUrl: "",
        word: "appeal",
        definition:
          "a serious or urgent request, typically one made to the public",
        synonyms: ["plea", "request", "petition"],
        examples: [
          "The charity made an appeal for donations.",
          "The lawyer filed an appeal against the decision.",
          "Her argument had great appeal to the audience.",
        ],
        wordPr: "درخواست",
        definitionPr: "یک درخواست جدی یا فوری، معمولاً به عموم مردم",
        synonymsPr: ["تمنا", "تقاضا"],
        examplesPr: [
          "خیریه درخواستی برای کمک‌های مالی کرد.",
          "وکیل درخواست تجدید نظر علیه تصمیم داد.",
          "استدلال او برای مخاطبان جذابیت زیادی داشت.",
        ],
      },
      {
        id: 194,
        pronunciation: "/ˈædɪkt/",
        imageUrl: "",
        word: "addict",
        definition: "someone who is unable to stop using a drug or activity",
        synonyms: ["user", "junkie", "enthusiast"],
        examples: [
          "He became a drug addict after his injury.",
          "She's a complete coffee addict.",
          "The program helps addicts recover.",
        ],
        wordPr: "معتاد",
        definitionPr:
          "کسی که نمی‌تواند استفاده از دارو یا فعالیتی را متوقف کند",
        synonymsPr: ["وابسته", "علاقه‌مند"],
        examplesPr: [
          "او پس از آسیب‌اش به مواد مخدر معتاد شد.",
          "او کاملاً به قهوه معتاد است.",
          "این برنامه به معتادان کمک می‌کند تا بهبود یابند.",
        ],
      },
      {
        id: 195,
        pronunciation: "/ˈwɛri/",
        imageUrl: "",
        word: "wary",
        definition:
          "feeling or showing caution about possible dangers or problems",
        synonyms: ["cautious", "careful", "suspicious"],
        examples: [
          "Be wary of strangers offering gifts.",
          "She was wary of making quick decisions.",
          "Investors are wary about the market.",
        ],
        wordPr: "هوشیار",
        definitionPr: "احتیاط در مورد خطرات یا مشکلات احتمالی",
        synonymsPr: ["محتاط", "مراقب"],
        examplesPr: [
          "از غریبه‌هایی که هدیه می‌دهند هوشیار باشید.",
          "او از گرفتن تصمیمات سریع محتاط بود.",
          "سرمایه‌گذاران در مورد بازار محتاط هستند.",
        ],
      },
      {
        id: 196,
        pronunciation: "/əˈwɛr/",
        imageUrl: "",
        word: "aware",
        definition: "having knowledge or perception of a situation or fact",
        synonyms: ["conscious", "informed", "knowledgeable"],
        examples: [
          "Are you aware of the risks involved?",
          "He wasn't aware that he was being followed.",
          "We need to make people aware of this issue.",
        ],
        wordPr: "آگاه",
        definitionPr: "داشتن دانش یا درک از یک موقعیت یا واقعیت",
        synonymsPr: ["هشیار", "مطلع"],
        examplesPr: [
          "آیا از خطرات مربوطه آگاه هستید؟",
          "او نمی‌دانست که تحت تعقیب است.",
          "ما باید مردم را از این موضوع آگاه کنیم.",
        ],
      },
      {
        id: 197,
        pronunciation: "/mɪsˈfɔːrtʃən/",
        imageUrl: "",
        word: "misfortune",
        definition: "bad luck or an unlucky event",
        synonyms: ["trouble", "hardship", "disaster"],
        examples: [
          "She had the misfortune of losing her job.",
          "It was his misfortune to be there at the wrong time.",
          "They suffered a series of misfortunes.",
        ],
        wordPr: "بدشانسی",
        definitionPr: "شانس بد یا یک رویداد ناگوار",
        synonymsPr: ["بدبختی", "مصیبت"],
        examplesPr: [
          "او بدشانسی آورد و شغلش را از دست داد.",
          "بدشانسی او بود که در زمان نامناسب آنجا بود.",
          "آنها متحمل یک سری بدبیاری‌ها شدند.",
        ],
      },
      {
        id: 198,
        pronunciation: "/əˈvɔɪd/",
        imageUrl: "",
        word: "avoid",
        definition: "to keep away from or stop oneself from doing something",
        synonyms: ["evade", "escape", "shun"],
        examples: [
          "I try to avoid eating junk food.",
          "He avoided answering the question.",
          "She took a detour to avoid traffic.",
        ],
        wordPr: "اجتناب کردن",
        definitionPr: "دوری کردن یا خودداری از انجام کاری",
        synonymsPr: ["پرهیز کردن", "فرار کردن"],
        examplesPr: [
          "من سعی می‌کنم از خوردن غذاهای ناسالم پرهیز کنم.",
          "او از پاسخ دادن به سوال اجتناب کرد.",
          "او برای جلوگیری از ترافیک راه دیگری را انتخاب کرد.",
        ],
      },
      {
        id: 199,
        pronunciation: "/ˈrɛtʃɪd/",
        imageUrl: "",
        word: "wretched",
        definition: "in a very unhappy or unfortunate state",
        synonyms: ["miserable", "unhappy", "pitiful"],
        examples: [
          "The refugees were living in wretched conditions.",
          "I felt wretched after hearing the news.",
          "What wretched weather we're having!",
        ],
        wordPr: "بدبخت",
        definitionPr: "در وضعیتی بسیار ناراحت یا بدشانس",
        synonymsPr: ["بیچاره", "تیره‌بخت"],
        examplesPr: [
          "پناهندگان در شرایط بدی زندگی می‌کردند.",
          "پس از شنیدن خبر احساس بدبختی کردم.",
          "چه هوای بدی داریم!",
        ],
      },
      {
        id: 200,
        pronunciation: "/kɛɡ/",
        imageUrl: "",
        word: "keg",
        definition: "a small barrel, typically holding beer",
        synonyms: ["barrel", "cask", "drum"],
        examples: [
          "They tapped a new keg for the party.",
          "The brewery produces beer in kegs and bottles.",
          "We ordered a keg for the celebration.",
        ],
        wordPr: "ظرف آبجو",
        definitionPr: "یک بشکه کوچک، معمولاً حاوی آبجو",
        synonymsPr: ["بشکه", "خمره"],
        examplesPr: [
          "آنها برای مهمانی یک ظرف آبجو جدید باز کردند.",
          "کارخانه آبجوسازی آبجو را در ظرف‌ها و بطری‌ها تولید می‌کند.",
          "ما برای جشن یک ظرف آبجو سفارش دادیم.",
        ],
      },
      {
        id: 201,
        pronunciation: "/ˈnɜːrɪʃ/",
        imageUrl: "",
        word: "nourish",
        definition:
          "to provide with food or other substances necessary for growth and health",
        synonyms: ["feed", "sustain", "nurture"],
        examples: [
          "The soil nourishes the plants.",
          "She nourished her baby with breast milk.",
          "Reading nourishes the mind.",
        ],
        wordPr: "تغذیه کردن",
        definitionPr: "فراهم کردن غذا یا مواد دیگر لازم برای رشد و سلامتی",
        synonymsPr: ["پرورش دادن", "حفظ کردن"],
        examplesPr: [
          "خاک به گیاهان غذا می‌دهد.",
          "او کودکش را با شیر مادر تغذیه کرد.",
          "خواندن ذهن را تغذیه می‌کند.",
        ],
      },
      {
        id: 202,
        pronunciation: "/hɑːrʃ/",
        imageUrl: "",
        word: "harsh",
        definition: "unpleasantly rough or jarring to the senses",
        synonyms: ["rough", "severe", "cruel"],
        examples: [
          "The winters here are very harsh.",
          "He received harsh punishment for his actions.",
          "The light was too harsh for photography.",
        ],
        wordPr: "سخت",
        definitionPr: "به طور ناخوشایند خشن یا ناهنجار برای حواس",
        synonymsPr: ["شدید", "بی‌رحمانه"],
        examplesPr: [
          "زمستان‌های اینجا بسیار سخت است.",
          "او به خاطر اعمالش مجازات سختی دریافت کرد.",
          "نور برای عکاسی خیلی شدید بود.",
        ],
      },
      {
        id: 203,
        pronunciation: "/ˈkwɑːntəti/",
        imageUrl: "",
        word: "quantity",
        definition: "the amount or number of something",
        synonyms: ["amount", "number", "volume"],
        examples: [
          "We need a large quantity of wood.",
          "The exact quantity is unknown.",
          "Quality is more important than quantity.",
        ],
        wordPr: "مقدار",
        definitionPr: "میزان یا تعداد چیزی",
        synonymsPr: ["تعداد", "حجم"],
        examplesPr: [
          "ما به مقدار زیادی چوب نیاز داریم.",
          "مقدار دقیق آن ناشناخته است.",
          "کیفیت از مقدار مهم‌تر است.",
        ],
      },
      {
        id: 204,
        pronunciation: "/ɑːpt/",
        imageUrl: "",
        word: "opt",
        definition: "to make a choice or decision",
        synonyms: ["choose", "select", "decide"],
        examples: [
          "Many students opt to study abroad.",
          "We opted for the cheaper alternative.",
          "You can opt out of the program at any time.",
        ],
        wordPr: "انتخاب کردن",
        definitionPr: "یک انتخاب یا تصمیم گرفتن",
        synonymsPr: ["برگزیدن", "تصمیم گرفتن"],
        examplesPr: [
          "بسیاری از دانشجویان انتخاب می‌کنند که در خارج تحصیل کنند.",
          "ما گزینه ارزان‌تر را انتخاب کردیم.",
          "شما می‌توانید هر زمان از برنامه انصراف دهید.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
