export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 349,
        pronunciation: "dɪˈpɪkt",
        imageUrl: "",
        word: "depict",
        definition: "to show or represent by a picture or words",
        synonyms: ["portray", "illustrate", "describe"],
        examples: [
          "The painting depicts a beautiful landscape.",
          "The book depicts life in ancient times.",
          "The movie depicts the struggles of refugees.",
        ],
        wordPr: "تصویر کردن، به تصویر کشیدن",
        definitionPr: "نشان دادن یا توصیف کردن با تصویر یا کلمات",
        synonymsPr: ["نشان دادن", "تصویر کردن", "توصیف کردن"],
        examplesPr: [
          "نقاشی منظره زیبایی را به تصویر می‌کشد.",
          "کتاب زندگی در دوران قدیم را توصیف می‌کند.",
          "فیلم مبارزات پناهندگان را نشان می‌دهد.",
        ],
      },
      {
        id: 350,
        pronunciation: "ˈmɔrtəl",
        imageUrl: "",
        word: "mortal",
        definition: "subject to death; causing death",
        synonyms: ["fatal", "deadly", "human"],
        examples: [
          "All humans are mortal.",
          "The wound was mortal.",
          "They faced a mortal danger.",
        ],
        wordPr: "فانی، کشنده",
        definitionPr: "مشمول مرگ؛ کشنده",
        synonymsPr: ["کشنده", "مرگبار", "فانی"],
        examplesPr: [
          "تمام انسان‌ها فانی هستند.",
          "زخم کشنده بود.",
          "آن‌ها با خطر مرگباری روبرو شدند.",
        ],
      },
      {
        id: 351,
        pronunciation: "ˈnɑvəl",
        imageUrl: "",
        word: "novel",
        definition:
          "a long written story about imaginary characters and events",
        synonyms: ["story", "book", "fiction"],
        examples: [
          "She wrote a novel about war.",
          "The novel became a bestseller.",
          "He enjoys reading historical novels.",
        ],
        wordPr: "رمان",
        definitionPr: "داستان بلند نوشته شده درباره شخصیت‌ها و اتفاقات خیالی",
        synonymsPr: ["داستان", "کتاب", "داستان خیالی"],
        examplesPr: [
          "او رمانی درباره جنگ نوشت.",
          "این رمان پرفروش شد.",
          "او از خواندن رمان‌های تاریخی لذت می‌برد.",
        ],
      },
      {
        id: 352,
        pronunciation: "ˈɑkjəpənt",
        imageUrl: "",
        word: "occupant",
        definition: "a person who lives or works in a particular place",
        synonyms: ["resident", "tenant", "inhabitant"],
        examples: [
          "The occupant of the house is on vacation.",
          "The car's occupant was injured.",
          "All occupants must evacuate the building.",
        ],
        wordPr: "ساکن، متصرف",
        definitionPr: "شخصی که در مکان خاصی زندگی یا کار می‌کند",
        synonymsPr: ["ساکن", "مستأجر", "اهل محل"],
        examplesPr: [
          "ساکن خانه در تعطیلات است.",
          "سرنشین ماشین زخمی شد.",
          "تمام ساکنان باید ساختمان را ترک کنند.",
        ],
      },
      {
        id: 353,
        pronunciation: "əˈpɔɪnt",
        imageUrl: "",
        word: "appoint",
        definition: "to officially choose someone for a position or duty",
        synonyms: ["assign", "designate", "nominate"],
        examples: [
          "They appointed him as the new manager.",
          "The president appointed a new ambassador.",
          "She was appointed to lead the committee.",
        ],
        wordPr: "منصوب کردن، تعیین کردن",
        definitionPr: "رسمی انتخاب کردن کسی برای یک موقعیت یا وظیفه",
        synonymsPr: ["منصوب کردن", "تعیین کردن", "انتخاب کردن"],
        examplesPr: [
          "آن‌ها او را به عنوان مدیر جدید منصوب کردند.",
          "رئیس‌جمهور سفیر جدیدی منصوب کرد.",
          "او برای رهبری کمیته منصوب شد.",
        ],
      },
      {
        id: 354,
        pronunciation: "ˈkwɔrtər",
        imageUrl: "",
        word: "quarter",
        definition: "one of four equal parts; a district or area of a city",
        synonyms: ["district", "area", "section"],
        examples: [
          "He lives in the French quarter of the city.",
          "The cake was cut into four quarters.",
          "We spent the night in the student quarter.",
        ],
        wordPr: "ربع، منطقه",
        definitionPr: "یکی از چهار بخش مساوی؛ منطقه یا ناحیه‌ای از شهر",
        synonymsPr: ["ناحیه", "منطقه", "بخش"],
        examplesPr: [
          "او در منطقه فرانسوی شهر زندگی می‌کند.",
          "کیک به چهار قسمت تقسیم شد.",
          "شب را در منطقه دانشجویی گذراندیم.",
        ],
      },
      {
        id: 355,
        pronunciation: "saɪt",
        imageUrl: "",
        word: "site",
        definition: "a place where something happened or is located",
        synonyms: ["location", "place", "area"],
        examples: [
          "They visited the archaeological site.",
          "The construction site is closed today.",
          "This is the site of the old castle.",
        ],
        wordPr: "محل، موقعیت",
        definitionPr: "مکانی که چیزی در آن اتفاق افتاده یا قرار دارد",
        synonymsPr: ["مکان", "محل", "ناحیه"],
        examplesPr: [
          "آن‌ها از محل باستان‌شناسی بازدید کردند.",
          "محل ساخت و ساز امروز بسته است.",
          "این محل قلعه قدیمی است.",
        ],
      },
      {
        id: 356,
        pronunciation: "kwoʊt",
        imageUrl: "",
        word: "quote",
        definition: "to repeat someone's words exactly",
        synonyms: ["cite", "repeat", "mention"],
        examples: [
          "He quoted a famous author in his speech.",
          "She likes to quote poetry.",
          "The article quotes several experts.",
        ],
        wordPr: "نقل قول کردن",
        definitionPr: "تکرار دقیق کلمات کسی",
        synonymsPr: ["نقل قول", "استناد", "ذکر"],
        examplesPr: [
          "او در سخنرانی خود از یک نویسنده مشهور نقل قول کرد.",
          "او دوست دارد شعر نقل قول کند.",
          "مقاله چندین کارشناس را نقل کرده است.",
        ],
      },
      {
        id: 357,
        pronunciation: "vɜrs",
        imageUrl: "",
        word: "verse",
        definition: "a line of poetry or a part of a song",
        synonyms: ["stanza", "line", "poem"],
        examples: [
          "He wrote a beautiful verse.",
          "The song has four verses.",
          "She memorized the first verse of the poem.",
        ],
        wordPr: "بند شعر، مصرع",
        definitionPr: "یک خط شعر یا بخشی از آهنگ",
        synonymsPr: ["بند شعر", "مصرع", "شعر"],
        examplesPr: [
          "او یک بند شعر زیبا نوشت.",
          "آهنگ چهار بند دارد.",
          "او بند اول شعر را حفظ کرد.",
        ],
      },
      {
        id: 358,
        pronunciation: "məˈrælɪti",
        imageUrl: "",
        word: "morality",
        definition: "principles concerning right and wrong behavior",
        synonyms: ["ethics", "values", "morals"],
        examples: [
          "The book discusses issues of morality.",
          "She has a strong sense of morality.",
          "Morality varies across cultures.",
        ],
        wordPr: "اخلاق، اخلاقیات",
        definitionPr: "اصول مربوط به رفتار درست و غلط",
        synonymsPr: ["اخلاق", "ارزش‌ها", "معیارها"],
        examplesPr: [
          "کتاب مسائل اخلاقی را بررسی می‌کند.",
          "او حس قوی از اخلاق دارد.",
          "اخلاق در فرهنگ‌ها متفاوت است.",
        ],
      },
      {
        id: 359,
        pronunciation: "roʊm",
        imageUrl: "",
        word: "roam",
        definition: "to move about without a fixed purpose or direction",
        synonyms: ["wander", "travel", "rove"],
        examples: [
          "The animals roam freely in the forest.",
          "He likes to roam the city at night.",
          "They roamed through the countryside.",
        ],
        wordPr: "گشتن، پرسه زدن",
        definitionPr: "حرکت کردن بدون هدف یا جهت مشخص",
        synonymsPr: ["پرسه زدن", "گشتن", "پرچم زدن"],
        examplesPr: [
          "حیوانات آزادانه در جنگل می‌گردند.",
          "او دوست دارد شب‌ها در شهر پرسه بزند.",
          "آن‌ها در روستا گشتند.",
        ],
      },
      {
        id: 360,
        pronunciation: "əˈtrækt",
        imageUrl: "",
        word: "attract",
        definition: "to draw attention or interest",
        synonyms: ["draw", "appeal", "entice"],
        examples: [
          "The garden attracts many visitors.",
          "Bright colors attract butterflies.",
          "He was attracted to her kindness.",
        ],
        wordPr: "جذب کردن",
        definitionPr: "جلب توجه یا علاقه کردن",
        synonymsPr: ["جذب کردن", "کشیدن", "فریفتن"],
        examplesPr: [
          "باغ گردشگران زیادی را جذب می‌کند.",
          "رنگ‌های روشن پروانه‌ها را جذب می‌کنند.",
          "او به مهربانی او جذب شد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
