export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 13,
        pronunciation: "kɔːrps",
        imageUrl: "",

        word: "corpse",
        definition: "a dead body, usually of a person",
        synonyms: ["dead body", "cadaver"],
        examples: [
          "When given all the data on the corpse, the professor was able to solve the murder.",
          "The corpse was laid to rest in the cemetery.",
          "The police found the corpse in the abandoned house.",
        ],

        wordPr: "جسد",
        definitionPr: "بدن مرده، معمولاً انسان",
        synonymsPr: ["جسد", "لاشه"],
        examplesPr: [
          "وقتی همه اطلاعات جسد را به استاد دادند، او توانست قتل را حل کند.",
          "جسد در قبرستان به خاک سپرده شد.",
          "پلیس جسد را در خانه متروکه پیدا کرد.",
        ],
      },
      {
        id: 14,
        pronunciation: "kənˈsiːl",
        imageUrl: "",
        word: "conceal",
        definition: "hide",
        synonyms: ["hide", "cover"],
        examples: [
          "Tris could not conceal his love for Gloria.",
          "The money was concealed in a tin box.",
          "As the dismal reports of the election came in, the senator's friends tactfully made no mention of them.",
        ],
        wordPr: "پنهان کردن",
        definitionPr: "مخفی کردن",
        synonymsPr: ["پنهان کردن", "مخفی کردن"],
        examplesPr: [
          "تریس نتوانست عشقش به گلوریا را پنهان کند.",
          "پول در یک جعبه فلزی پنهان شده بود.",
          "همزمان با رسیدن گزارش‌های ناامیدکننده‌ی انتخابات، دوستان سناتور با تدبیر و زیرکی هیچ اشاره‌ای به آنها نکردند.",
        ],
      },
      {
        id: 16,
        pronunciation: "ˈfrɪdʒɪd",
        imageUrl: "",
        word: "frigid",
        definition: "very cold",
        synonyms: ["freezing", "icy"],
        examples: [
          "The climbers faced frigid temperatures on the mountain.",
          "The frigid air made it hard to breathe.",
          "She gave him a frigid look.",
        ],
        wordPr: "خیلی سرد",
        definitionPr: "بسیار سرد",
        synonymsPr: ["یخ‌زده", "منجمد"],
        examplesPr: [
          "کوهنوردان با دمای بسیار سرد در کوه روبرو شدند.",
          "هوای خیلی سرد نفس کشیدن را سخت کرده بود.",
          "او نگاه سردی به او انداخت.",
        ],
      },
      {
        id: 17,
        pronunciation: "ɪnˈhæbɪt",
        imageUrl: "",
        word: "inhabit",
        definition: "live in",
        synonyms: ["reside", "occupy"],
        examples: [
          "Eskimos inhabit the frigid part of Alaska.",
          "These woods are inhabited by many birds.",
          "Some people inhabit the desert regions.",
        ],
        wordPr: "سکونت داشتن",
        definitionPr: "زندگی کردن در جایی",
        synonymsPr: ["ساکن بودن", "اقامت داشتن"],
        examplesPr: [
          "اسکیموها در بخش‌های سرد آلاسکا زندگی می‌کنند.",
          "این جنگل‌ها محل سکونت پرندگان زیادی است.",
          "برخی مردم در مناطق بیابانی زندگی می‌کنند.",
        ],
      },
      {
        id: 18,
        pronunciation: "nʌm",
        imageUrl: "",
        word: "numb",
        definition: "having lost the power of feeling or movement",
        synonyms: ["insensible", "deadened"],
        examples: [
          "My fingers were numb with cold.",
          "After the accident, his legs were numb.",
          "The shock left her numb.",
        ],
        wordPr: "بی‌حس",
        definitionPr: "از دست دادن حس یا حرکت",
        synonymsPr: ["بی‌حس", "کرخت"],
        examplesPr: [
          "انگشتانم از سرما بی‌حس شده بودند.",
          "بعد از تصادف پاهایش بی‌حس شد.",
          "شوک او را بی‌حس کرد.",
        ],
      },
      {
        id: 19,
        pronunciation: "ˈperəl",
        imageUrl: "",
        word: "peril",
        definition: "danger",
        synonyms: ["danger", "risk"],
        examples: [
          "The sailors faced the peril of the storm.",
          "He put his life in peril to save the child.",
          "Ignoring the warning was done at their own peril.",
        ],
        wordPr: "خطر",
        definitionPr: "خطر، ریسک",
        synonymsPr: ["خطر", "ریسک"],
        examplesPr: [
          "ملوانان با خطر طوفان روبرو شدند.",
          "او برای نجات کودک جانش را به خطر انداخت.",
          "نادیده گرفتن هشدار به مسئولیت خودشان بود.",
        ],
      },
      {
        id: 20,
        pronunciation: "rɪˈklaɪn",
        imageUrl: "",
        word: "recline",
        definition: "stretch out; lean back",
        synonyms: ["lie down", "lean back"],
        examples: [
          "He reclined on the sofa and read a book.",
          "You may recline your seat during the flight.",
          "She likes to recline in her chair after work.",
        ],
        wordPr: "دراز کشیدن، لم دادن",
        definitionPr: "دراز کشیدن یا تکیه دادن",
        synonymsPr: ["دراز کشیدن", "لم دادن"],
        examplesPr: [
          "او روی مبل دراز کشید و کتاب خواند.",
          "می‌توانید صندلی خود را در طول پرواز بخوابانید.",
          "او دوست دارد بعد از کار روی صندلی‌اش لم بدهد.",
        ],
      },
      {
        id: 21,
        pronunciation: "ʃrɪŋk",
        imageUrl: "",
        word: "shrink",
        definition: "draw back; get smaller",
        synonyms: ["contract", "diminish"],
        examples: [
          "The sweater shrank after washing.",
          "He tried to shrink from his responsibilities.",
          "The cat shrank in fear.",
        ],
        wordPr: "کوچک شدن، عقب کشیدن",
        definitionPr: "عقب کشیدن یا کوچک شدن",
        synonymsPr: ["کوچک شدن", "عقب کشیدن"],
        examplesPr: [
          "پلیور بعد از شستن کوچک شد.",
          "او سعی کرد از مسئولیت‌هایش شانه خالی کند.",
          "گربه از ترس عقب کشید.",
        ],
      },
      {
        id: 22,
        pronunciation: "ˈsɪnɪstər",
        imageUrl: "",
        word: "sinister",
        definition: "evil; wicked; dishonest; frightening",
        synonyms: ["evil", "ominous"],
        examples: [
          "The sinister-looking man frightened the children.",
          "There was something sinister about the abandoned house.",
          "His sinister plan was discovered by the police.",
        ],
        wordPr: "شوم، بدشگون",
        definitionPr: "بد، ترسناک یا شیطانی",
        synonymsPr: ["شوم", "بدشگون"],
        examplesPr: [
          "مرد شوم بچه‌ها را ترساند.",
          "چیزی شوم در مورد خانه متروکه وجود داشت.",
          "پلیس نقشه شوم او را کشف کرد.",
        ],
      },
      {
        id: 23,
        pronunciation: "tempt",
        imageUrl: "",
        word: "tempt",
        definition: "try to get someone to do something; test; invite",
        synonyms: ["entice", "attract"],
        examples: [
          "A banana split can tempt me to break my diet.",
          "The sight of money tempted him to steal.",
          "She was tempted to skip class.",
        ],
        wordPr: "وسوسه کردن",
        definitionPr: "تشویق یا وسوسه کردن کسی به انجام کاری",
        synonymsPr: ["وسوسه کردن", "تشویق کردن"],
        examplesPr: [
          "یک بستنی می‌تواند من را وسوسه کند رژیمم را بشکنم.",
          "دیدن پول او را وسوسه کرد که دزدی کند.",
          "او وسوسه شد که کلاس را نرود.",
        ],
      },
      {
        id: 24,
        pronunciation: "ˈweɪdʒər",
        imageUrl: "",
        word: "wager",
        definition: "bet",
        synonyms: ["bet", "gamble"],
        examples: [
          "I lost a small wager on the game.",
          "He made a wager that his team would win.",
          "She likes to wager on horse races.",
        ],
        wordPr: "شرط بندی، شرط",
        definitionPr: "شرط یا شرط بندی کردن",
        synonymsPr: ["شرط", "شرط بندی"],
        examplesPr: [
          "من یک شرط کوچک روی بازی باختم.",
          "او شرط بست که تیمش برنده می‌شود.",
          "او دوست دارد روی مسابقات اسب‌دوانی شرط ببندد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
