export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 325,
        pronunciation: "ˈwɔːrdən",
        imageUrl: "",
        word: "warden",
        definition: "a person in charge of a prison or a protected place",
        synonyms: ["guard", "supervisor", "keeper"],
        examples: [
          "The warden ensures the prison is secure.",
          "The park warden patrols the area daily.",
          "He was appointed as the warden of the prison.",
        ],
        wordPr: "سرپرست زندان، ناظر",
        definitionPr: "شخص مسئول یک زندان یا مکان محافظت شده",
        synonymsPr: ["نگهبان", "سرپرست", "ناظر"],
        examplesPr: [
          "سرپرست زندان امنیت زندان را تضمین می‌کند.",
          "نگهبان پارک روزانه منطقه را گشت می‌زند.",
          "او به عنوان سرپرست زندان منصوب شد.",
        ],
      },
      {
        id: 326,
        pronunciation: "prəˈmoʊt",
        imageUrl: "",
        word: "promote",
        definition: "to encourage or support; to advance in position",
        synonyms: ["encourage", "advance", "boost"],
        examples: [
          "The company promotes healthy living.",
          "She was promoted to manager.",
          "They promote their products through advertising.",
        ],
        wordPr: "ترغیب کردن، ارتقاء دادن",
        definitionPr: "تشویق یا حمایت کردن؛ ارتقاء در موقعیت",
        synonymsPr: ["تشویق کردن", "ارتقاء دادن", "تقویت کردن"],
        examplesPr: [
          "شرکت زندگی سالم را ترغیب می‌کند.",
          "او به مدیر ارتقاء یافت.",
          "آن‌ها محصولات خود را از طریق تبلیغات ترویج می‌کنند.",
        ],
      },
      {
        id: 327,
        pronunciation: "ˌʌndərˈnɜːrɪʃt",
        imageUrl: "",
        word: "undernourished",
        definition: "not having enough food or nutrients",
        synonyms: ["malnourished", "starved", "underfed"],
        examples: [
          "Many children are undernourished in poor countries.",
          "The patient was undernourished and weak.",
          "Undernourished animals need extra care.",
        ],
        wordPr: "کم‌تغذیه",
        definitionPr: "نداشتن غذای کافی یا مواد مغذی لازم",
        synonymsPr: ["کم‌تغذیه", "گرسنگی کشیده", "کم خوراک"],
        examplesPr: [
          "بسیاری از کودکان در کشورهای فقیر کم‌تغذیه هستند.",
          "بیمار کم‌تغذیه و ضعیف بود.",
          "حیوانات کم‌تغذیه نیاز به مراقبت بیشتری دارند.",
        ],
      },
      {
        id: 328,
        pronunciation: "ˈɪləstreɪt",
        imageUrl: "",
        word: "illustrate",
        definition: "to explain or decorate with pictures",
        synonyms: ["demonstrate", "show", "depict"],
        examples: [
          "The book is illustrated with beautiful pictures.",
          "He used examples to illustrate his point.",
          "The teacher illustrated the concept clearly.",
        ],
        wordPr: "توضیح دادن، تصویرگری کردن",
        definitionPr: "توضیح دادن یا تزئین با تصاویر",
        synonymsPr: ["نشان دادن", "توضیح دادن", "تصویر کردن"],
        examplesPr: [
          "کتاب با تصاویر زیبایی تصویرگری شده است.",
          "او برای توضیح نکته خود از مثال‌ها استفاده کرد.",
          "معلم مفهوم را به وضوح توضیح داد.",
        ],
      },
      {
        id: 329,
        pronunciation: "dɪsˈkloʊz",
        imageUrl: "",
        word: "disclose",
        definition: "to reveal or make known",
        synonyms: ["reveal", "divulge", "uncover"],
        examples: [
          "The company disclosed its profits.",
          "She refused to disclose the secret.",
          "The report discloses new information.",
        ],
        wordPr: "آشکار کردن، فاش کردن",
        definitionPr: "افشا کردن یا معلوم ساختن",
        synonymsPr: ["فاش کردن", "آشکار کردن", "بازگو کردن"],
        examplesPr: [
          "شرکت سودهای خود را فاش کرد.",
          "او از افشای راز خودداری کرد.",
          "گزارش اطلاعات جدیدی را آشکار می‌کند.",
        ],
      },
      {
        id: 330,
        pronunciation: "ɪkˈsɛsɪv",
        imageUrl: "",
        word: "excessive",
        definition: "more than necessary or normal",
        synonyms: ["too much", "extreme", "over"],
        examples: [
          "Excessive noise disturbed the neighbors.",
          "He showed excessive confidence.",
          "Avoid excessive use of salt.",
        ],
        wordPr: "بیش از حد، افراطی",
        definitionPr: "بیش از مقدار لازم یا معمول",
        synonymsPr: ["بیش از حد", "افراطی", "زیاد"],
        examplesPr: [
          "سر و صدای بیش از حد همسایه‌ها را اذیت کرد.",
          "او اعتماد به نفس افراطی داشت.",
          "از مصرف بیش از حد نمک خودداری کنید.",
        ],
      },
      {
        id: 331,
        pronunciation: "dɪˈzæstər",
        imageUrl: "",
        word: "disaster",
        definition: "a sudden event causing great damage or loss",
        synonyms: ["catastrophe", "calamity", "tragedy"],
        examples: [
          "The earthquake was a natural disaster.",
          "The flood caused a disaster in the village.",
          "They prepared for possible disasters.",
        ],
        wordPr: "فاجعه، بلایا",
        definitionPr: "رویداد ناگهانی که خسارت یا زیان زیاد ایجاد می‌کند",
        synonymsPr: ["فاجعه", "بلایا", "حادثه"],
        examplesPr: [
          "زلزله یک فاجعه طبیعی بود.",
          "سیل بلایی برای روستا به وجود آورد.",
          "آن‌ها برای بلایای احتمالی آماده شدند.",
        ],
      },
      {
        id: 332,
        pronunciation: "ˈsɛnsər",
        imageUrl: "",
        word: "censor",
        definition: "to examine and remove unacceptable parts",
        synonyms: ["suppress", "edit", "cut"],
        examples: [
          "The government censored the movie.",
          "Books were censored during the regime.",
          "The editor censored some parts of the article.",
        ],
        wordPr: "سانسور کردن",
        definitionPr: "بررسی و حذف بخش‌های غیرقابل قبول",
        synonymsPr: ["سانسور کردن", "حذف کردن", "ویرایش کردن"],
        examplesPr: [
          "دولت فیلم را سانسور کرد.",
          "کتاب‌ها در دوران حکومت سانسور می‌شدند.",
          "ویراستار برخی قسمت‌های مقاله را سانسور کرد.",
        ],
      },
      {
        id: 333,
        pronunciation: "ˈkʌlprɪt",
        imageUrl: "",
        word: "culprit",
        definition: "a person responsible for a crime or problem",
        synonyms: ["offender", "guilty party", "wrongdoer"],
        examples: [
          "The police caught the culprit.",
          "He was the culprit behind the theft.",
          "The culprit was punished for the crime.",
        ],
        wordPr: "مجرم، مقصر",
        definitionPr: "شخص مسئول جرم یا مشکل",
        synonymsPr: ["مجرم", "مقصر", "متخلف"],
        examplesPr: [
          "پلیس مجرم را دستگیر کرد.",
          "او مقصر سرقت بود.",
          "مجرم برای جرم خود مجازات شد.",
        ],
      },
      {
        id: 334,
        pronunciation: "ˈdʒuːvənaɪl",
        imageUrl: "",
        word: "juvenile",
        definition: "relating to young people or youth",
        synonyms: ["youthful", "adolescent", "minor"],
        examples: [
          "The juvenile offender was sent to a special center.",
          "Juvenile behavior is often different from adults.",
          "He works with juvenile delinquents.",
        ],
        wordPr: "نوجوان، کودک",
        definitionPr: "مرتبط با جوانان یا نوجوانان",
        synonymsPr: ["نوجوان", "جوان", "کودک"],
        examplesPr: [
          "مجرم نوجوان به مرکز ویژه‌ای فرستاده شد.",
          "رفتار نوجوانان معمولاً متفاوت از بزرگسالان است.",
          "او با نوجوانان خلافکار کار می‌کند.",
        ],
      },
      {
        id: 335,
        pronunciation: "beɪt",
        imageUrl: "",
        word: "bait",
        definition: "something used to lure or attract",
        synonyms: ["lure", "decoy", "trap"],
        examples: [
          "They used worms as bait for fishing.",
          "The bait attracted many fish.",
          "He set bait to catch the animal.",
        ],
        wordPr: "طعمه، فریب",
        definitionPr: "چیزی که برای جذب یا فریب استفاده می‌شود",
        synonymsPr: ["طعمه", "فریب", "دام"],
        examplesPr: [
          "آن‌ها برای ماهیگیری از کرم به عنوان طعمه استفاده کردند.",
          "طعمه بسیاری از ماهی‌ها را جذب کرد.",
          "او طعمه‌ای گذاشت تا حیوان را بگیرد.",
        ],
      },
      {
        id: 336,
        pronunciation: "ɪnˈsɪst",
        imageUrl: "",
        word: "insist",
        definition: "to demand firmly or persistently",
        synonyms: ["demand", "persist", "assert"],
        examples: [
          "She insisted on paying the bill.",
          "He insisted that we should leave early.",
          "They insisted on their rights.",
        ],
        wordPr: "اصرار کردن",
        definitionPr: "با قاطعیت یا پافشاری درخواست کردن",
        synonymsPr: ["اصرار کردن", "پافشاری کردن", "تأکید کردن"],
        examplesPr: [
          "او اصرار داشت که پول را پرداخت کند.",
          "او تأکید کرد که باید زودتر برویم.",
          "آن‌ها بر حقوق خود اصرار داشتند.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
