export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 85,
        pronunciation: "/ɪɡˈzædʒəreɪt/",
        imageUrl: "",
        word: "exaggerate",
        definition:
          "to represent something as being larger, better, or worse than it really is",
        synonyms: ["overstate", "overemphasize", "magnify"],
        examples: [
          "He tends to exaggerate his accomplishments.",
          "The media exaggerated the effects of the storm.",
          "Don't exaggerate! It wasn't that bad.",
        ],
        wordPr: "اغراق کردن",
        definitionPr:
          "نمایش چیزی به صورت بزرگ‌تر، بهتر یا بدتر از آنچه واقعاً هست",
        synonymsPr: ["بزرگنمایی کردن", "غلو کردن"],
        examplesPr: [
          "او معمولاً در مورد دستاوردهایش اغراق می‌کند.",
          "رسانه‌ها اثرات طوفان را بزرگنمایی کردند.",
          "اغراق نکن! آنقدرها هم بد نبود.",
        ],
      },
      {
        id: 86,
        pronunciation: "/ˈæmətər/",
        imageUrl: "",
        word: "amateur",
        definition:
          "a person who engages in a pursuit, especially a sport, on an unpaid basis",
        synonyms: ["nonprofessional", "beginner", "novice"],
        examples: [
          "He's just an amateur photographer, but his pictures are amazing.",
          "The tournament is open to both amateurs and professionals.",
          "She started as an amateur before turning pro.",
        ],
        wordPr: "آماتور",
        definitionPr:
          "شخصی که به فعالیتی، به ویژه ورزش، به صورت غیرحرفه‌ای می‌پردازد",
        synonymsPr: ["غیرحرفه‌ای", "تازه کار"],
        examplesPr: [
          "او فقط یک عکاس آماتور است، اما عکس‌هایش فوق‌العاده است.",
          "مسابقه هم برای آماتورها و هم حرفه‌ای‌ها باز است.",
          "او قبل از حرفه‌ای شدن به عنوان آماتور شروع کرد.",
        ],
      },
      {
        id: 87,
        pronunciation: "/ˌmiːdiˈoʊkər/",
        imageUrl: "",
        word: "mediocre",
        definition: "of only moderate quality; not very good",
        synonyms: ["average", "ordinary", "unremarkable"],
        examples: [
          "The restaurant received mediocre reviews.",
          "His performance was mediocre at best.",
          "I don't want to settle for a mediocre life.",
        ],
        wordPr: "متوسط",
        definitionPr: "با کیفیت معمولی؛ خیلی خوب نیست",
        synonymsPr: ["معمولی", "پیش پا افتاده"],
        examplesPr: [
          "رستوران نقدهای متوسطی دریافت کرد.",
          "عملکردش در بهترین حالت متوسط بود.",
          "من نمی‌خواهم به یک زندگی متوسط رضایت بدهم.",
        ],
      },
      {
        id: 88,
        pronunciation: "/vəˈraɪəti/",
        imageUrl: "",
        word: "variety",
        definition: "the quality or state of being different or diverse",
        synonyms: ["diversity", "assortment", "mixture"],
        examples: [
          "The store offers a wide variety of products.",
          "We need more variety in our diet.",
          "She enjoys the variety of her job.",
        ],
        wordPr: "تنوع",
        definitionPr: "کیفیت یا حالت متفاوت یا متنوع بودن",
        synonymsPr: ["گوناگونی", "مخلوط"],
        examplesPr: [
          "فروشگاه طیف گسترده‌ای از محصولات را ارائه می‌دهد.",
          "ما به تنوع بیشتری در رژیم غذایی خود نیاز داریم.",
          "او از تنوع شغلش لذت می‌برد.",
        ],
      },
      {
        id: 89,
        pronunciation: "/ˈvælɪd/",
        imageUrl: "",
        word: "valid",
        definition:
          "having a sound basis in logic or fact; reasonable or cogent",
        synonyms: ["sound", "legitimate", "well-founded"],
        examples: [
          "You need a valid passport to travel internationally.",
          "His argument was perfectly valid.",
          "The ticket is valid for one month.",
        ],
        wordPr: "معتبر",
        definitionPr: "داشتن پایه‌ای محکم در منطق یا واقعیت؛ معقول یا مستدل",
        synonymsPr: ["قانونی", "موجه"],
        examplesPr: [
          "برای سفر به خارج از کشور به پاسپورت معتبر نیاز دارید.",
          "استدلال او کاملاً معتبر بود.",
          "بلیت به مدت یک ماه اعتبار دارد.",
        ],
      },
      {
        id: 90,
        pronunciation: "/sərˈvaɪv/",
        imageUrl: "",
        word: "survive",
        definition:
          "to continue to live or exist, especially in spite of danger or hardship",
        synonyms: ["endure", "persist", "outlast"],
        examples: [
          "Few plants can survive in the desert.",
          "He survived the accident with minor injuries.",
          "The company is struggling to survive the economic crisis.",
        ],
        wordPr: "زنده ماندن",
        definitionPr: "ادامه زندگی یا وجود داشتن، به ویژه علیرغم خطر یا سختی",
        synonymsPr: ["تحمل کردن", "پایدار ماندن"],
        examplesPr: [
          "تعداد کمی گیاه می‌توانند در بیابان زنده بمانند.",
          "او با جراحات جزئی از سانحه جان سالم به در برد.",
          "شرکت برای زنده ماندن در بحران اقتصادی تلاش می‌کند.",
        ],
      },
      {
        id: 91,
        pronunciation: "/wɪrd/",
        imageUrl: "",
        word: "weird",
        definition: "suggesting something supernatural; uncanny",
        synonyms: ["strange", "odd", "bizarre"],
        examples: [
          "She has a weird habit of talking to herself.",
          "I had a weird dream last night.",
          "That's a weird coincidence.",
        ],
        wordPr: "عجیب",
        definitionPr: "حاکی از چیزی ماوراءطبیعی؛ ناشناخته",
        synonymsPr: ["غریب", "نامتعارف"],
        examplesPr: [
          "او عادت عجیبی در صحبت کردن با خودش دارد.",
          "دیشب خواب عجیبی دیدم.",
          "این یک تصادف عجیب است.",
        ],
      },
      {
        id: 92,
        pronunciation: "/ˈprɑːmɪnənt/",
        imageUrl: "",
        word: "prominent",
        definition: "important; famous",
        synonyms: ["distinguished", "notable", "eminent"],
        examples: [
          "He plays a prominent role in the company.",
          "The house was in a prominent position on the hill.",
          "She comes from a prominent family.",
        ],
        wordPr: "برجسته",
        definitionPr: "مهم؛ مشهور",
        synonymsPr: ["سرشناس", "معروف"],
        examplesPr: [
          "او نقش برجسته‌ای در شرکت دارد.",
          "خانه در موقعیت برجسته‌ای روی تپه قرار داشت.",
          "او از یک خانواده سرشناس می‌آید.",
        ],
      },
      {
        id: 93,
        pronunciation: "/səˈkjʊrəti/",
        imageUrl: "",
        word: "security",
        definition: "the state of being free from danger or threat",
        synonyms: ["safety", "protection", "defense"],
        examples: [
          "Airport security has been tightened.",
          "He works in computer security.",
          "The money is kept in a security box.",
        ],
        wordPr: "امنیت",
        definitionPr: "حالت دور بودن از خطر یا تهدید",
        synonymsPr: ["ایمنی", "حفاظت"],
        examplesPr: [
          "امنیت فرودگاه افزایش یافته است.",
          "او در زمینه امنیت کامپیوتر کار می‌کند.",
          "پول در یک جعبه امنیتی نگهداری می‌شود.",
        ],
      },
      {
        id: 94,
        pronunciation: "/ˈbʌlki/",
        imageUrl: "",
        word: "bulky",
        definition: "taking up much space; large and unwieldy",
        synonyms: ["large", "heavy", "cumbersome"],
        examples: [
          "The package was too bulky to carry.",
          "He wore a bulky sweater.",
          "Bulky furniture can make a room look smaller.",
        ],
        wordPr: "حجیم",
        definitionPr: "فضای زیادی اشغال کردن؛ بزرگ و دست و پا گیر",
        synonymsPr: ["بزرگ", "سنگین"],
        examplesPr: [
          "بسته برای حمل کردن خیلی حجیم بود.",
          "او یک پلیور حجیم پوشیده بود.",
          "مبلمان حجیم می‌تواند باعث شود اتاق کوچک‌تر به نظر برسد.",
        ],
      },
      {
        id: 95,
        pronunciation: "/rɪˈlʌktənt/",
        imageUrl: "",
        word: "reluctant",
        definition: "unwilling and hesitant; disinclined",
        synonyms: ["unwilling", "hesitant", "averse"],
        examples: [
          "She was reluctant to admit her mistake.",
          "He gave a reluctant promise.",
          "They were reluctant participants in the study.",
        ],
        wordPr: "بی‌میل",
        definitionPr: "ناخواسته و مردد؛ بی‌تمایل",
        synonymsPr: ["متردد", "سرباززن"],
        examplesPr: [
          "او به اقرار اشتباهش بی‌میل بود.",
          "او یک قول بی‌میل داد.",
          "آن‌ها شرکت‌کنندگان بی‌میل در مطالعه بودند.",
        ],
      },
      {
        id: 96,
        pronunciation: "/ˈɑːbviəs/",
        imageUrl: "",
        word: "obvious",
        definition:
          "easily perceived or understood; clear, self-evident, or apparent",
        synonyms: ["clear", "evident", "plain"],
        examples: [
          "It's obvious that she's unhappy.",
          "The solution was obvious to everyone.",
          "He made the obvious choice.",
        ],
        wordPr: "آشکار",
        definitionPr: "به راحتی درک یا فهمیده شده؛ واضح، بدیهی یا آشکار",
        synonymsPr: ["واضح", "مشهود"],
        examplesPr: [
          "واضح است که او ناراضی است.",
          "راه‌حل برای همه آشکار بود.",
          "او انتخاب واضحی انجام داد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
