export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 181,
        pronunciation: "/ˈslɛndər/",
        imageUrl: "",
        word: "slender",
        definition: "gracefully thin; small in amount or size",
        synonyms: ["slim", "lean", "slight"],
        examples: [
          "She had a slender figure.",
          "The chances of success are slender.",
          "He supported himself on a slender cane.",
        ],
        wordPr: "لاغر",
        definitionPr: "به زیبایی باریک؛ کم در مقدار یا اندازه",
        synonymsPr: ["نازک", "کم"],
        examplesPr: [
          "او اندامی لاغر داشت.",
          "شانس موفقیت کم است.",
          "او خود را با یک چوب باریک حمایت کرد.",
        ],
      },
      {
        id: 182,
        pronunciation: "/sərˈpæs/",
        imageUrl: "",
        word: "surpass",
        definition: "to exceed or go beyond in degree, amount, or quality",
        synonyms: ["exceed", "outdo", "outstrip"],
        examples: [
          "Her performance surpassed all expectations.",
          "The new model surpasses the old one in every way.",
          "He surpassed his previous record.",
        ],
        wordPr: "پیشی گرفتن",
        definitionPr: "فراتر رفتن یا عبور کردن در درجه، مقدار یا کیفیت",
        synonymsPr: ["سبقت گرفتن", "فراتر رفتن"],
        examplesPr: [
          "عملکرد او از تمام انتظارات فراتر رفت.",
          "مدل جدید از هر لحاظ از مدل قدیمی بهتر است.",
          "او از رکورد قبلی خود پیشی گرفت.",
        ],
      },
      {
        id: 183,
        pronunciation: "/væst/",
        imageUrl: "",
        word: "vast",
        definition: "of very great extent or quantity; immense",
        synonyms: ["huge", "enormous", "immense"],
        examples: [
          "The Sahara is a vast desert.",
          "There's a vast difference between them.",
          "The project requires vast amounts of money.",
        ],
        wordPr: "وسیع",
        definitionPr: "با وسعت یا مقدار بسیار زیاد؛ عظیم",
        synonymsPr: ["بسیار بزرگ", "گسترده"],
        examplesPr: [
          "صحرای صحرا یک بیابان وسیع است.",
          "تفاوت عظیمی بین آنها وجود دارد.",
          "این پروژه به مقادیر زیادی پول نیاز دارد.",
        ],
      },
      {
        id: 184,
        pronunciation: "/daʊt/",
        imageUrl: "",
        word: "doubt",
        definition: "a feeling of uncertainty or lack of conviction",
        synonyms: ["uncertainty", "skepticism", "hesitation"],
        examples: [
          "I have serious doubts about his honesty.",
          "There's no doubt that she's qualified.",
          "He did it without a shadow of doubt.",
        ],
        wordPr: "شک",
        definitionPr: "احساس عدم اطمینان یا عدم اعتقاد",
        synonymsPr: ["تردید", "بی‌اعتمادی"],
        examplesPr: [
          "من شک جدی در مورد صداقت او دارم.",
          "هیچ شکی نیست که او واجد شرایط است.",
          "او این کار را بدون ذره‌ای شک انجام داد.",
        ],
      },
      {
        id: 185,
        pronunciation: "/kəˈpæsəti/",
        imageUrl: "",
        word: "capacity",
        definition: "the maximum amount that something can contain",
        synonyms: ["volume", "size", "capability"],
        examples: [
          "The stadium has a capacity of 50,000.",
          "He was working to his full capacity.",
          "This tank has a large water capacity.",
        ],
        wordPr: "ظرفیت",
        definitionPr: "حداکثر مقداری که چیزی می‌تواند در خود جای دهد",
        synonymsPr: ["گنجایش", "توانایی"],
        examplesPr: [
          "این استادیوم ظرفیت 50000 نفر را دارد.",
          "او با تمام ظرفیت خود کار می‌کرد.",
          "این مخزن ظرفیت آب زیادی دارد.",
        ],
      },
      {
        id: 186,
        pronunciation: "/ˈpɛnɪtreɪt/",
        imageUrl: "",
        word: "penetrate",
        definition: "to force a way into or through something",
        synonyms: ["pierce", "enter", "perforate"],
        examples: [
          "The bullet penetrated the wall.",
          "The cold penetrated my bones.",
          "They failed to penetrate the enemy's defenses.",
        ],
        wordPr: "نفوذ کردن",
        definitionPr: "راهی را به زور به درون یا از میان چیزی باز کردن",
        synonymsPr: ["سوراخ کردن", "ورود کردن"],
        examplesPr: [
          "گلوله به دیوار نفوذ کرد.",
          "سرما تا استخوان‌هایم نفوذ کرد.",
          "آنها نتوانستند به دفاع دشمن نفوذ کنند.",
        ],
      },
      {
        id: 187,
        pronunciation: "/pɪrs/",
        imageUrl: "",
        word: "pierce",
        definition:
          "to make a hole in or through something with a sharp object",
        synonyms: ["puncture", "stab", "perforate"],
        examples: [
          "She had her ears pierced.",
          "The needle pierced his skin.",
          "A scream pierced the silence.",
        ],
        wordPr: "سوراخ کردن",
        definitionPr: "با یک شی تیز سوراخی در چیزی ایجاد کردن",
        synonymsPr: ["سوزن زدن", "فرورفتن"],
        examplesPr: [
          "او گوش‌هایش را سوراخ کرد.",
          "سوزن به پوستش فرو رفت.",
          "جیغی سکوت را شکست.",
        ],
      },
      {
        id: 188,
        pronunciation: "/ˈækjərət/",
        imageUrl: "",
        word: "accurate",
        definition: "correct in all details; exact",
        synonyms: ["precise", "exact", "correct"],
        examples: [
          "The measurements need to be accurate.",
          "His description was accurate in every detail.",
          "This watch keeps accurate time.",
        ],
        wordPr: "دقیق",
        definitionPr: "درست در تمام جزئیات؛ دقیق",
        synonymsPr: ["صحیح", "درست"],
        examplesPr: [
          "اندازه‌گیری‌ها باید دقیق باشد.",
          "توضیحات او در هر جزئی دقیق بود.",
          "این ساعت زمان دقیق را نشان می‌دهد.",
        ],
      },
      {
        id: 189,
        pronunciation: "/ˈmaɪkrəskoʊp/",
        imageUrl: "",
        word: "microscope",
        definition: "an optical instrument used for viewing very small objects",
        synonyms: ["magnifier", "lens", "scope"],
        examples: [
          "We examined the cells under a microscope.",
          "The scientist adjusted the microscope.",
          "Microscope technology has advanced greatly.",
        ],
        wordPr: "میکروسکوپ",
        definitionPr:
          "ابزار نوری که برای مشاهده اشیاء بسیار کوچک استفاده می‌شود",
        synonymsPr: ["ذره‌بین", "عدسی"],
        examplesPr: [
          "ما سلول‌ها را زیر میکروسکوپ بررسی کردیم.",
          "دانشمند میکروسکوپ را تنظیم کرد.",
          "فناوری میکروسکوپ بسیار پیشرفت کرده است.",
        ],
      },
      {
        id: 190,
        pronunciation: "/ˈɡreɪtfəl/",
        imageUrl: "",
        word: "grateful",
        definition:
          "feeling or showing an appreciation for something done or received",
        synonyms: ["thankful", "appreciative", "obliged"],
        examples: [
          "I'm grateful for your help.",
          "She gave him a grateful smile.",
          "We're grateful to be alive.",
        ],
        wordPr: "سپاسگزار",
        definitionPr:
          "احساس یا نشان دادن قدردانی برای چیزی که انجام شده یا دریافت شده",
        synonymsPr: ["ممنون", "قدردان"],
        examplesPr: [
          "من برای کمک شما سپاسگزارم.",
          "او به او لبخند سپاسگزاری داد.",
          "ما سپاسگزاریم که زنده هستیم.",
        ],
      },
      {
        id: 191,
        pronunciation: "/ˈkɔːʃəs/",
        imageUrl: "",
        word: "cautious",
        definition: "careful to avoid potential problems or dangers",
        synonyms: ["careful", "wary", "prudent"],
        examples: [
          "Be cautious when crossing the road.",
          "She's cautious about making new friends.",
          "The doctor was cautious in his diagnosis.",
        ],
        wordPr: "محتاط",
        definitionPr: "مراقب برای جلوگیری از مشکلات یا خطرات احتمالی",
        synonymsPr: ["هوشیار", "دوراندیش"],
        examplesPr: [
          "در هنگام عبور از جاده محتاط باشید.",
          "او در دوست یابی جدید محتاط است.",
          "پزشک در تشخیص خود محتاط بود.",
        ],
      },
      {
        id: 192,
        pronunciation: "/ˈkɑːnfɪdənt/",
        imageUrl: "",
        word: "confident",
        definition: "feeling or showing certainty about something",
        synonyms: ["assured", "self-confident", "positive"],
        examples: [
          "She sounded confident during her presentation.",
          "I'm confident that we'll succeed.",
          "He gave a confident performance.",
        ],
        wordPr: "مطمئن",
        definitionPr: "احساس یا نشان دادن اطمینان در مورد چیزی",
        synonymsPr: ["بااعتمادبه‌نفس", "قطعی"],
        examplesPr: [
          "او در طول ارائه خود مطمئن به نظر می‌رسید.",
          "من مطمئنم که موفق خواهیم شد.",
          "او اجرایی مطمئن داشت.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
