export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 169,
        pronunciation: "/ɪkˈspænd/",
        imageUrl: "",
        word: "expand",
        definition: "to increase in size, number, or importance",
        synonyms: ["enlarge", "grow", "extend"],
        examples: [
          "The company plans to expand its operations overseas.",
          "Metals expand when heated.",
          "She expanded her knowledge by taking evening classes.",
        ],
        wordPr: "گسترش دادن",
        definitionPr: "افزایش در اندازه، تعداد یا اهمیت",
        synonymsPr: ["بزرگ کردن", "افزایش دادن"],
        examplesPr: [
          "شرکت قصد دارد عملیات خود را در خارج از کشور گسترش دهد.",
          "فلزات در اثر گرما منبسط می‌شوند.",
          "او دانش خود را با شرکت در کلاس‌های شبانه گسترش داد.",
        ],
      },
      {
        id: 170,
        pronunciation: "/ˈɔːltər/",
        imageUrl: "",
        word: "alter",
        definition: "to change or make different",
        synonyms: ["change", "modify", "adjust"],
        examples: [
          "We had to alter our plans due to the weather.",
          "The dress was altered to fit perfectly.",
          "Nothing can alter the fact that we were wrong.",
        ],
        wordPr: "تغییر دادن",
        definitionPr: "تغییر کردن یا متفاوت کردن",
        synonymsPr: ["اصلاح کردن", "تنظیم کردن"],
        examplesPr: [
          "ما مجبور شدیم به دلیل هوا برنامه‌هایمان را تغییر دهیم.",
          "لباس تغییر داده شد تا کاملاً اندازه شود.",
          "هیچ چیز نمی‌تواند این واقعیت را تغییر دهد که ما اشتباه کردیم.",
        ],
      },
      {
        id: 171,
        pronunciation: "/məˈtʃʊr/",
        imageUrl: "",
        word: "mature",
        definition:
          "fully developed physically; fully considered and perfected",
        synonyms: ["grown-up", "ripe", "developed"],
        examples: [
          "At 16, he was very mature for his age.",
          "The plan needs more time to mature.",
          "This cheese has a mature flavor.",
        ],
        wordPr: "بالغ",
        definitionPr:
          "از نظر فیزیکی کاملاً رشد یافته؛ کاملاً در نظر گرفته شده و کامل شده",
        synonymsPr: ["رسیده", "پخته"],
        examplesPr: [
          "در 16 سالگی، او برای سنش بسیار بالغ بود.",
          "این برنامه نیاز به زمان بیشتری برای تکامل دارد.",
          "این پنیر طعمی رسیده دارد.",
        ],
      },
      {
        id: 172,
        pronunciation: "/ˈseɪkrɪd/",
        imageUrl: "",
        word: "sacred",
        definition: "connected with God or a god; considered to be holy",
        synonyms: ["holy", "divine", "consecrated"],
        examples: [
          "The temple is a sacred place for worship.",
          "Cows are considered sacred in India.",
          "They made a sacred promise to each other.",
        ],
        wordPr: "مقدس",
        definitionPr: "متصل به خدا یا یک خدا؛ در نظر گرفته شده به عنوان مقدس",
        synonymsPr: ["الهی", "متعال"],
        examplesPr: [
          "معبد مکانی مقدس برای عبادت است.",
          "گاوها در هند مقدس محسوب می‌شوند.",
          "آنها به یکدیگر قول مقدس دادند.",
        ],
      },
      {
        id: 173,
        pronunciation: "/rɪˈvaɪz/",
        imageUrl: "",
        word: "revise",
        definition:
          "to re-examine and make alterations to (written or printed matter)",
        synonyms: ["amend", "modify", "correct"],
        examples: [
          "I need to revise my essay before submitting it.",
          "The textbook was revised for the new school year.",
          "She revised her opinion after hearing the facts.",
        ],
        wordPr: "بازبینی کردن",
        definitionPr: "بازبینی و ایجاد تغییرات در (موضوعات نوشته یا چاپ شده)",
        synonymsPr: ["اصلاح کردن", "ویرایش کردن"],
        examplesPr: [
          "من باید مقاله‌ام را قبل از ارسال بازبینی کنم.",
          "کتاب درسی برای سال تحصیلی جدید بازبینی شد.",
          "او پس از شنیدن حقایق نظر خود را اصلاح کرد.",
        ],
      },
      {
        id: 174,
        pronunciation: "/plɛdʒ/",
        imageUrl: "",
        word: "pledge",
        definition: "a solemn promise or undertaking",
        synonyms: ["promise", "vow", "commitment"],
        examples: [
          "They made a pledge to help the poor.",
          "He gave a pledge of loyalty to the king.",
          "She pledged to donate money to the charity.",
        ],
        wordPr: "قول",
        definitionPr: "یک وعده یا تعهد رسمی",
        synonymsPr: ["عهد", "تعهد"],
        examplesPr: [
          "آنها قول دادند که به فقرا کمک کنند.",
          "او تعهد وفاداری به پادشاه داد.",
          "او قول داد به خیریه پول اهدا کند.",
        ],
      },
      {
        id: 175,
        pronunciation: "/ˈkæʒuəl/",
        imageUrl: "",
        word: "casual",
        definition: "relaxed and unconcerned; not regular or permanent",
        synonyms: ["informal", "relaxed", "occasional"],
        examples: [
          "He wore casual clothes to the party.",
          "They had a casual conversation over coffee.",
          "She works as a casual employee.",
        ],
        wordPr: "غیررسمی",
        definitionPr: "آرام و بی‌خیال؛ نه منظم و نه دائمی",
        synonymsPr: ["راحت", "موقت"],
        examplesPr: [
          "او لباس غیررسمی به مهمانی پوشید.",
          "آنها یک گفتگوی غیررسمی روی قهوه داشتند.",
          "او به عنوان یک کارمند موقت کار می‌کند.",
        ],
      },
      {
        id: 176,
        pronunciation: "/pərˈsuː/",
        imageUrl: "",
        word: "pursue",
        definition: "to follow or chase (someone or something)",
        synonyms: ["chase", "follow", "seek"],
        examples: [
          "The police pursued the thief through the streets.",
          "She decided to pursue a career in medicine.",
          "The government is pursuing a new policy.",
        ],
        wordPr: "دنبال کردن",
        definitionPr: "پیروی کردن یا تعقیب کردن (کسی یا چیزی)",
        synonymsPr: ["تعقیب کردن", "جستجو کردن"],
        examplesPr: [
          "پلیس دزد را در خیابان‌ها تعقیب کرد.",
          "او تصمیم گرفت دنبال شغلی در پزشکی باشد.",
          "دولت در حال پیگیری یک سیاست جدید است.",
        ],
      },
      {
        id: 177,
        pronunciation: "/juːˈnænɪməs/",
        imageUrl: "",
        word: "unanimous",
        definition: "fully in agreement",
        synonyms: ["united", "agreed", "harmonious"],
        examples: [
          "The decision was unanimous.",
          "The jury reached a unanimous verdict.",
          "There was unanimous support for the proposal.",
        ],
        wordPr: "متفق‌الرأی",
        definitionPr: "کاملاً موافق",
        synonymsPr: ["یکدست", "هماهنگ"],
        examplesPr: [
          "تصمیم به اتفاق آرا بود.",
          "هیئت منصفه به حکمی متفق‌الرأی رسید.",
          "حمایت یکپارچه‌ای از پیشنهاد وجود داشت.",
        ],
      },
      {
        id: 178,
        pronunciation: "/ˈfɔːrtʃənət/",
        imageUrl: "",
        word: "fortunate",
        definition: "favored by or involving good luck",
        synonyms: ["lucky", "blessed", "privileged"],
        examples: [
          "We were fortunate to get tickets for the concert.",
          "She's fortunate to have such good friends.",
          "It was fortunate that no one was hurt in the accident.",
        ],
        wordPr: "خوش‌شانس",
        definitionPr: "مورد لطف یا شامل شانس خوب بودن",
        synonymsPr: ["خوشبخت", "متمول"],
        examplesPr: [
          "ما خوش‌شانس بودیم که بلیت کنسرت را گرفتیم.",
          "او خوش‌شانس است که چنین دوستان خوبی دارد.",
          "خوشبختانه هیچکس در حادثه آسیب ندید.",
        ],
      },
      {
        id: 179,
        pronunciation: "/ˌpaɪəˈnɪr/",
        imageUrl: "",
        word: "pioneer",
        definition:
          "a person who is among the first to explore or settle a new area",
        synonyms: ["innovator", "trailblazer", "forerunner"],
        examples: [
          "He was a pioneer in the field of computer science.",
          "The pioneers traveled west in covered wagons.",
          "She pioneered a new technique in surgery.",
        ],
        wordPr: "پیشگام",
        definitionPr:
          "شخصی که جزو اولین کسانی است که منطقه جدیدی را کشف یا سکونت می‌دهد",
        synonymsPr: ["نوآور", "جاده‌گشا"],
        examplesPr: [
          "او پیشگام در زمینه علوم کامپیوتر بود.",
          "پیشگامان با گاری‌های سرپوشیده به غرب سفر کردند.",
          "او یک تکنیک جدید در جراحی ابداع کرد.",
        ],
      },
      {
        id: 180,
        pronunciation: "/ˈɪnəveɪtɪv/",
        imageUrl: "",
        word: "innovative",
        definition: "featuring new methods; advanced and original",
        synonyms: ["original", "creative", "groundbreaking"],
        examples: [
          "The company is known for its innovative designs.",
          "She developed an innovative approach to teaching.",
          "This is the most innovative product we've seen in years.",
        ],
        wordPr: "نوآورانه",
        definitionPr: "شامل روش‌های جدید؛ پیشرفته و اصیل",
        synonymsPr: ["خلاقانه", "انقلابی"],
        examplesPr: [
          "این شرکت به خاطر طراحی‌های نوآورانه‌اش شناخته شده است.",
          "او یک روش نوآورانه برای تدریس توسعه داد.",
          "این نوآورانه‌ترین محصولی است که در سال‌های اخیر دیده‌ایم.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
