export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 313,
        pronunciation: "dɪˈspaɪt",
        imageUrl: "",
        word: "despite",
        definition: "without being affected by; in spite of",
        synonyms: ["although", "in spite of", "regardless of"],
        examples: [
          "Despite the rain, we went for a walk.",
          "She succeeded despite many difficulties.",
          "Despite his illness, he went to work.",
        ],
        wordPr: "علیرغم، باوجود",
        definitionPr: "بدون تأثیر گرفتن از چیزی؛ باوجود",
        synonymsPr: ["علیرغم", "باوجود", "صرف‌نظر از"],
        examplesPr: [
          "علیرغم باران، به پیاده‌روی رفتیم.",
          "او باوجود مشکلات زیاد موفق شد.",
          "علیرغم بیماری، به سر کار رفت.",
        ],
      },
      {
        id: 314,
        pronunciation: "dɪsˈrʌpt",
        imageUrl: "",
        word: "disrupt",
        definition: "to interrupt or disturb",
        synonyms: ["disturb", "interrupt", "break up"],
        examples: [
          "The protest disrupted traffic.",
          "His loud noise disrupted the meeting.",
          "Power failure disrupted the work.",
        ],
        wordPr: "مختل کردن، بهم زدن",
        definitionPr: "قطع کردن یا مختل کردن روند چیزی",
        synonymsPr: ["مختل کردن", "قطع کردن", "بهم زدن"],
        examplesPr: [
          "تظاهرات ترافیک را مختل کرد.",
          "صدای بلند او جلسه را بهم زد.",
          "قطع برق کار را مختل کرد.",
        ],
      },
      {
        id: 315,
        pronunciation: "ræʃ",
        imageUrl: "",
        word: "rash",
        definition: "acting without careful thought; a skin eruption",
        synonyms: ["reckless", "hasty", "eruption"],
        examples: [
          "It was a rash decision to quit his job.",
          "He made a rash move that caused problems.",
          "She developed a rash after eating seafood.",
        ],
        wordPr: "نسنجیده، جوش پوستی",
        definitionPr: "عمل کردن بدون فکر دقیق؛ جوش یا بثورات پوستی",
        synonymsPr: ["نسنجیده", "بی‌پروا", "بثورات پوستی"],
        examplesPr: [
          "تصمیم او برای ترک کار نسنجیده بود.",
          "او حرکت نسنجیده‌ای انجام داد که مشکل ایجاد کرد.",
          "بعد از خوردن غذاهای دریایی دچار جوش شد.",
        ],
      },
      {
        id: 316,
        pronunciation: "ˈræpɪd",
        imageUrl: "",
        word: "rapid",
        definition: "happening quickly or in a short time",
        synonyms: ["fast", "quick", "swift"],
        examples: [
          "The rapid growth of the company surprised everyone.",
          "He made rapid progress in his studies.",
          "The river has a rapid current.",
        ],
        wordPr: "سریع",
        definitionPr: "اتفاق افتادن با سرعت یا در زمان کوتاه",
        synonymsPr: ["سریع", "چابک", "تند"],
        examplesPr: [
          "رشد سریع شرکت همه را شگفت‌زده کرد.",
          "او پیشرفت سریعی در درس‌هایش داشت.",
          "رودخانه جریان سریعی دارد.",
        ],
      },
      {
        id: 317,
        pronunciation: "ɪɡˈzɔːst",
        imageUrl: "",
        word: "exhaust",
        definition: "to tire out completely; to use up resources",
        synonyms: ["tire", "drain", "deplete"],
        examples: [
          "The long hike exhausted the children.",
          "He exhausted all his options.",
          "The workers were exhausted after the hard labor.",
        ],
        wordPr: "خسته کردن، تمام کردن",
        definitionPr: "کاملاً خسته کردن؛ استفاده کامل از منابع",
        synonymsPr: ["خسته کردن", "تمام کردن", "مصرف کردن"],
        examplesPr: [
          "پیاده‌روی طولانی کودکان را خسته کرد.",
          "او تمام گزینه‌های خود را امتحان کرد.",
          "کارگران پس از کار سخت خسته بودند.",
        ],
      },
      {
        id: 318,
        pronunciation: "səˈvɛrɪti",
        imageUrl: "",
        word: "severity",
        definition: "the condition of being very bad or serious",
        synonyms: ["seriousness", "intensity", "harshness"],
        examples: [
          "The severity of the storm caused many problems.",
          "Doctors were concerned about the severity of his illness.",
          "The severity of the punishment was questioned.",
        ],
        wordPr: "شدت، سختی",
        definitionPr: "شرایط بد یا جدی بودن",
        synonymsPr: ["شدت", "سختی", "جدیت"],
        examplesPr: [
          "شدت طوفان مشکلات زیادی ایجاد کرد.",
          "پزشکان نگران شدت بیماری او بودند.",
          "شدت مجازات مورد سوال قرار گرفت.",
        ],
      },
      {
        id: 319,
        pronunciation: "ˈfiːbəl",
        imageUrl: "",
        word: "feeble",
        definition: "weak or lacking strength",
        synonyms: ["weak", "frail", "delicate"],
        examples: [
          "The old man’s voice was feeble.",
          "She felt feeble after the illness.",
          "A feeble attempt to fix the problem.",
        ],
        wordPr: "ضعیف، ناتوان",
        definitionPr: "ضعیف یا فاقد قدرت",
        synonymsPr: ["ضعیف", "ناتوان", "سست"],
        examplesPr: [
          "صدای پیرمرد ضعیف بود.",
          "او بعد از بیماری احساس ضعف می‌کرد.",
          "تلاش ضعیفی برای حل مشکل بود.",
        ],
      },
      {
        id: 320,
        pronunciation: "juːˈnaɪt",
        imageUrl: "",
        word: "unite",
        definition: "to come or bring together for a common purpose",
        synonyms: ["join", "combine", "merge"],
        examples: [
          "The teams united to achieve their goal.",
          "The country was united after the war.",
          "People united for a common cause.",
        ],
        wordPr: "متحد شدن، متحد کردن",
        definitionPr: "با هم آمدن یا گرد هم آوردن برای هدف مشترک",
        synonymsPr: ["متحد شدن", "پیوستن", "ادغام"],
        examplesPr: [
          "تیم‌ها برای رسیدن به هدف خود متحد شدند.",
          "کشور پس از جنگ متحد شد.",
          "مردم برای هدفی مشترک متحد شدند.",
        ],
      },
      {
        id: 321,
        pronunciation: "siːs",
        imageUrl: "",
        word: "cease",
        definition: "to stop or come to an end",
        synonyms: ["stop", "end", "halt"],
        examples: [
          "The fighting ceased after the peace agreement.",
          "The rain ceased at noon.",
          "They decided to cease the operation.",
        ],
        wordPr: "متوقف شدن، پایان یافتن",
        definitionPr: "متوقف شدن یا به پایان رسیدن",
        synonymsPr: ["متوقف شدن", "پایان یافتن", "قطع کردن"],
        examplesPr: [
          "جنگ پس از توافق صلح متوقف شد.",
          "باران ظهر قطع شد.",
          "آن‌ها تصمیم گرفتند عملیات را متوقف کنند.",
        ],
      },
      {
        id: 322,
        pronunciation: "ˈθrɪfti",
        imageUrl: "",
        word: "thrifty",
        definition: "using money and resources carefully and not wastefully",
        synonyms: ["frugal", "economical", "saving"],
        examples: [
          "She is very thrifty with her spending.",
          "Thrifty people save money for the future.",
          "Being thrifty helps you manage your budget.",
        ],
        wordPr: "صرفه‌جو، مقتصد",
        definitionPr: "استفاده دقیق و بدون هدر دادن منابع و پول",
        synonymsPr: ["مقتصد", "صرفه‌جو", "اقتصادی"],
        examplesPr: [
          "او در خرج کردن پول بسیار صرفه‌جو است.",
          "افراد صرفه‌جو پول برای آینده پس‌انداز می‌کنند.",
          "صرفه‌جویی به مدیریت بودجه کمک می‌کند.",
        ],
      },
      {
        id: 323,
        pronunciation: "ˈmaɪzərli",
        imageUrl: "",
        word: "miserly",
        definition: "unwilling to spend money; very stingy",
        synonyms: ["stingy", "cheap", "parsimonious"],
        examples: [
          "He is known for his miserly ways.",
          "A miserly person never shares.",
          "She lived a miserly life.",
        ],
        wordPr: "خسیس، کم‌خرج",
        definitionPr: "ناراضی از خرج کردن پول؛ بسیار خسیس",
        synonymsPr: ["خسیس", "کم‌خرج", "بخل‌ورز"],
        examplesPr: [
          "او به خاطر خسیس بودن شناخته شده است.",
          "یک فرد خسیس هیچ‌وقت سهیم نمی‌شود.",
          "او زندگی خسیسی داشت.",
        ],
      },
      {
        id: 324,
        pronunciation: "ˈmɑːnərk",
        imageUrl: "",
        word: "monarch",
        definition: "a king or queen who rules a country",
        synonyms: ["king", "queen", "sovereign"],
        examples: [
          "The monarch ruled the country wisely.",
          "Queen Elizabeth was a famous monarch.",
          "The monarch’s decisions affected the whole nation.",
        ],
        wordPr: "پادشاه، پادشاهی",
        definitionPr: "شاه یا ملکه‌ای که بر کشور حکومت می‌کند",
        synonymsPr: ["پادشاه", "ملکه", "حاکم"],
        examplesPr: [
          "پادشاه کشور را با حکمت حکومت کرد.",
          "ملکه الیزابت یک پادشاه مشهور بود.",
          "تصمیمات پادشاه بر کل ملت تأثیر داشت.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
