export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 420,
        pronunciation: "ˈprɑːmpt",
        imageUrl: "",
        word: "prompt",
        definition: "to cause someone to take action quickly",
        synonyms: ["encourage", "cause", "motivate"],
        examples: [
          "His speech prompted a standing ovation.",
          "The accident prompted an investigation.",
          "Please prompt me if I forget.",
        ],
        wordPr: "باعث شدن، تحریک کردن",
        definitionPr: "وارد کردن یا تشویق کسی به عمل سریع",
        synonymsPr: ["تشویق کردن", "باعث شدن", "تحریک کردن"],
        examplesPr: [
          "سخنرانی او باعث تشویق ایستاده شد.",
          "تصادف باعث شروع تحقیقات شد.",
          "لطفا اگر فراموش کردم، یادآوری کن.",
        ],
      },
      {
        id: 421,
        pronunciation: "ˈheɪsti",
        imageUrl: "",
        word: "hasty",
        definition: "done quickly without careful thought",
        synonyms: ["rash", "quick", "hurried"],
        examples: [
          "She made a hasty decision and regretted it.",
          "Don't be hasty; think before you act.",
          "His hasty remarks offended some people.",
        ],
        wordPr: "شتابزده، عجولانه",
        definitionPr: "انجام شده به سرعت بدون فکر دقیق",
        synonymsPr: ["عجولانه", "شتابزده", "بی‌دقت"],
        examplesPr: [
          "او تصمیم شتابزده گرفت و پشیمان شد.",
          "عجول نباش؛ قبل از عمل فکر کن.",
          "اظهارات عجولانه‌اش باعث ناراحتی برخی شد.",
        ],
      },
      {
        id: 422,
        pronunciation: "skɔːrtʃ",
        imageUrl: "",
        word: "scorch",
        definition: "to burn the surface of something slightly",
        synonyms: ["burn", "sing", "char"],
        examples: [
          "The sun scorched the dry grass.",
          "Be careful not to scorch the toast.",
          "The fire scorched the edges of the paper.",
        ],
        wordPr: "سوزاندن سطحی",
        definitionPr: "کمی سوزاندن سطح چیزی",
        synonymsPr: ["سوزاندن", "کمی سوختن", "خشک کردن"],
        examplesPr: [
          "خورشید علف‌های خشک را سوزاند.",
          "مراقب باش نان تست را نسوزانی.",
          "آتش لبه‌های کاغذ را سوزاند.",
        ],
      },
      {
        id: 423,
        pronunciation: "ˈtɛmpɪst",
        imageUrl: "",
        word: "tempest",
        definition: "a violent storm with strong winds and rain",
        synonyms: ["storm", "gale", "hurricane"],
        examples: [
          "The tempest damaged many houses.",
          "Sailors were afraid of the coming tempest.",
          "After the tempest, the sea was calm.",
        ],
        wordPr: "طوفان شدید",
        definitionPr: "طوفان شدید با باد و باران قوی",
        synonymsPr: ["طوفان", "باد شدید", "توفان"],
        examplesPr: [
          "طوفان بسیاری از خانه‌ها را خراب کرد.",
          "دریانوردان از طوفان در راه ترسیده بودند.",
          "بعد از طوفان، دریا آرام بود.",
        ],
      },
      {
        id: 424,
        pronunciation: "suːð",
        imageUrl: "",
        word: "soothe",
        definition: "to make calm or relieve pain",
        synonyms: ["calm", "comfort", "relieve"],
        examples: [
          "Music can soothe a troubled mind.",
          "She soothed the crying baby.",
          "The medicine helped soothe his pain.",
        ],
        wordPr: "آرام کردن، تسکین دادن",
        definitionPr: "آرام کردن یا کاهش درد",
        synonymsPr: ["آرام کردن", "تسکین دادن", "راحت کردن"],
        examplesPr: [
          "موسیقی می‌تواند ذهن مضطرب را آرام کند.",
          "او کودک گریان را آرام کرد.",
          "دارو به تسکین درد او کمک کرد.",
        ],
      },
      {
        id: 425,
        pronunciation: "ˌsɪmpəˈθɛtɪk",
        imageUrl: "",
        word: "sympathetic",
        definition: "showing understanding and care for someone’s feelings",
        synonyms: ["compassionate", "caring", "understanding"],
        examples: [
          "She was sympathetic to his problems.",
          "A sympathetic listener can help a lot.",
          "He gave me a sympathetic smile.",
        ],
        wordPr: "همدرد، دلسوز",
        definitionPr: "نشان دادن درک و مراقبت از احساسات دیگران",
        synonymsPr: ["دلسوز", "همدل", "مهربان"],
        examplesPr: [
          "او نسبت به مشکلات او دلسوز بود.",
          "یک شنونده همدل می‌تواند خیلی کمک کند.",
          "او لبخند همدلانه‌ای به من زد.",
        ],
      },
      {
        id: 426,
        pronunciation: "rɪˈdiːm",
        imageUrl: "",
        word: "redeem",
        definition: "to make up for a mistake or bad situation",
        synonyms: ["compensate", "make amends", "recover"],
        examples: [
          "He tried to redeem himself after the failure.",
          "You can redeem your coupon at the store.",
          "The company redeemed its reputation.",
        ],
        wordPr: "جبران کردن، بازخرید کردن",
        definitionPr: "جبران اشتباه یا وضعیت بد",
        synonymsPr: ["جبران کردن", "اصلاح کردن", "بازخرید کردن"],
        examplesPr: [
          "او پس از شکست سعی کرد خود را جبران کند.",
          "می‌توانی کوپن خود را در فروشگاه بازخرید کنی.",
          "شرکت اعتبار خود را بازگرداند.",
        ],
      },
      {
        id: 427,
        pronunciation: "rɪˈzjuːm",
        imageUrl: "",
        word: "resume",
        definition: "to start again after a pause",
        synonyms: ["restart", "continue", "proceed"],
        examples: [
          "The meeting will resume after lunch.",
          "She resumed her studies after a break.",
          "They resumed work on the project.",
        ],
        wordPr: "از سر گرفتن، ادامه دادن",
        definitionPr: "شروع دوباره بعد از توقف",
        synonymsPr: ["ادامه دادن", "از سر گرفتن", "دوباره شروع کردن"],
        examplesPr: [
          "جلسه بعد از ناهار از سر گرفته می‌شود.",
          "او پس از یک وقفه تحصیلاتش را ادامه داد.",
          "آن‌ها کار روی پروژه را از سر گرفتند.",
        ],
      },
      {
        id: 428,
        pronunciation: "ˈhɑːrməni",
        imageUrl: "",
        word: "harmony",
        definition: "peaceful and friendly relations",
        synonyms: ["peace", "agreement", "concord"],
        examples: [
          "They lived in harmony for many years.",
          "The choir sang in perfect harmony.",
          "Harmony between nations is important.",
        ],
        wordPr: "هماهنگی، هارمونی",
        definitionPr: "روابط صلح‌آمیز و دوستانه",
        synonymsPr: ["صلح", "توافق", "هماهنگی"],
        examplesPr: [
          "آن‌ها سال‌ها در هماهنگی زندگی کردند.",
          "کُر با هارمونی کامل آواز خواند.",
          "هماهنگی بین کشورها مهم است.",
        ],
      },
      {
        id: 429,
        pronunciation: "rɪˈfreɪn",
        imageUrl: "",
        word: "refrain",
        definition: "to avoid doing something",
        synonyms: ["abstain", "avoid", "hold back"],
        examples: [
          "Please refrain from smoking here.",
          "He refrained from commenting on the issue.",
          "She refrained from eating sweets.",
        ],
        wordPr: "خودداری کردن، پرهیز کردن",
        definitionPr: "از انجام کاری خودداری کردن",
        synonymsPr: ["پرهیز کردن", "دوری کردن", "خودداری کردن"],
        examplesPr: [
          "لطفا اینجا سیگار نکشید.",
          "او از اظهار نظر درباره موضوع خودداری کرد.",
          "او از خوردن شیرینی خودداری کرد.",
        ],
      },
      {
        id: 430,
        pronunciation: "ɪˈliːgəl",
        imageUrl: "",
        word: "illegal",
        definition: "not allowed by law",
        synonyms: ["unlawful", "forbidden", "illicit"],
        examples: [
          "It is illegal to drive without a license.",
          "The police caught the illegal trader.",
          "Selling drugs is illegal.",
        ],
        wordPr: "غیرقانونی",
        definitionPr: "مجاز نبودن توسط قانون",
        synonymsPr: ["غیرقانونی", "ممنوع", "ناجوانمردانه"],
        examplesPr: [
          "رانندگی بدون گواهینامه غیرقانونی است.",
          "پلیس تاجر غیرقانونی را گرفت.",
          "فروش مواد مخدر غیرقانونی است.",
        ],
      },
      {
        id: 431,
        pronunciation: "nɑːrˈkɑːtɪk",
        imageUrl: "",
        word: "narcotic",
        definition:
          "a drug that affects mood or behavior and can cause addiction",
        synonyms: ["drug", "opioid", "sedative"],
        examples: [
          "The patient was given a narcotic for pain relief.",
          "Narcotics can be very addictive.",
          "The police seized illegal narcotics.",
        ],
        wordPr: "ماده مخدر",
        definitionPr:
          "دارویی که حالت یا رفتار را تغییر می‌دهد و می‌تواند اعتیادآور باشد",
        synonymsPr: ["ماده مخدر", "داروی آرام‌بخش", "مواد اعتیادآور"],
        examplesPr: [
          "برای تسکین درد به بیمار ماده مخدر دادند.",
          "مواد مخدر می‌توانند بسیار اعتیادآور باشند.",
          "پلیس مواد مخدر غیرقانونی را ضبط کرد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
