export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 456,
        pronunciation: "ʌnˈɜːrθ",
        imageUrl: "",
        word: "unearth",
        definition: "to discover something hidden, lost, or kept secret",
        synonyms: ["discover", "expose", "reveal"],
        examples: [
          "They unearthed ancient artifacts during the excavation.",
          "The journalist unearthed a political scandal.",
          "New evidence was unearthed by the police.",
        ],
        wordPr: "کشف کردن، از زیر خاک درآوردن",
        definitionPr: "کشف کردن چیزی پنهان، گمشده یا مخفی‌شده",
        synonymsPr: ["کشف کردن", "آشکار کردن", "یافتن"],
        examplesPr: [
          "آن‌ها در حفاری، آثار باستانی را کشف کردند.",
          "خبرنگار یک رسوایی سیاسی را افشا کرد.",
          "شواهد جدیدی توسط پلیس کشف شد.",
        ],
      },
      {
        id: 457,
        pronunciation: "dɪˈpɑːrt",
        imageUrl: "",
        word: "depart",
        definition: "to leave, especially to start a journey",
        synonyms: ["leave", "exit", "go away"],
        examples: [
          "The train departs at 9 a.m.",
          "She departed from New York yesterday.",
          "They departed for Paris in the morning.",
        ],
        wordPr: "ترک کردن، عزیمت کردن",
        definitionPr: "ترک کردن مکانی، به ویژه برای شروع سفر",
        synonymsPr: ["عزیمت کردن", "رفتن", "خروج کردن"],
        examplesPr: [
          "قطار ساعت ۹ صبح حرکت می‌کند.",
          "او دیروز نیویورک را ترک کرد.",
          "آن‌ها صبح به سوی پاریس حرکت کردند.",
        ],
      },
      {
        id: 458,
        pronunciation: "ˌkəʊɪnˈsaɪd",
        imageUrl: "",
        word: "coincide",
        definition: "to happen at the same time",
        synonyms: ["occur simultaneously", "match", "agree"],
        examples: [
          "My birthday coincides with the holiday.",
          "Their arrivals coincided.",
          "The meetings coincided perfectly.",
        ],
        wordPr: "همزمان بودن، مصادف شدن",
        definitionPr: "اتفاق افتادن همزمان دو یا چند چیز",
        synonymsPr: ["همزمان بودن", "تطابق داشتن", "منطبق شدن"],
        examplesPr: [
          "تولد من با تعطیلات مصادف شده است.",
          "ورود آن‌ها همزمان بود.",
          "جلسات به طور کامل با هم منطبق شدند.",
        ],
      },
      {
        id: 459,
        pronunciation: "ˈkænsəl",
        imageUrl: "",
        word: "cancel",
        definition: "to decide that an event will not happen",
        synonyms: ["call off", "abort", "annul"],
        examples: [
          "The flight was canceled due to weather.",
          "They canceled the meeting.",
          "He canceled his subscription.",
        ],
        wordPr: "لغو کردن",
        definitionPr: "تصمیم به برگزار نکردن یک رویداد یا پایان دادن به چیزی",
        synonymsPr: ["لغو کردن", "باطل کردن", "منصرف شدن"],
        examplesPr: [
          "پرواز به دلیل وضعیت هوا لغو شد.",
          "آن‌ها جلسه را لغو کردند.",
          "او اشتراک خود را لغو کرد.",
        ],
      },
      {
        id: 460,
        pronunciation: "ˈdɛtər",
        imageUrl: "",
        word: "debtor",
        definition: "a person or organization that owes money",
        synonyms: ["borrower", "defaulter", "obligor"],
        examples: [
          "The debtor couldn't pay his loan.",
          "Creditors are chasing the debtor.",
          "The bank gave the debtor more time.",
        ],
        wordPr: "بدهکار",
        definitionPr: "شخص یا سازمانی که پولی بدهکار است",
        synonymsPr: ["بدهکار", "وام‌گیرنده", "مدیون"],
        examplesPr: [
          "بدهکار نتوانست وام خود را پرداخت کند.",
          "طلبکاران به دنبال بدهکار هستند.",
          "بانک به بدهکار مهلت بیشتری داد.",
        ],
      },
      {
        id: 461,
        pronunciation: "ˈlɛdʒəbl",
        imageUrl: "",
        word: "legible",
        definition: "clear enough to read",
        synonyms: ["readable", "clear", "understandable"],
        examples: [
          "His handwriting is barely legible.",
          "The document was written in legible print.",
          "Make sure your answer is legible.",
        ],
        wordPr: "خوانا",
        definitionPr: "به اندازه کافی واضح برای خواندن",
        synonymsPr: ["قابل خواندن", "واضح", "روشن"],
        examplesPr: [
          "دست‌خط او به سختی خوانا است.",
          "سند با چاپ خوانا نوشته شده بود.",
          "مطمئن شو پاسخ تو خوانا باشد.",
        ],
      },
      {
        id: 462,
        pronunciation: "ˈplækɑːrd",
        imageUrl: "",
        word: "placard",
        definition: "a sign or notice carried or displayed publicly",
        synonyms: ["poster", "sign", "banner"],
        examples: [
          "Protesters held placards in the street.",
          "A placard on the door said ‘closed’.",
          "She waved a placard at the rally.",
        ],
        wordPr: "پلاکارد، تابلو اعلان",
        definitionPr: "تابلو یا نوشته‌ای که در مکان عمومی نمایش داده می‌شود",
        synonymsPr: ["تابلو", "پوستر", "اعلان"],
        examplesPr: [
          "معترضان در خیابان پلاکاردهایی در دست داشتند.",
          "تابلویی روی در نوشته بود 'بسته'.",
          "او در تجمع پلاکاردی را تکان می‌داد.",
        ],
      },
      {
        id: 463,
        pronunciation: "kənˈteɪdʒəs",
        imageUrl: "",
        word: "contagious",
        definition: "able to be passed from one person to another",
        synonyms: ["infectious", "transmittable", "communicable"],
        examples: [
          "The flu is highly contagious.",
          "Laughter can be contagious.",
          "He avoided contagious diseases.",
        ],
        wordPr: "مسری، واگیردار",
        definitionPr: "قابل انتقال از یک شخص به دیگری، معمولاً بیماری",
        synonymsPr: ["واگیردار", "قابل انتقال", "مُسری"],
        examplesPr: [
          "آنفولانزا بسیار مسری است.",
          "خنده می‌تواند مسری باشد.",
          "او از بیماری‌های مسری دوری می‌کرد.",
        ],
      },
      {
        id: 464,
        pronunciation: "ˈklɜːrdʒi",
        imageUrl: "",
        word: "clergy",
        definition: "religious leaders, especially Christian priests",
        synonyms: ["priesthood", "ministers", "church officials"],
        examples: [
          "The clergy gathered for the ceremony.",
          "He is a respected member of the clergy.",
          "Church and clergy were respected.",
        ],
        wordPr: "روحانیون",
        definitionPr: "رهبران مذهبی، به‌ویژه در کلیسا",
        synonymsPr: ["روحانیت", "کشیشان", "مقامات مذهبی"],
        examplesPr: [
          "روحانیون برای مراسم گرد هم آمدند.",
          "او یکی از اعضای محترم روحانیت است.",
          "کلیسا و روحانیون مورد احترام بودند.",
        ],
      },
      {
        id: 465,
        pronunciation: "ˈkʌstəməri",
        imageUrl: "",
        word: "customary",
        definition: "usual or typical of a particular person or situation",
        synonyms: ["usual", "habitual", "conventional"],
        examples: [
          "It is customary to tip in restaurants.",
          "She greeted me with her customary smile.",
          "The ceremony followed customary rituals.",
        ],
        wordPr: "مرسوم، رایج",
        definitionPr: "عادی یا معمول در یک موقعیت یا برای فرد خاص",
        synonymsPr: ["رایج", "معمول", "مرسوم"],
        examplesPr: [
          "در رستوران‌ها انعام دادن مرسوم است.",
          "او با لبخند همیشگی‌اش به من سلام کرد.",
          "مراسم طبق آیین‌های مرسوم برگزار شد.",
        ],
      },
      {
        id: 466,
        pronunciation: "trænsˈpærənt",
        imageUrl: "",
        word: "transparent",
        definition: "easy to see through or understand",
        synonyms: ["clear", "see-through", "obvious"],
        examples: [
          "The glass is completely transparent.",
          "She gave a transparent explanation.",
          "The box has a transparent lid.",
        ],
        wordPr: "شفاف، آشکار",
        definitionPr: "قابل دیدن از میان آن یا به راحتی قابل درک",
        synonymsPr: ["روشن", "آشکار", "قابل درک"],
        examplesPr: [
          "شیشه کاملاً شفاف است.",
          "او توضیحی شفاف داد.",
          "جعبه دارای درپوش شفاف است.",
        ],
      },
      {
        id: 467,
        pronunciation: "skɔːld",
        imageUrl: "",
        word: "scald",
        definition: "to burn with hot liquid or steam",
        synonyms: ["burn", "blister", "sear"],
        examples: [
          "He scalded his hand with boiling water.",
          "Be careful not to scald your tongue.",
          "Scalding water spilled on her leg.",
        ],
        wordPr: "سوختن با مایع داغ",
        definitionPr: "سوزاندن با مایعات داغ یا بخار",
        synonymsPr: ["سوختن", "تاول زدن", "داغ شدن"],
        examplesPr: [
          "او دستش را با آب جوش سوزاند.",
          "مراقب باش زبانت را نسوزانی.",
          "آب داغ روی پایش ریخت و او را سوزاند.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
