export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 492,
        pronunciation: "meɪnˈteɪn",
        imageUrl: "",
        word: "maintain",
        definition:
          "to keep something in good condition or continue it without change",
        synonyms: ["preserve", "sustain", "continue"],
        examples: [
          "They maintain the building well.",
          "You must maintain a healthy diet.",
          "She maintained her innocence.",
        ],
        wordPr: "حفظ کردن، نگه داشتن",
        definitionPr: "نگه داشتن چیزی در وضعیت خوب یا ادامه دادن بدون تغییر",
        synonymsPr: ["حفظ کردن", "ادامه دادن", "نگهداری کردن"],
        examplesPr: [
          "آن‌ها ساختمان را خوب نگهداری می‌کنند.",
          "باید رژیم غذایی سالمی را حفظ کنی.",
          "او بی‌گناهی‌اش را حفظ کرد.",
        ],
      },
      {
        id: 493,
        pronunciation: "snʌb",
        imageUrl: "",
        word: "snub",
        definition: "to ignore or behave coldly toward someone",
        synonyms: ["ignore", "rebuff", "shun"],
        examples: [
          "He snubbed his old friend.",
          "She felt snubbed at the party.",
          "They snubbed the offer without discussion.",
        ],
        wordPr: "بی‌اعتنایی کردن، نادیده گرفتن",
        definitionPr: "نادیده گرفتن یا سرد برخورد کردن با کسی",
        synonymsPr: ["نادیده گرفتن", "رد کردن", "تحقیر کردن"],
        examplesPr: [
          "او دوست قدیمی‌اش را نادیده گرفت.",
          "او در مهمانی احساس بی‌توجهی کرد.",
          "آن‌ها بدون بحث پیشنهاد را رد کردند.",
        ],
      },
      {
        id: 494,
        pronunciation: "ɪnˈdjʊə(r)",
        imageUrl: "",
        word: "endure",
        definition: "to suffer something difficult or unpleasant patiently",
        synonyms: ["tolerate", "bear", "withstand"],
        examples: [
          "She endured the pain silently.",
          "They endured years of hardship.",
          "I can't endure his behavior anymore.",
        ],
        wordPr: "تحمل کردن",
        definitionPr: "با صبر رنج یا شرایط سخت را تحمل کردن",
        synonymsPr: ["تاب آوردن", "تحمل کردن", "پایداری کردن"],
        examplesPr: [
          "او درد را بی‌صدا تحمل کرد.",
          "آن‌ها سال‌ها سختی را تحمل کردند.",
          "دیگر نمی‌توانم رفتار او را تحمل کنم.",
        ],
      },
      {
        id: 495,
        pronunciation: "ræθ",
        imageUrl: "",
        word: "wrath",
        definition: "extreme anger",
        synonyms: ["rage", "fury", "outrage"],
        examples: [
          "He feared the wrath of his boss.",
          "The king's wrath was terrifying.",
          "Her betrayal sparked his wrath.",
        ],
        wordPr: "خشم شدید",
        definitionPr: "عصبانیت شدید و گاهی ترسناک",
        synonymsPr: ["خشم", "غضب", "عصبانیت"],
        examplesPr: [
          "او از خشم رئیسش می‌ترسید.",
          "خشم پادشاه ترسناک بود.",
          "خیانت او خشمش را شعله‌ور کرد.",
        ],
      },
      {
        id: 496,
        pronunciation: "ɪkˈspəʊz",
        imageUrl: "",
        word: "expose",
        definition:
          "to make something visible or reveal it to danger or attention",
        synonyms: ["reveal", "uncover", "disclose"],
        examples: [
          "The scandal was exposed by the media.",
          "Don't expose the film to light.",
          "He exposed the truth.",
        ],
        wordPr: "نمایان کردن، افشا کردن",
        definitionPr: "آشکار کردن یا در معرض قرار دادن چیزی",
        synonymsPr: ["افشا کردن", "نمایان ساختن", "برملا کردن"],
        examplesPr: [
          "رسانه‌ها این رسوایی را افشا کردند.",
          "فیلم را در معرض نور قرار نده.",
          "او حقیقت را فاش کرد.",
        ],
      },
      {
        id: 497,
        pronunciation: "ˈledʒənd",
        imageUrl: "",
        word: "legend",
        definition:
          "a traditional story or a famous person admired for achievements",
        synonyms: ["myth", "fable", "icon"],
        examples: [
          "He is a football legend.",
          "The legend of King Arthur is famous.",
          "She became a legend in her field.",
        ],
        wordPr: "افسانه، اسطوره",
        definitionPr: "داستان سنتی یا فردی مشهور و ستایش‌شده",
        synonymsPr: ["افسانه", "داستان", "چهره افسانه‌ای"],
        examplesPr: [
          "او یک اسطوره فوتبال است.",
          "افسانه شاه آرتور معروف است.",
          "او در حرفه‌اش به اسطوره تبدیل شد.",
        ],
      },
      {
        id: 498,
        pronunciation: "ˈpɒndə(r)",
        imageUrl: "",
        word: "ponder",
        definition: "to think deeply or carefully about something",
        synonyms: ["contemplate", "consider", "reflect"],
        examples: [
          "She pondered the question for a while.",
          "Ponder your decision carefully.",
          "He sat alone, pondering his future.",
        ],
        wordPr: "تفکر کردن، تأمل کردن",
        definitionPr: "عمیق و با دقت درباره چیزی فکر کردن",
        synonymsPr: ["تأمل کردن", "اندیشه کردن", "سنجیدن"],
        examplesPr: [
          "او مدتی درباره سؤال تأمل کرد.",
          "با دقت درباره تصمیم‌ات فکر کن.",
          "او تنها نشسته بود و به آینده‌اش فکر می‌کرد.",
        ],
      },
      {
        id: 499,
        pronunciation: "rɪˈzaɪn",
        imageUrl: "",
        word: "resign",
        definition: "to voluntarily leave a job or position",
        synonyms: ["quit", "step down", "leave"],
        examples: [
          "He resigned from his job.",
          "She resigned as manager.",
          "The minister resigned over the scandal.",
        ],
        wordPr: "استعفا دادن",
        definitionPr: "به طور داوطلبانه شغلی را ترک کردن",
        synonymsPr: ["کناره‌گیری کردن", "استعفا دادن", "ترک کردن"],
        examplesPr: [
          "او از شغلش استعفا داد.",
          "او از سمت مدیر کناره‌گیری کرد.",
          "وزیر به دلیل رسوایی استعفا داد.",
        ],
      },
      {
        id: 500,
        pronunciation: "ˈdræstɪk",
        imageUrl: "",
        word: "drastic",
        definition: "extreme or forceful, especially in effect",
        synonyms: ["extreme", "severe", "harsh"],
        examples: [
          "Drastic changes were made to the policy.",
          "They took drastic action to solve the issue.",
          "The economy needs drastic reform.",
        ],
        wordPr: "شدید، افراطی",
        definitionPr: "بسیار شدید یا قاطع، به ویژه از نظر اثرگذاری",
        synonymsPr: ["افراطی", "سخت", "شدید"],
        examplesPr: [
          "تغییرات شدیدی در سیاست ایجاد شد.",
          "آن‌ها برای حل مشکل، اقدامات قاطعی انجام دادند.",
          "اقتصاد نیاز به اصلاحات شدیدی دارد.",
        ],
      },
      {
        id: 501,
        pronunciation: "wɔːf",
        imageUrl: "",
        word: "wharf",
        definition:
          "a structure built on the shore for ships to load and unload cargo",
        synonyms: ["dock", "pier", "quay"],
        examples: [
          "The ship docked at the wharf.",
          "Fishermen waited by the wharf.",
          "Cargo was unloaded onto the wharf.",
        ],
        wordPr: "اسکله، بارانداز",
        definitionPr: "سازه‌ای در ساحل برای بارگیری یا تخلیه کشتی‌ها",
        synonymsPr: ["اسکله", "بندرگاه", "لنگرگاه"],
        examplesPr: [
          "کشتی در اسکله پهلو گرفت.",
          "ماهیگیران در کنار اسکله منتظر بودند.",
          "بارها روی اسکله تخلیه شدند.",
        ],
      },
      {
        id: 502,
        pronunciation: "əˈmɛnd",
        imageUrl: "",
        word: "amend",
        definition: "to make changes to improve or correct something",
        synonyms: ["modify", "adjust", "revise"],
        examples: [
          "They amended the law.",
          "You should amend your mistakes.",
          "The contract was amended last week.",
        ],
        wordPr: "اصلاح کردن، تغییر دادن",
        definitionPr: "اعمال تغییر برای بهتر شدن یا تصحیح چیزی",
        synonymsPr: ["اصلاح کردن", "تغییر دادن", "تجدیدنظر کردن"],
        examplesPr: [
          "آن‌ها قانون را اصلاح کردند.",
          "باید اشتباهاتت را اصلاح کنی.",
          "قرارداد هفته گذشته اصلاح شد.",
        ],
      },
      {
        id: 503,
        pronunciation: "ˈbælət",
        imageUrl: "",
        word: "ballot",
        definition: "a process of voting, typically in secret",
        synonyms: ["vote", "election", "poll"],
        examples: [
          "He cast his ballot early.",
          "The decision was made by ballot.",
          "They voted by secret ballot.",
        ],
        wordPr: "رأی‌گیری، رأی مخفی",
        definitionPr: "فرآیند رأی دادن، معمولاً به‌صورت مخفیانه",
        synonymsPr: ["رأی", "رأی‌گیری", "انتخابات"],
        examplesPr: [
          "او رأی خود را زودتر داد.",
          "تصمیم از طریق رأی‌گیری گرفته شد.",
          "آن‌ها به‌صورت رأی مخفی رأی دادند.",
        ],
      },
      {
        id: 504,
        pronunciation: "candidate",
        imageUrl: "",
        word: "candidate",
        definition: "person who is proposed for some office orhonor",
        synonyms: ["volunteer", "applicant"],
        examples: [
          "We can have a maximum of four candidates for the office of president.",
          "Each candidate for mayor seemed confident he would be victorious.",
          "Derek Jeter is a candidate for baseball's Hall of Fame.",
        ],
        wordPr: "نامزد، کاندید",
        definitionPr: "فرآیند رأی دادن، معمولاً به‌صورت مخفیانه",
        synonymsPr: ["رأی", "رأی‌گیری", "انتخابات"],
        examplesPr: [
          "ما می‌توانیم حداکثر چهار نامزد برای مقام ریاست جمهوری داشته باشیم.",
          "به نظر می‌رسید هر یک از نامزدهای شهرداری از پیروزی خود مطمئن بودند.",
          "درک جتر نامزد عضویت در تالار مشاهیر بیسبال شد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
