export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 25,
        pronunciation: "ˈtɪpɪkəl",
        imageUrl: "",
        word: "typical",
        definition: "being like others of its kind",
        synonyms: ["usual", "normal"],
        examples: [
          "The typical dog barks at strangers.",
          "It is typical of him to be late.",
          "Rainy weather is typical in April.",
        ],
        wordPr: "معمولی، نمونه",
        definitionPr: "مانند دیگران از نوع خود؛ معمولی",
        synonymsPr: ["معمولی", "نمونه"],
        examplesPr: [
          "سگ معمولی به غریبه‌ها پارس می‌کند.",
          "دیر رسیدن از خصوصیات معمول اوست.",
          "هوای بارانی در آوریل معمول است.",
        ],
      },
      {
        id: 26,
        pronunciation: "ˈmɪnɪməm",
        imageUrl: "",
        word: "minimum",
        definition: "the least possible amount",
        synonyms: ["least", "smallest"],
        examples: [
          "The minimum age for voting is 18.",
          "Keep expenses to a minimum.",
          "He did the minimum required to pass.",
        ],
        wordPr: "حداقل",
        definitionPr: "کمترین مقدار ممکن",
        synonymsPr: ["کمترین", "حداقل"],
        examplesPr: [
          "حداقل سن رای دادن ۱۸ سال است.",
          "هزینه‌ها را به حداقل برسان.",
          "او حداقل کار لازم برای قبولی را انجام داد.",
        ],
      },
      {
        id: 27,
        pronunciation: "skɛrs",
        imageUrl: "",
        word: "scarce",
        definition: "hard to get; rare",
        synonyms: ["rare", "insufficient"],
        examples: [
          "Food was scarce during the drought.",
          "Good jobs are scarce these days.",
          "Water is scarce in the desert.",
        ],
        wordPr: "کمیاب",
        definitionPr: "به سختی پیدا می‌شود؛ نادر",
        synonymsPr: ["نادر", "کم"],
        examplesPr: [
          "در زمان خشکسالی غذا کمیاب بود.",
          "شغل خوب این روزها کمیاب است.",
          "آب در بیابان کمیاب است.",
        ],
      },
      {
        id: 28,
        pronunciation: "ˈænjuəl",
        imageUrl: "",
        word: "annual",
        definition: "once a year; happening every year",
        synonyms: ["yearly", "once a year"],
        examples: [
          "The school holds an annual sports day.",
          "We have an annual meeting in January.",
          "The annual rainfall is low in this region.",
        ],
        wordPr: "سالانه",
        definitionPr: "یک بار در سال؛ هر سال اتفاق می‌افتد",
        synonymsPr: ["سالانه", "یک‌بار در سال"],
        examplesPr: [
          "مدرسه یک روز ورزشی سالانه برگزار می‌کند.",
          "ما هر سال در ژانویه جلسه سالانه داریم.",
          "بارش سالانه در این منطقه کم است.",
        ],
      },
      {
        id: 29,
        pronunciation: "pərˈsweɪd",
        imageUrl: "",
        word: "persuade",
        definition: "win over to do or believe; make willing",
        synonyms: ["convince", "influence"],
        examples: [
          "He persuaded me to go to the party.",
          "She persuaded her friend to try the new restaurant.",
          "Nothing could persuade him to change his mind.",
        ],
        wordPr: "متقاعد کردن",
        definitionPr: "راضی کردن یا وادار کردن کسی به انجام کاری",
        synonymsPr: ["قانع کردن", "وادار کردن"],
        examplesPr: [
          "او من را متقاعد کرد به مهمانی بروم.",
          "او دوستش را قانع کرد رستوران جدید را امتحان کند.",
          "هیچ چیز نتوانست او را متقاعد کند نظرش را عوض کند.",
        ],
      },
      {
        id: 30,
        pronunciation: "ɪˈsɛnʃəl",
        imageUrl: "",
        word: "essential",
        definition: "necessary; very important",
        synonyms: ["necessary", "vital"],
        examples: [
          "Food and water are essential for life.",
          "It is essential to study for the exam.",
          "Good communication is essential in a team.",
        ],
        wordPr: "ضروری",
        definitionPr: "لازم؛ بسیار مهم",
        synonymsPr: ["لازم", "حیاتی"],
        examplesPr: [
          "غذا و آب برای زندگی ضروری هستند.",
          "مطالعه برای امتحان ضروری است.",
          "ارتباط خوب در یک تیم ضروری است.",
        ],
      },
      {
        id: 31,
        pronunciation: "blɛnd",
        imageUrl: "",
        word: "blend",
        definition: "mix together thoroughly; a mixture",
        synonyms: ["mix", "combine"],
        examples: [
          "Blend the eggs with the milk.",
          "The artist blended red and yellow to make orange.",
          "This tea is a blend of several herbs.",
        ],
        wordPr: "ترکیب کردن، مخلوط",
        definitionPr: "کاملاً مخلوط کردن؛ ترکیب",
        synonymsPr: ["مخلوط کردن", "ترکیب"],
        examplesPr: [
          "تخم‌مرغ‌ها را با شیر مخلوط کن.",
          "هنرمند قرمز و زرد را ترکیب کرد تا نارنجی بسازد.",
          "این چای ترکیبی از چند گیاه است.",
        ],
      },
      {
        id: 32,
        pronunciation: "ˈvɪzəbl",
        imageUrl: "",
        word: "visible",
        definition: "able to be seen",
        synonyms: ["seeable", "observable"],
        examples: [
          "The mountains were visible from the window.",
          "There was a visible improvement in his health.",
          "The stars are not visible during the day.",
        ],
        wordPr: "قابل مشاهده",
        definitionPr: "قابل دیدن",
        synonymsPr: ["قابل دیدن", "مشهود"],
        examplesPr: [
          "کوه‌ها از پنجره قابل مشاهده بودند.",
          "بهبودی قابل مشاهده‌ای در سلامتی او بود.",
          "ستاره‌ها در طول روز قابل مشاهده نیستند.",
        ],
      },
      {
        id: 33,
        pronunciation: "ɪkˈspɛnsɪv",
        imageUrl: "",
        word: "expensive",
        definition: "costing a lot of money",
        synonyms: ["costly", "high-priced"],
        examples: [
          "This car is very expensive.",
          "He bought an expensive watch.",
          "Eating out can be expensive.",
        ],
        wordPr: "گران",
        definitionPr: "هزینه‌بر؛ پرهزینه",
        synonymsPr: ["گران", "پر هزینه"],
        examplesPr: [
          "این ماشین خیلی گران است.",
          "او یک ساعت گران خرید.",
          "بیرون غذا خوردن می‌تواند گران باشد.",
        ],
      },
      {
        id: 34,
        pronunciation: "ˈtælənt",
        imageUrl: "",
        word: "talent",
        definition: "natural ability",
        synonyms: ["ability", "skill"],
        examples: [
          "She has a talent for music.",
          "He showed great talent as a writer.",
          "Everyone has some kind of talent.",
        ],
        wordPr: "استعداد",
        definitionPr: "توانایی ذاتی",
        synonymsPr: ["استعداد", "مهارت"],
        examplesPr: [
          "او استعداد موسیقی دارد.",
          "او به عنوان نویسنده استعداد زیادی نشان داد.",
          "هر کسی نوعی استعداد دارد.",
        ],
      },
      {
        id: 35,
        pronunciation: "dɪˈvaɪz",
        imageUrl: "",
        word: "devise",
        definition: "think out; plan; invent",
        synonyms: ["invent", "create"],
        examples: [
          "The engineers devised a new method for saving energy.",
          "She devised a plan to improve sales.",
          "We must devise a way to solve the problem.",
        ],
        wordPr: "ابداع کردن، طرح کردن",
        definitionPr: "فکر کردن و اختراع یا برنامه‌ریزی کردن",
        synonymsPr: ["ابداع کردن", "اختراع کردن"],
        examplesPr: [
          "مهندسان روشی جدید برای صرفه‌جویی در انرژی ابداع کردند.",
          "او برنامه‌ای برای بهبود فروش طرح کرد.",
          "ما باید راهی برای حل مشکل ابداع کنیم.",
        ],
      },
      {
        id: 36,
        pronunciation: "ˈhoʊlseɪl",
        imageUrl: "",
        word: "wholesale",
        definition: "in large quantity; less than retail in price",
        synonyms: ["bulk", "mass"],
        examples: [
          "He bought the goods wholesale.",
          "Wholesale prices are lower than retail prices.",
          "They sell fruit wholesale to stores.",
        ],
        wordPr: "عمده فروشی",
        definitionPr: "در مقدار زیاد؛ با قیمت کمتر از خرده‌فروشی",
        synonymsPr: ["عمده", "انبوه"],
        examplesPr: [
          "او کالاها را به صورت عمده خرید.",
          "قیمت عمده فروشی کمتر از خرده فروشی است.",
          "آنها میوه را به صورت عمده به فروشگاه‌ها می‌فروشند.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
