export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 217,
        pronunciation: "ˈhɑːrvɪst",
        imageUrl: "",
        word: "harvest",
        definition: "the gathering of crops",
        synonyms: ["gathering", "reaping", "collection"],
        examples: [
          "This year’s harvest was the largest in the last decade.",
          "Farmers are busy during the harvest season.",
          "The harvest of wheat begins in late summer.",
        ],
        wordPr: "برداشت محصول",
        definitionPr: "جمع‌آوری محصولات کشاورزی",
        synonymsPr: ["درو", "جمع‌آوری", "محصول‌برداری"],
        examplesPr: [
          "برداشت امسال بزرگ‌ترین در ده سال گذشته بود.",
          "کشاورزان در فصل برداشت بسیار مشغول هستند.",
          "برداشت گندم در اواخر تابستان آغاز می‌شود.",
        ],
      },
      {
        id: 218,
        pronunciation: "əˈbʌndənt",
        imageUrl: "",
        word: "abundant",
        definition: "more than enough; very plentiful",
        synonyms: ["plentiful", "ample", "bountiful"],
        examples: [
          "There was abundant evidence to support the theory.",
          "The region has an abundant supply of water.",
          "Sunlight is abundant in desert areas.",
        ],
        wordPr: "فراوان",
        definitionPr: "بیش از اندازه، بسیار زیاد",
        synonymsPr: ["زیاد", "وفور", "فراوانی"],
        examplesPr: [
          "شواهد فراوانی برای حمایت از این نظریه وجود داشت.",
          "این منطقه دارای منابع آب فراوان است.",
          "نور خورشید در مناطق بیابانی فراوان است.",
        ],
      },
      {
        id: 219,
        pronunciation: "ʌnˈiːzi",
        imageUrl: "",
        word: "uneasy",
        definition: "not comfortable; worried or nervous",
        synonyms: ["anxious", "nervous", "restless"],
        examples: [
          "She felt uneasy about the interview.",
          "There was an uneasy silence in the room.",
          "He gave her an uneasy look.",
        ],
        wordPr: "نا‌آرام، نگران",
        definitionPr: "احساس ناراحتی یا نگرانی داشتن",
        synonymsPr: ["مضطرب", "نگران", "دل‌آشوب"],
        examplesPr: [
          "او درباره مصاحبه احساس نگرانی داشت.",
          "سکوتی ناآرام در اتاق حاکم بود.",
          "او با نگاهی نگران به او نگاه کرد.",
        ],
      },
      {
        id: 220,
        pronunciation: "ˈkælkjuleɪt",
        imageUrl: "",
        word: "calculate",
        definition: "to find out by using mathematics or reasoning",
        synonyms: ["compute", "figure", "determine"],
        examples: [
          "You can calculate the area by multiplying length and width.",
          "The company calculated the cost of the project.",
          "We need to calculate the risks before investing.",
        ],
        wordPr: "محاسبه کردن",
        definitionPr: "یافتن مقدار با استفاده از ریاضی یا استدلال",
        synonymsPr: ["شمارش کردن", "تخمین زدن", "برآورد کردن"],
        examplesPr: [
          "می‌توانید با ضرب طول در عرض، مساحت را محاسبه کنید.",
          "شرکت هزینه پروژه را محاسبه کرد.",
          "باید قبل از سرمایه‌گذاری، ریسک‌ها را محاسبه کنیم.",
        ],
      },
      {
        id: 221,
        pronunciation: "əbˈzɔːrb",
        imageUrl: "",
        word: "absorb",
        definition: "to soak up or take in",
        synonyms: ["soak", "take in", "consume"],
        examples: [
          "The sponge absorbed the water quickly.",
          "Plants absorb sunlight during photosynthesis.",
          "The book was so interesting, I was completely absorbed.",
        ],
        wordPr: "جذب کردن",
        definitionPr: "جذب یا درون کشیدن چیزی (مثلاً مایع یا اطلاعات)",
        synonymsPr: ["در خود کشیدن", "بلعیدن", "جذب شدن"],
        examplesPr: [
          "اسفنج به سرعت آب را جذب کرد.",
          "گیاهان در فتوسنتز نور خورشید را جذب می‌کنند.",
          "کتاب آن‌قدر جالب بود که کاملاً جذبش شدم.",
        ],
      },
      {
        id: 222,
        pronunciation: "ˈestɪmeɪt",
        imageUrl: "",
        word: "estimate",
        definition: "to form an approximate judgment or opinion",
        synonyms: ["guess", "evaluate", "approximate"],
        examples: [
          "The repairman estimated the cost at $300.",
          "Can you estimate how long the trip will take?",
          "We estimated the number of guests.",
        ],
        wordPr: "تخمین زدن",
        definitionPr: "تشخیص یا برآورد حدودی چیزی",
        synonymsPr: ["پیش‌بینی کردن", "برآورد کردن", "حدس زدن"],
        examplesPr: [
          "تعمیرکار هزینه را حدود ۳۰۰ دلار تخمین زد.",
          "می‌توانی تخمین بزنی سفر چقدر طول می‌کشه؟",
          "ما تعداد مهمانان را تخمین زدیم.",
        ],
      },
      {
        id: 223,
        pronunciation: "ˈmɔːrsl",
        imageUrl: "",
        word: "morsel",
        definition: "a small piece of food",
        synonyms: ["bite", "crumb", "fragment"],
        examples: [
          "She ate every morsel on her plate.",
          "A morsel of bread is enough for now.",
          "He gave the dog a morsel of meat.",
        ],
        wordPr: "لقمه کوچک",
        definitionPr: "تکه کوچک غذا",
        synonymsPr: ["خرده", "تکه", "لقمه"],
        examplesPr: [
          "او هر لقمه غذایش را خورد.",
          "فعلاً یک لقمه نان کافی است.",
          "او یک تکه گوشت به سگ داد.",
        ],
      },
      {
        id: 224,
        pronunciation: "ˈkwoʊtə",
        imageUrl: "",
        word: "quota",
        definition: "a fixed share or amount",
        synonyms: ["allocation", "limit", "share"],
        examples: [
          "Each worker was given a quota of tasks.",
          "The country set a quota on imports.",
          "He reached his sales quota this month.",
        ],
        wordPr: "سهمیه",
        definitionPr: "مقدار یا سهم مشخص شده از چیزی",
        synonymsPr: ["سهم", "مقدار تعیین‌شده", "محدودیت"],
        examplesPr: [
          "به هر کارگر سهمیه‌ای از وظایف داده شد.",
          "کشور برای واردات سهمیه تعیین کرد.",
          "او در این ماه به سهمیه فروش خود رسید.",
        ],
      },
      {
        id: 225,
        pronunciation: "θret",
        imageUrl: "",
        word: "threat",
        definition: "a warning that one may do harm",
        synonyms: ["menace", "danger", "risk"],
        examples: [
          "The threat of war is real.",
          "He made a threat against the manager.",
          "Pollution poses a serious threat to the environment.",
        ],
        wordPr: "تهدید",
        definitionPr: "هشداری که نشان‌دهنده قصد آسیب رساندن است",
        synonymsPr: ["خطر", "هشدار", "ریسک"],
        examplesPr: [
          "تهدید جنگ واقعی است.",
          "او مدیر را تهدید کرد.",
          "آلودگی تهدیدی جدی برای محیط‌ زیست است.",
        ],
      },
      {
        id: 226,
        pronunciation: "bæn",
        imageUrl: "",
        word: "ban",
        definition: "to prohibit or forbid",
        synonyms: ["prohibit", "forbid", "bar"],
        examples: [
          "Smoking is banned in public places.",
          "The government banned the sale of fireworks.",
          "They plan to ban plastic bags.",
        ],
        wordPr: "ممنوع کردن",
        definitionPr: "ممنوع کردن یا قدغن کردن چیزی",
        synonymsPr: ["قدغن کردن", "جلوگیری کردن", "تحریم کردن"],
        examplesPr: [
          "کشیدن سیگار در مکان‌های عمومی ممنوع است.",
          "دولت فروش مواد آتش‌بازی را ممنوع کرد.",
          "آن‌ها قصد دارند استفاده از کیسه‌های پلاستیکی را ممنوع کنند.",
        ],
      },
      {
        id: 227,
        pronunciation: "ˈpænɪk",
        imageUrl: "",
        word: "panic",
        definition: "a sudden fear that dominates or replaces thinking",
        synonyms: ["fear", "alarm", "terror"],
        examples: [
          "The fire caused widespread panic.",
          "She was in a panic when she couldn’t find her keys.",
          "Don't panic! Everything is under control.",
        ],
        wordPr: "وحشت",
        definitionPr: "ترس ناگهانی و شدید که باعث از بین رفتن تمرکز می‌شود",
        synonymsPr: ["ترس", "هراس", "دلهره"],
        examplesPr: [
          "آتش‌سوزی باعث وحشت گسترده شد.",
          "وقتی کلیدهایش را پیدا نکرد، وحشت‌زده شد.",
          "وحشت نکن! همه چیز تحت کنترل است.",
        ],
      },
      {
        id: 228,
        pronunciation: "əˈproʊpriət",
        imageUrl: "",
        word: "appropriate",
        definition: "suitable or proper in the circumstances",
        synonyms: ["suitable", "fitting", "proper"],
        examples: [
          "This isn’t an appropriate time to discuss that.",
          "Wear appropriate clothing for the weather.",
          "Her reaction was perfectly appropriate.",
        ],
        wordPr: "مناسب",
        definitionPr: "درست یا مناسب برای موقعیت خاص",
        synonymsPr: ["شایسته", "درخور", "متناسب"],
        examplesPr: [
          "الان زمان مناسبی برای صحبت درباره آن نیست.",
          "لباس مناسب با آب‌وهوا بپوش.",
          "واکنش او کاملاً مناسب بود.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
