export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 277,
        pronunciation: "fɪrs",
        imageUrl: "",
        word: "fierce",
        definition: "very strong or violent",
        synonyms: ["intense", "ferocious", "aggressive"],
        examples: [
          "The fierce storm caused a lot of damage.",
          "He has a fierce temper.",
          "There was fierce competition for the job.",
        ],
        wordPr: "خشمگین، شدید",
        definitionPr: "بسیار شدید یا خشن",
        synonymsPr: ["وحشی", "خشن", "شدید"],
        examplesPr: [
          "طوفان خشمگین خسارات زیادی وارد کرد.",
          "او خلق و خوی تندی دارد.",
          "رقابت شدیدی برای آن شغل وجود داشت.",
        ],
      },
      {
        id: 278,
        pronunciation: "dɪˈtɛst",
        imageUrl: "",
        word: "detest",
        definition: "to hate very much",
        synonyms: ["hate", "loathe", "despise"],
        examples: [
          "I detest violence.",
          "She detests being ignored.",
          "He detests doing homework.",
        ],
        wordPr: "نفرت داشتن، بیزار بودن",
        definitionPr: "بسیار متنفر بودن از چیزی یا کسی",
        synonymsPr: ["متنفر بودن", "نفرت داشتن", "بیزار بودن"],
        examplesPr: [
          "من از خشونت متنفرم.",
          "او از نادیده گرفته شدن بیزار است.",
          "او از انجام تکالیف متنفر است.",
        ],
      },
      {
        id: 279,
        pronunciation: "snɪr",
        imageUrl: "",
        word: "sneer",
        definition: "to smile or speak in a disrespectful way",
        synonyms: ["mock", "scorn", "taunt"],
        examples: [
          "He sneered at my idea.",
          "They sneered when she walked by.",
          "Don't sneer at people who try.",
        ],
        wordPr: "پوزخند زدن، تمسخر کردن",
        definitionPr: "با بی‌احترامی یا تمسخر صحبت کردن یا لبخند زدن",
        synonymsPr: ["پوزخند زدن", "تمسخر کردن", "با تحقیر نگاه کردن"],
        examplesPr: [
          "او به ایده‌ام پوزخند زد.",
          "وقتی او رد شد، آن‌ها پوزخند زدند.",
          "به کسانی که تلاش می‌کنند پوزخند نزن.",
        ],
      },
      {
        id: 280,
        pronunciation: "skaʊl",
        imageUrl: "",
        word: "scowl",
        definition: "to frown in an angry or bad-tempered way",
        synonyms: ["frown", "glare", "grimace"],
        examples: [
          "She scowled at the noisy children.",
          "He scowled when he heard the news.",
          "A deep scowl was on his face.",
        ],
        wordPr: "اخم کردن",
        definitionPr:
          "با حالت عصبانی یا ناراضی به کسی نگاه کردن یا ابرو در هم کشیدن",
        synonymsPr: ["اخم کردن", "با خشم نگاه کردن", "چهره در هم کشیدن"],
        examplesPr: [
          "او به بچه‌های پر سر و صدا اخم کرد.",
          "وقتی خبر را شنید، اخم کرد.",
          "اخم عمیقی روی صورتش بود.",
        ],
      },
      {
        id: 281,
        pronunciation: "ɛnˈkɜːrɪdʒ",
        imageUrl: "",
        word: "encourage",
        definition: "to give support or confidence to someone",
        synonyms: ["support", "inspire", "motivate"],
        examples: [
          "His teacher encouraged him to study harder.",
          "Parents should encourage their children.",
          "She was encouraged by the feedback.",
        ],
        wordPr: "تشویق کردن، دلگرم کردن",
        definitionPr: "ایجاد انگیزه یا دلگرمی برای انجام کاری",
        synonymsPr: ["دلگرم کردن", "تشویق کردن", "حمایت کردن"],
        examplesPr: [
          "معلمش او را به مطالعه بیشتر تشویق کرد.",
          "والدین باید فرزندان خود را تشویق کنند.",
          "او با بازخوردها دلگرم شد.",
        ],
      },
      {
        id: 282,
        pronunciation: "kənˈsɪdər",
        imageUrl: "",
        word: "consider",
        definition: "to think about something carefully",
        synonyms: ["contemplate", "reflect", "weigh"],
        examples: [
          "We are considering buying a new car.",
          "Please consider my request.",
          "He considered the offer for a while.",
        ],
        wordPr: "در نظر گرفتن، بررسی کردن",
        definitionPr: "به دقت درباره چیزی فکر کردن",
        synonymsPr: ["بررسی کردن", "تأمل کردن", "مد نظر قرار دادن"],
        examplesPr: [
          "ما در حال بررسی خرید یک ماشین جدید هستیم.",
          "لطفاً درخواست من را در نظر بگیر.",
          "او مدتی درباره پیشنهاد فکر کرد.",
        ],
      },
      {
        id: 283,
        pronunciation: "ˈvɜːrmɪn",
        imageUrl: "",
        word: "vermin",
        definition: "harmful or annoying small animals or insects",
        synonyms: ["pests", "parasites", "rodents"],
        examples: [
          "The old house was infested with vermin.",
          "Farmers try to get rid of vermin.",
          "Vermin spread disease.",
        ],
        wordPr: "آفات، جانوران موذی",
        definitionPr: "حیوانات یا حشرات کوچک و آزاردهنده یا مضر",
        synonymsPr: ["آفت", "موش و سوسک", "جانور مزاحم"],
        examplesPr: [
          "خانه قدیمی پر از جانوران موذی بود.",
          "کشاورزان سعی در از بین بردن آفات دارند.",
          "آفات می‌توانند بیماری منتقل کنند.",
        ],
      },
      {
        id: 284,
        pronunciation: "weɪl",
        imageUrl: "",
        word: "wail",
        definition: "to cry out loudly in sorrow or pain",
        synonyms: ["cry", "sob", "lament"],
        examples: [
          "The baby wailed all night.",
          "She wailed in grief after hearing the news.",
          "People wailed at the funeral.",
        ],
        wordPr: "ناله کردن، شیون کردن",
        definitionPr: "با صدای بلند و پر از ناراحتی گریه کردن یا فریاد زدن",
        synonymsPr: ["ناله کردن", "شیون کردن", "ضجه زدن"],
        examplesPr: [
          "نوزاد تمام شب ناله می‌کرد.",
          "او بعد از شنیدن خبر شیون کرد.",
          "مردم در مراسم خاکسپاری ناله می‌کردند.",
        ],
      },
      {
        id: 285,
        pronunciation: "ˈsɪmbəl",
        imageUrl: "",
        word: "symbol",
        definition: "a sign, shape, or object that represents something",
        synonyms: ["sign", "emblem", "representation"],
        examples: [
          "The dove is a symbol of peace.",
          "The dollar sign is a symbol of money.",
          "Each religion has its own symbols.",
        ],
        wordPr: "نماد",
        definitionPr: "نشانه یا شکلی که نشان‌دهنده چیز دیگری است",
        synonymsPr: ["نشانه", "علامت", "نماینده"],
        examplesPr: [
          "کبوتر نماد صلح است.",
          "علامت دلار نماد پول است.",
          "هر دین نمادهای خاص خود را دارد.",
        ],
      },
      {
        id: 286,
        pronunciation: "əˈθɔːrəti",
        imageUrl: "",
        word: "authority",
        definition: "the power to give orders or make decisions",
        synonyms: ["power", "control", "influence"],
        examples: [
          "The police have authority to arrest people.",
          "He is an authority on ancient history.",
          "Only the manager has the authority to approve it.",
        ],
        wordPr: "اختیار، قدرت",
        definitionPr: "قدرت یا حق برای تصمیم‌گیری یا صدور دستور",
        synonymsPr: ["قدرت", "نفوذ", "حاکمیت"],
        examplesPr: [
          "پلیس اختیار دستگیری افراد را دارد.",
          "او مرجع تاریخ باستان است.",
          "فقط مدیر اختیار تأیید آن را دارد.",
        ],
      },
      {
        id: 287,
        pronunciation: "ˈnuːtrəl",
        imageUrl: "",
        word: "neutral",
        definition: "not taking sides in a conflict or disagreement",
        synonyms: ["unbiased", "impartial", "nonaligned"],
        examples: [
          "Switzerland remained neutral during the war.",
          "Try to stay neutral in arguments.",
          "He gave a neutral response.",
        ],
        wordPr: "بی‌طرف",
        definitionPr: "درگیر نشدن در اختلاف یا درگیری؛ بدون جانبداری",
        synonymsPr: ["بی‌طرف", "بی‌غرض", "غیرجانبدار"],
        examplesPr: [
          "سوئیس در طول جنگ بی‌طرف ماند.",
          "سعی کن در بحث‌ها بی‌طرف بمانی.",
          "او پاسخ بی‌طرفانه‌ای داد.",
        ],
      },
      {
        id: 288,
        pronunciation: "ˈtraɪfəl",
        imageUrl: "",
        word: "trifle",
        definition: "a small amount or something of little value",
        synonyms: ["bit", "small matter", "triviality"],
        examples: [
          "Don't waste time on trifles.",
          "He paid a trifle for the book.",
          "That’s just a trifle compared to the real problem.",
        ],
        wordPr: "چیز جزئی، بی‌ارزش",
        definitionPr: "چیز کوچک یا کم‌اهمیت",
        synonymsPr: ["ناچیز", "چیز بی‌اهمیت", "اندک"],
        examplesPr: [
          "وقتت را برای چیزهای بی‌اهمیت تلف نکن.",
          "او مبلغ ناچیزی برای آن کتاب پرداخت.",
          "این فقط یک چیز جزئی نسبت به مشکل اصلی است.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
