export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 265,
        pronunciation: "ˈreptaɪl",
        imageUrl: "",
        word: "reptile",
        definition: "a cold-blooded animal with scales that lays eggs",
        synonyms: ["lizard", "snake", "amphibian"],
        examples: [
          "Snakes and lizards are reptiles.",
          "The zoo has many types of reptiles.",
          "Reptiles are cold-blooded animals.",
        ],
        wordPr: "خزنده",
        definitionPr: "حیوان خونسرد با پوست فلس‌دار که تخم‌گذار است",
        synonymsPr: ["مار", "سوسمار", "جانور خزنده"],
        examplesPr: [
          "مارها و سوسمارها جزو خزندگان هستند.",
          "باغ‌وحش انواع مختلفی از خزندگان دارد.",
          "خزندگان حیواناتی خونسرد هستند.",
        ],
      },
      {
        id: 266,
        pronunciation: "ˈrɛərli",
        imageUrl: "",
        word: "rarely",
        definition: "not often; infrequently",
        synonyms: ["seldom", "hardly ever", "occasionally"],
        examples: [
          "She rarely eats junk food.",
          "I rarely go to the movies.",
          "He rarely speaks in public.",
        ],
        wordPr: "به ندرت",
        definitionPr: "نه به طور مکرر؛ گاهی اوقات",
        synonymsPr: ["به‌ندرت", "کم", "بندرت"],
        examplesPr: [
          "او به ندرت غذای ناسالم می‌خورد.",
          "من به ندرت به سینما می‌روم.",
          "او به ندرت در جمع صحبت می‌کند.",
        ],
      },
      {
        id: 267,
        pronunciation: "fərˈbɪd",
        imageUrl: "",
        word: "forbid",
        definition: "to order someone not to do something",
        synonyms: ["prohibit", "ban", "disallow"],
        examples: [
          "Smoking is forbidden here.",
          "My parents forbid me to stay out late.",
          "The law forbids drunk driving.",
        ],
        wordPr: "ممنوع کردن",
        definitionPr: "دستور به انجام ندادن کاری دادن",
        synonymsPr: ["قدغن کردن", "ممنوع کردن", "باز داشتن"],
        examplesPr: [
          "سیگار کشیدن اینجا ممنوع است.",
          "والدینم من را از دیر بیرون ماندن منع کردند.",
          "قانون رانندگی در حالت مستی را ممنوع کرده است.",
        ],
      },
      {
        id: 268,
        pronunciation: "ˈlɑːdʒɪkəl",
        imageUrl: "",
        word: "logical",
        definition: "reasonable; based on clear thinking",
        synonyms: ["rational", "sensible", "coherent"],
        examples: [
          "That’s a logical conclusion.",
          "He made a logical argument.",
          "It’s only logical to plan ahead.",
        ],
        wordPr: "منطقی",
        definitionPr: "بر اساس استدلال و عقل سلیم",
        synonymsPr: ["عقلانی", "معقول", "منطبق با منطق"],
        examplesPr: [
          "این یک نتیجه‌گیری منطقی است.",
          "او استدلال منطقی ارائه داد.",
          "برنامه‌ریزی از پیش فقط منطقی است.",
        ],
      },
      {
        id: 269,
        pronunciation: "ɪɡˈzɪbɪt",
        imageUrl: "",
        word: "exhibit",
        definition: "to show or display something",
        synonyms: ["display", "present", "demonstrate"],
        examples: [
          "The artist exhibited her paintings.",
          "He exhibited signs of stress.",
          "Rare books were exhibited at the museum.",
        ],
        wordPr: "نمایش دادن",
        definitionPr: "نشان دادن یا در معرض دید قرار دادن",
        synonymsPr: ["ارائه کردن", "به نمایش گذاشتن", "نشان دادن"],
        examplesPr: [
          "هنرمند نقاشی‌هایش را به نمایش گذاشت.",
          "او علائم استرس را نشان داد.",
          "کتاب‌های نایاب در موزه به نمایش گذاشته شدند.",
        ],
      },
      {
        id: 270,
        pronunciation: "prəˈsiːd",
        imageUrl: "",
        word: "proceed",
        definition: "to continue or move forward",
        synonyms: ["continue", "advance", "go on"],
        examples: [
          "We may proceed with the plan.",
          "After a short break, he proceeded to speak.",
          "Please proceed to the next page.",
        ],
        wordPr: "ادامه دادن، پیش رفتن",
        definitionPr: "حرکت کردن یا ادامه دادن چیزی",
        synonymsPr: ["ادامه دادن", "پیش رفتن", "جلو رفتن"],
        examplesPr: [
          "می‌توانیم با برنامه ادامه دهیم.",
          "بعد از یک وقفه کوتاه، او به صحبت ادامه داد.",
          "لطفاً به صفحه بعدی بروید.",
        ],
      },
      {
        id: 271,
        pronunciation: "prɪˈkɔːʃən",
        imageUrl: "",
        word: "precaution",
        definition: "a measure taken in advance to prevent harm",
        synonyms: ["safety measure", "protection", "safeguard"],
        examples: [
          "He took precautions against theft.",
          "Use caution and take all necessary precautions.",
          "Vaccines are a precaution against disease.",
        ],
        wordPr: "احتیاط",
        definitionPr: "اقدامی که از قبل برای جلوگیری از خطر انجام می‌شود",
        synonymsPr: ["پیشگیری", "تدبیر", "اقدام احتیاطی"],
        examplesPr: [
          "او اقدامات احتیاطی در برابر دزدی انجام داد.",
          "با احتیاط عمل کن و همه اقدامات لازم را انجام بده.",
          "واکسیناسیون اقدامی پیشگیرانه در برابر بیماری است.",
        ],
      },
      {
        id: 272,
        pronunciation: "ɪkˈstrækt",
        imageUrl: "",
        word: "extract",
        definition: "to remove or take out",
        synonyms: ["remove", "pull out", "withdraw"],
        examples: [
          "Dentists extract teeth.",
          "They extracted oil from the ground.",
          "Please extract the data from this file.",
        ],
        wordPr: "استخراج کردن، بیرون کشیدن",
        definitionPr: "بیرون آوردن یا خارج کردن چیزی",
        synonymsPr: ["بیرون کشیدن", "خارج کردن", "استخراج کردن"],
        examplesPr: [
          "دندان‌پزشکان دندان‌ها را می‌کشند.",
          "آن‌ها نفت را از زمین استخراج کردند.",
          "لطفاً اطلاعات را از این فایل استخراج کن.",
        ],
      },
      {
        id: 273,
        pronunciation: "ˈpraɪər",
        imageUrl: "",
        word: "prior",
        definition: "earlier in time or order",
        synonyms: ["previous", "earlier", "former"],
        examples: [
          "I have a prior appointment.",
          "Prior experience is required.",
          "They had no prior warning.",
        ],
        wordPr: "قبلی، پیشین",
        definitionPr: "پیش از زمان یا ترتیب مشخصی",
        synonymsPr: ["سابق", "پیشین", "قبلی"],
        examplesPr: [
          "من قبلاً وقت ملاقات دارم.",
          "تجربه قبلی لازم است.",
          "آن‌ها هیچ هشدار قبلی نداشتند.",
        ],
      },
      {
        id: 274,
        pronunciation: "ɪmˈbreɪs",
        imageUrl: "",
        word: "embrace",
        definition: "to hug; to accept or support willingly",
        synonyms: ["hug", "accept", "adopt"],
        examples: [
          "They embraced each other warmly.",
          "She embraced the new culture quickly.",
          "He embraced the opportunity gladly.",
        ],
        wordPr: "در آغوش گرفتن، پذیرفتن",
        definitionPr: "در آغوش کشیدن یا با میل پذیرفتن چیزی",
        synonymsPr: ["بغل کردن", "پذیرفتن", "در آغوش گرفتن"],
        examplesPr: [
          "آن‌ها یکدیگر را گرم در آغوش گرفتند.",
          "او فرهنگ جدید را به سرعت پذیرفت.",
          "او با خوشحالی این فرصت را پذیرفت.",
        ],
      },
      {
        id: 275,
        pronunciation: "ˈvæliənt",
        imageUrl: "",
        word: "valiant",
        definition: "brave and determined",
        synonyms: ["brave", "courageous", "heroic"],
        examples: [
          "The firefighter made a valiant effort.",
          "She fought a valiant battle against cancer.",
          "The soldier was honored for his valiant service.",
        ],
        wordPr: "دلیر، شجاع",
        definitionPr: "شجاع و مصمم در مواجهه با خطر یا سختی",
        synonymsPr: ["دلیر", "شجاع", "قهرمانانه"],
        examplesPr: [
          "آتش‌نشان تلاش دلیرانه‌ای کرد.",
          "او مبارزه‌ای شجاعانه با سرطان داشت.",
          "سرباز به خاطر خدمت قهرمانانه‌اش مورد تقدیر قرار گرفت.",
        ],
      },
      {
        id: 276,
        pronunciation: "ˈpɑːrʃəl",
        imageUrl: "",
        word: "partial",
        definition: "not complete; favoring one side",
        synonyms: ["incomplete", "biased", "unfinished"],
        examples: [
          "We only have partial information.",
          "The judge was accused of being partial.",
          "She showed partiality toward her nephew.",
        ],
        wordPr: "جزئی، جانبدارانه",
        definitionPr: "ناتمام یا دارای تمایل به یک طرف",
        synonymsPr: ["ناتمام", "جانبدار", "نسبی"],
        examplesPr: [
          "ما فقط اطلاعات جزئی داریم.",
          "قاضی به جانبداری متهم شد.",
          "او تمایل خاصی به برادرزاده‌اش نشان داد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
