export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 97,
        pronunciation: "/vɪˈsɪnəti/",
        imageUrl: "",
        word: "vicinity",
        definition: "the area near or surrounding a particular place",
        synonyms: ["proximity", "neighborhood", "surroundings"],
        examples: [
          "There are several good restaurants in the vicinity.",
          "The police searched the vicinity for clues.",
          "We chose this hotel because of its vicinity to the beach.",
        ],
        wordPr: "مجاورت",
        definitionPr: "ناحیه اطراف یا نزدیک به یک مکان خاص",
        synonymsPr: ["حوالی", "همسایگی"],
        examplesPr: [
          "چندین رستوران خوب در حوالی اینجا وجود دارد.",
          "پلیس اطراف محل را برای یافتن سرنخ‌ها جستجو کرد.",
          "ما این هتل را به دلیل نزدیکی‌اش به ساحل انتخاب کردیم.",
        ],
      },
      {
        id: 98,
        pronunciation: "/ˈsentʃəri/",
        imageUrl: "",
        word: "century",
        definition: "a period of 100 years",
        synonyms: ["hundred years", "centennial"],
        examples: [
          "The cathedral was built in the 13th century.",
          "Technology has advanced rapidly in the past century.",
          "This manuscript is centuries old.",
        ],
        wordPr: "قرن",
        definitionPr: "دوره‌ای به مدت ۱۰۰ سال",
        synonymsPr: ["صد سال"],
        examplesPr: [
          "این کلیسا در قرن سیزدهم ساخته شد.",
          "تکنولوژی در قرن گذشته به سرعت پیشرفت کرده است.",
          "این دستنویس قرن‌ها قدمت دارد.",
        ],
      },
      {
        id: 99,
        pronunciation: "/reɪdʒ/",
        imageUrl: "",
        word: "rage",
        definition: "violent, uncontrollable anger",
        synonyms: ["fury", "wrath", "outrage"],
        examples: [
          "He was filled with rage after the insult.",
          "The storm raged all night.",
          "Her sudden rage surprised everyone.",
        ],
        wordPr: "خشم شدید",
        definitionPr: "عصبانیت شدید و غیرقابل کنترل",
        synonymsPr: ["غضب", "خشونت"],
        examplesPr: [
          "او پس از آن توهین پر از خشم شد.",
          "طوفان تمام شب با خشونت ادامه داشت.",
          "خشم ناگهانی او همه را شگفت‌زده کرد.",
        ],
      },
      {
        id: 100,
        pronunciation: "/ˈdɑːkjʊmənt/",
        imageUrl: "",
        word: "document",
        definition:
          "a written or printed record that provides information or evidence",
        synonyms: ["record", "paper", "certificate"],
        examples: [
          "Please sign this document before leaving.",
          "Historical documents were preserved in the museum.",
          "The report was documented with photographs.",
        ],
        wordPr: "سند",
        definitionPr:
          "یک رکورد نوشته یا چاپ شده که اطلاعات یا مدرک ارائه می‌دهد",
        synonymsPr: ["مدرک", "پرونده"],
        examplesPr: [
          "لطفاً قبل از ترک این سند را امضا کنید.",
          "اسناد تاریخی در موزه حفظ شده‌اند.",
          "این گزارش با عکس‌ها مستند شده بود.",
        ],
      },
      {
        id: 101,
        pronunciation: "/kənˈkluːd/",
        imageUrl: "",
        word: "conclude",
        definition: "to bring something to an end; to arrive at a judgment",
        synonyms: ["finish", "end", "determine"],
        examples: [
          "The meeting concluded at noon.",
          "After examining the evidence, we concluded he was innocent.",
          "The concert concluded with a fireworks display.",
        ],
        wordPr: "نتیجه‌گیری کردن",
        definitionPr: "پایان دادن به چیزی؛ رسیدن به یک قضاوت",
        synonymsPr: ["تمام کردن", "خاتمه دادن"],
        examplesPr: [
          "جلسه ظهر به پایان رسید.",
          "پس از بررسی مدارک، نتیجه گرفتیم که او بی‌گناه است.",
          "کنسرت با نمایش آتش‌بازی به پایان رسید.",
        ],
      },
      {
        id: 102,
        pronunciation: "/ˌʌndɪˈnaɪəbl/",
        imageUrl: "",
        word: "undeniable",
        definition: "unable to be denied or disputed",
        synonyms: ["indisputable", "irrefutable", "certain"],
        examples: [
          "Her talent is undeniable.",
          "The evidence presents an undeniable truth.",
          "There's an undeniable connection between the two events.",
        ],
        wordPr: "انکارناپذیر",
        definitionPr: "چیزی که نمی‌توان آن را انکار یا رد کرد",
        synonymsPr: ["غیرقابل انکار", "قطعی"],
        examplesPr: [
          "استعداد او انکارناپذیر است.",
          "مدارک یک حقیقت انکارناپذیر را نشان می‌دهند.",
          "یک ارتباط انکارناپذیر بین این دو رویداد وجود دارد.",
        ],
      },
      {
        id: 103,
        pronunciation: "/rɪˈzɪst/",
        imageUrl: "",
        word: "resist",
        definition: "to withstand the action or effect of something",
        synonyms: ["oppose", "withstand", "defy"],
        examples: [
          "The material resists water.",
          "He couldn't resist eating the cake.",
          "They resisted the enemy's attack.",
        ],
        wordPr: "مقاومت کردن",
        definitionPr: "پایداری در برابر عمل یا اثر چیزی",
        synonymsPr: ["ایستادگی کردن", "سرپیچی کردن"],
        examplesPr: [
          "این ماده در برابر آب مقاوم است.",
          "او نتوانست در برابر خوردن کیک مقاومت کند.",
          "آن‌ها در برابر حمله دشمن مقاومت کردند.",
        ],
      },
      {
        id: 104,
        pronunciation: "/læk/",
        imageUrl: "",
        word: "lack",
        definition:
          "the state of being without or not having enough of something",
        synonyms: ["shortage", "absence", "deficiency"],
        examples: [
          "The project failed due to lack of funding.",
          "Her lack of experience showed in her work.",
          "There's no lack of talent in this team.",
        ],
        wordPr: "کمبود",
        definitionPr: "حالت بدون چیزی بودن یا کم داشتن چیزی",
        synonymsPr: ["نداشتن", "نقص"],
        examplesPr: [
          "این پروژه به دلیل کمبود بودجه شکست خورد.",
          "کمبود تجربه او در کارش مشهود بود.",
          "در این تیم کمبود استعداد وجود ندارد.",
        ],
      },
      {
        id: 105,
        pronunciation: "/ɪɡˈnɔːr/",
        imageUrl: "",
        word: "ignore",
        definition: "to refuse to take notice of or acknowledge",
        synonyms: ["disregard", "overlook", "neglect"],
        examples: [
          "He ignored my advice and regretted it later.",
          "She pretended to ignore the rude comment.",
          "You can't ignore the facts.",
        ],
        wordPr: "نادیده گرفتن",
        definitionPr: "امتناع از توجه یا تصدیق چیزی",
        synonymsPr: ["چشم پوشی کردن", "بی‌اعتنایی کردن"],
        examplesPr: [
          "او توصیه من را نادیده گرفت و بعداً پشیمان شد.",
          "او تظاهر کرد که آن نظر بی‌ادبانه را نادیده گرفته است.",
          "نمی‌توانید واقعیات را نادیده بگیرید.",
        ],
      },
      {
        id: 106,
        pronunciation: "/ˈtʃælɪndʒ/",
        imageUrl: "",
        word: "challenge",
        definition: "a task or situation that tests someone's abilities",
        synonyms: ["test", "difficulty", "obstacle"],
        examples: [
          "The exam was a real challenge.",
          "She enjoys challenges that push her limits.",
          "Overcoming poverty is a major challenge.",
        ],
        wordPr: "چالش",
        definitionPr: "یک وظیفه یا موقعیت که توانایی‌های کسی را محک می‌زند",
        synonymsPr: ["آزمون", "مانع"],
        examplesPr: [
          "این امتحان یک چالش واقعی بود.",
          "او از چالش‌هایی که محدودیت‌هایش را به چالش می‌کشند لذت می‌برد.",
          "غلبه بر فقر یک چالش بزرگ است.",
        ],
      },
      {
        id: 107,
        pronunciation: "/ˈmɪnɪtʃər/",
        imageUrl: "",
        word: "miniature",
        definition: "a much smaller version of something",
        synonyms: ["small-scale", "tiny", "mini"],
        examples: [
          "He collects miniature cars.",
          "The artist painted a miniature portrait.",
          "They built a miniature model of the city.",
        ],
        wordPr: "مینیاتوری",
        definitionPr: "نسخه بسیار کوچک‌شده از چیزی",
        synonymsPr: ["کوچک مقیاس", "ریز"],
        examplesPr: [
          "او ماشین‌های مینیاتوری جمع می‌کند.",
          "هنرمند یک پرتره مینیاتوری کشید.",
          "آن‌ها یک مدل مینیاتوری از شهر ساختند.",
        ],
      },
      {
        id: 108,
        pronunciation: "/sɔːrs/",
        imageUrl: "",
        word: "source",
        definition:
          "the place, person, or thing from which something originates",
        synonyms: ["origin", "root", "beginning"],
        examples: [
          "The river's source is in the mountains.",
          "Citrus fruits are a good source of vitamin C.",
          "The journalist refused to reveal her sources.",
        ],
        wordPr: "منبع",
        definitionPr: "مکان، شخص یا چیزی که چیزی از آن سرچشمه می‌گیرد",
        synonymsPr: ["مبدأ", "سرآغاز"],
        examplesPr: [
          "منبع رودخانه در کوهستان است.",
          "مرکبات منبع خوبی از ویتامین C هستند.",
          "روزنامه‌نگار از افشای منابعش خودداری کرد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
