export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 37,
        pronunciation: "ˈveɪpər",
        imageUrl: "",
        word: "vapor",
        definition: "moisture in the air that can be seen; fog; mist",
        synonyms: ["mist", "steam"],
        examples: [
          "Clouds are formed when vapor condenses in the sky.",
          "There was vapor on the bathroom mirror after the shower.",
          "The kettle released vapor as the water boiled.",
        ],
        wordPr: "بخار",
        definitionPr: "رطوبت یا بخار قابل مشاهده در هوا؛ مه",
        synonymsPr: ["بخار", "مه"],
        examplesPr: [
          "ابرها زمانی تشکیل می‌شوند که بخار در آسمان متراکم شود.",
          "بعد از دوش گرفتن، روی آینه حمام بخار بود.",
          "کتری هنگام جوشیدن آب، بخار آزاد کرد.",
        ],
      },
      {
        id: 38,
        pronunciation: "ɪˈlɪməˌneɪt",
        imageUrl: "",
        word: "eliminate",
        definition: "get rid of; remove",
        synonyms: ["remove", "get rid of"],
        examples: [
          "He tried to eliminate all errors from his essay.",
          "Our team was eliminated from the competition.",
          "Doctors are working to eliminate the disease.",
        ],
        wordPr: "حذف کردن",
        definitionPr: "از بین بردن؛ حذف کردن",
        synonymsPr: ["حذف کردن", "از بین بردن"],
        examplesPr: [
          "او سعی کرد همه اشتباهات را از مقاله‌اش حذف کند.",
          "تیم ما از مسابقات حذف شد.",
          "پزشکان در تلاشند بیماری را ریشه‌کن کنند.",
        ],
      },
      {
        id: 39,
        pronunciation: "ˈvɪlən",
        imageUrl: "",
        word: "villain",
        definition: "a very wicked person",
        synonyms: ["criminal", "evil person"],
        examples: [
          "The villain in the story tried to harm the hero.",
          "Every good story needs a villain.",
          "The police finally caught the villain.",
        ],
        wordPr: "آدم شرور، تبهکار",
        definitionPr: "شخص بسیار بد یا شرور",
        synonymsPr: ["آدم بد", "تبهکار"],
        examplesPr: [
          "آدم شرور داستان سعی داشت به قهرمان آسیب بزند.",
          "هر داستان خوبی به یک آدم بد نیاز دارد.",
          "پلیس سرانجام تبهکار را دستگیر کرد.",
        ],
      },
      {
        id: 40,
        pronunciation: "dɛns",
        imageUrl: "",
        word: "dense",
        definition: "closely packed together; thick",
        synonyms: ["thick", "compact"],
        examples: [
          "The forest was so dense that we could hardly walk through it.",
          "Smoke was so dense that we could not see.",
          "The city has a dense population.",
        ],
        wordPr: "متراکم، انبوه",
        definitionPr: "به هم فشرده؛ ضخیم",
        synonymsPr: ["انبوه", "متراکم"],
        examplesPr: [
          "جنگل آنقدر متراکم بود که به سختی می‌توانستیم عبور کنیم.",
          "دود آنقدر متراکم بود که نمی‌توانستیم ببینیم.",
          "این شهر جمعیت متراکمی دارد.",
        ],
      },
      {
        id: 41,
        pronunciation: "ˈjuːtəˌlaɪz",
        imageUrl: "",
        word: "utilize",
        definition: "make use of",
        synonyms: ["use", "employ"],
        examples: [
          "We can utilize solar energy to heat our homes.",
          "She utilized her skills to get a better job.",
          "The teacher utilized new methods in the classroom.",
        ],
        wordPr: "استفاده کردن",
        definitionPr: "به کار بردن؛ استفاده کردن",
        synonymsPr: ["استفاده کردن", "به کار بردن"],
        examplesPr: [
          "ما می‌توانیم از انرژی خورشیدی برای گرم کردن خانه‌ها استفاده کنیم.",
          "او از مهارت‌هایش برای گرفتن شغل بهتر استفاده کرد.",
          "معلم روش‌های جدیدی را در کلاس به کار برد.",
        ],
      },
      {
        id: 42,
        pronunciation: "ˈhjuːmɪd",
        imageUrl: "",
        word: "humid",
        definition: "moist; damp",
        synonyms: ["moist", "damp"],
        examples: [
          "It is very humid in the summer.",
          "The humid air made it hard to breathe.",
          "Plants grow well in humid climates.",
        ],
        wordPr: "مرطوب",
        definitionPr: "نمناک؛ دارای رطوبت",
        synonymsPr: ["مرطوب", "نمناک"],
        examplesPr: [
          "در تابستان هوا بسیار مرطوب است.",
          "هوای مرطوب نفس کشیدن را سخت کرده بود.",
          "گیاهان در آب و هوای مرطوب خوب رشد می‌کنند.",
        ],
      },
      {
        id: 43,
        pronunciation: "ˈθɪəri",
        imageUrl: "",
        word: "theory",
        definition: "explanation based on thought, observation, or reasoning",
        synonyms: ["hypothesis", "idea"],
        examples: [
          "Einstein developed the theory of relativity.",
          "There are several theories about how the universe began.",
          "Her theory was proven correct.",
        ],
        wordPr: "نظریه",
        definitionPr: "توضیح مبتنی بر فکر، مشاهده یا استدلال",
        synonymsPr: ["فرضیه", "ایده"],
        examplesPr: [
          "انیشتین نظریه نسبیت را توسعه داد.",
          "چندین نظریه درباره آغاز جهان وجود دارد.",
          "نظریه او درست ثابت شد.",
        ],
      },
      {
        id: 44,
        pronunciation: "dɪˈsɛnd",
        imageUrl: "",
        word: "descend",
        definition: "go or come down",
        synonyms: ["go down", "drop"],
        examples: [
          "The plane began to descend.",
          "We watched the sun descend below the horizon.",
          "The climbers descended the mountain.",
        ],
        wordPr: "پایین آمدن",
        definitionPr: "پایین رفتن یا آمدن",
        synonymsPr: ["پایین آمدن", "فرود آمدن"],
        examplesPr: [
          "هواپیما شروع به پایین آمدن کرد.",
          "ما تماشاکردیم که خورشید پشت افق پایین رفت.",
          "کوهنوردان از کوه پایین آمدند.",
        ],
      },
      {
        id: 45,
        pronunciation: "ˈsɜːrkjəˌleɪt",
        imageUrl: "",
        word: "circulate",
        definition: "go around; move from place to place or person to person",
        synonyms: ["move around", "flow"],
        examples: [
          "Blood circulates through the body.",
          "A rumor circulated quickly through the school.",
          "Air circulates in the room when the fan is on.",
        ],
        wordPr: "گردش کردن، چرخیدن",
        definitionPr: "دور زدن؛ حرکت کردن از جایی به جای دیگر",
        synonymsPr: ["گردش کردن", "چرخیدن"],
        examplesPr: [
          "خون در بدن گردش می‌کند.",
          "یک شایعه به سرعت در مدرسه پخش شد.",
          "وقتی پنکه روشن است، هوا در اتاق گردش می‌کند.",
        ],
      },
      {
        id: 46,
        pronunciation: "ɪˈnɔːrməs",
        imageUrl: "",
        word: "enormous",
        definition: "extremely large",
        synonyms: ["huge", "immense"],
        examples: [
          "The elephant is an enormous animal.",
          "They spent an enormous amount of money.",
          "The building was enormous.",
        ],
        wordPr: "عظیم، بسیار بزرگ",
        definitionPr: "بسیار بزرگ؛ عظیم",
        synonymsPr: ["عظیم", "بزرگ"],
        examplesPr: [
          "فیل حیوانی بسیار بزرگ است.",
          "آنها مقدار زیادی پول خرج کردند.",
          "ساختمان بسیار عظیم بود.",
        ],
      },
      {
        id: 47,
        pronunciation: "prɪˈdɪkt",
        imageUrl: "",
        word: "predict",
        definition: "tell beforehand",
        synonyms: ["forecast", "foresee"],
        examples: [
          "It is difficult to predict the weather.",
          "No one can predict the future.",
          "Scientists predict that the population will increase.",
        ],
        wordPr: "پیش‌بینی کردن",
        definitionPr: "از قبل گفتن؛ پیش‌بینی کردن",
        synonymsPr: ["پیش‌بینی کردن", "حدس زدن"],
        examplesPr: [
          "پیش‌بینی آب و هوا دشوار است.",
          "هیچ‌کس نمی‌تواند آینده را پیش‌بینی کند.",
          "دانشمندان پیش‌بینی می‌کنند جمعیت افزایش یابد.",
        ],
      },
      {
        id: 48,
        pronunciation: "ˈvænɪʃ",
        imageUrl: "",
        word: "vanish",
        definition: "disappear; go out of sight",
        synonyms: ["disappear", "fade"],
        examples: [
          "The magician made the rabbit vanish.",
          "The sun vanished behind the clouds.",
          "All my worries vanished when I saw my friend.",
        ],
        wordPr: "ناپدید شدن",
        definitionPr: "ناپدید شدن؛ از نظر محو شدن",
        synonymsPr: ["ناپدید شدن", "محو شدن"],
        examplesPr: [
          "جادوگر خرگوش را ناپدید کرد.",
          "خورشید پشت ابرها ناپدید شد.",
          "وقتی دوستم را دیدم همه نگرانی‌هایم ناپدید شد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
