export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 229,
        pronunciation: "ɪˈmɜːrdʒ",
        imageUrl: "",
        word: "emerge",
        definition: "to come into view or become known",
        synonyms: ["appear", "arise", "surface"],
        examples: [
          "The sun emerged from behind the clouds.",
          "New facts emerged during the investigation.",
          "She emerged as a strong leader.",
        ],
        wordPr: "پدیدار شدن",
        definitionPr: "ظاهر شدن یا آشکار شدن",
        synonymsPr: ["ظاهر شدن", "نمایان شدن", "آشکار شدن"],
        examplesPr: [
          "خورشید از پشت ابرها پدیدار شد.",
          "حقایق جدیدی در طول تحقیقات آشکار شد.",
          "او به‌عنوان رهبری قدرتمند ظاهر شد.",
        ],
      },
      {
        id: 230,
        pronunciation: "ˈdʒæɡɪd",
        imageUrl: "",
        word: "jagged",
        definition: "with rough or sharp edges",
        synonyms: ["rough", "pointed", "uneven"],
        examples: [
          "The knife has a jagged edge.",
          "We climbed over the jagged rocks.",
          "He tore his shirt on a jagged piece of metal.",
        ],
        wordPr: "دندانه‌دار، ناهموار",
        definitionPr: "دارای لبه‌های تیز و ناصاف",
        synonymsPr: ["ناهموار", "دندانه‌دار", "لبه‌دار"],
        examplesPr: [
          "لبه چاقو دندانه‌دار است.",
          "از روی صخره‌های ناهموار بالا رفتیم.",
          "پیراهنش به تکه‌ای فلز دندانه‌دار گیر کرد و پاره شد.",
        ],
      },
      {
        id: 231,
        pronunciation: "ˈlɪŋɡər",
        imageUrl: "",
        word: "linger",
        definition: "to stay longer than expected",
        synonyms: ["stay", "remain", "delay"],
        examples: [
          "She lingered at the party after everyone left.",
          "The smell of her perfume lingered in the room.",
          "Don't linger too long in the cold.",
        ],
        wordPr: "باقی ماندن، معطل شدن",
        definitionPr: "بیشتر از حد معمول ماندن یا تأخیر کردن",
        synonymsPr: ["درنگ کردن", "ماندن", "طول دادن"],
        examplesPr: [
          "بعد از رفتن همه، او در مهمانی باقی ماند.",
          "بوی عطرش در اتاق باقی ماند.",
          "زیاد در سرما معطل نکن.",
        ],
      },
      {
        id: 232,
        pronunciation: "ˈæmbʊʃ",
        imageUrl: "",
        word: "ambush",
        definition: "a surprise attack from a hidden place",
        synonyms: ["attack", "trap", "assault"],
        examples: [
          "The soldiers were caught in an ambush.",
          "They planned to ambush the convoy at night.",
          "The enemy ambushed them in the forest.",
        ],
        wordPr: "کمین",
        definitionPr: "حمله ناگهانی از مکان پنهان",
        synonymsPr: ["حمله ناگهانی", "کمین", "تله"],
        examplesPr: [
          "سربازان در کمین گرفتار شدند.",
          "آنها قصد داشتند در شب به کاروان کمین بزنند.",
          "دشمن در جنگل به آن‌ها کمین زد.",
        ],
      },
      {
        id: 233,
        pronunciation: "ˈkræfti",
        imageUrl: "",
        word: "crafty",
        definition: "skilled at tricking others",
        synonyms: ["cunning", "sly", "devious"],
        examples: [
          "The crafty fox escaped the trap.",
          "He came up with a crafty plan to win.",
          "She gave a crafty smile before answering.",
        ],
        wordPr: "زیرک، حیله‌گر",
        definitionPr: "دارای مهارت در فریب دادن دیگران",
        synonymsPr: ["مکار", "حیله‌گر", "زیرک"],
        examplesPr: [
          "روباه حیله‌گر از تله فرار کرد.",
          "او نقشه‌ای زیرکانه برای پیروزی طراحی کرد.",
          "قبل از پاسخ، لبخندی حیله‌گرانه زد.",
        ],
      },
      {
        id: 234,
        pronunciation: "dɪˈfaɪənt",
        imageUrl: "",
        word: "defiant",
        definition: "boldly resisting authority or rules",
        synonyms: ["rebellious", "disobedient", "insubordinate"],
        examples: [
          "The child gave a defiant look to his teacher.",
          "She remained defiant despite the warnings.",
          "He crossed the line with a defiant attitude.",
        ],
        wordPr: "مقاوم، سرکش",
        definitionPr: "مخالفت و مقاومت آشکار در برابر قانون یا قدرت",
        synonymsPr: ["سرکش", "متمرد", "یاغی"],
        examplesPr: [
          "کودک نگاهی سرکش به معلمش انداخت.",
          "با وجود هشدارها، او همچنان سرسخت باقی ماند.",
          "با نگرشی مقاوم از خط عبور کرد.",
        ],
      },
      {
        id: 235,
        pronunciation: "ˈvɪɡər",
        imageUrl: "",
        word: "vigor",
        definition: "physical strength and energy",
        synonyms: ["strength", "energy", "force"],
        examples: [
          "She worked with great vigor.",
          "The athlete showed vigor during the race.",
          "Youth is often associated with vigor.",
        ],
        wordPr: "انرژی، نیرو",
        definitionPr: "قدرت بدنی یا انرژی زیاد",
        synonymsPr: ["توان", "نیرو", "نشاط"],
        examplesPr: [
          "او با انرژی زیادی کار می‌کرد.",
          "ورزشکار در طول مسابقه، توان زیادی نشان داد.",
          "جوانی اغلب با انرژی همراه است.",
        ],
      },
      {
        id: 236,
        pronunciation: "ˈperɪʃ",
        imageUrl: "",
        word: "perish",
        definition: "to die or be destroyed",
        synonyms: ["die", "expire", "cease to exist"],
        examples: [
          "Many people perished in the earthquake.",
          "Food will perish without refrigeration.",
          "They perished in the storm at sea.",
        ],
        wordPr: "مردن، نابود شدن",
        definitionPr: "از بین رفتن یا مردن (معمولاً به شکل ناگهانی)",
        synonymsPr: ["فوت کردن", "هلاک شدن", "نابود شدن"],
        examplesPr: [
          "بسیاری در زلزله جان باختند.",
          "غذا بدون یخچال خراب می‌شود.",
          "در طوفان در دریا نابود شدند.",
        ],
      },
      {
        id: 237,
        pronunciation: "ˈfrædʒəl",
        imageUrl: "",
        word: "fragile",
        definition: "easily broken or damaged",
        synonyms: ["delicate", "breakable", "brittle"],
        examples: [
          "The package contains fragile items.",
          "Be careful — that glass is fragile.",
          "Her health is very fragile right now.",
        ],
        wordPr: "شکننده، حساس",
        definitionPr: "آسان برای شکستن یا آسیب دیدن",
        synonymsPr: ["ظریف", "شکننده", "آسیب‌پذیر"],
        examplesPr: [
          "این بسته شامل وسایل شکننده است.",
          "مواظب باش — آن لیوان شکننده است.",
          "سلامتی او در حال حاضر بسیار حساس است.",
        ],
      },
      {
        id: 238,
        pronunciation: "ˈkæptɪv",
        imageUrl: "",
        word: "captive",
        definition: "a person or animal that is confined or restrained",
        synonyms: ["prisoner", "hostage", "detainee"],
        examples: [
          "The soldiers were taken captive.",
          "She felt like a captive in her own home.",
          "The lion was born in captivity.",
        ],
        wordPr: "اسیر، زندانی",
        definitionPr: "کسی که در بند یا اسارت است",
        synonymsPr: ["زندانی", "گروگان", "در بند"],
        examplesPr: [
          "سربازان اسیر شدند.",
          "او در خانه خود احساس اسارت می‌کرد.",
          "شیر در اسارت به دنیا آمده بود.",
        ],
      },
      {
        id: 239,
        pronunciation: "ˈprɑːspər",
        imageUrl: "",
        word: "prosper",
        definition: "to be successful or fortunate",
        synonyms: ["succeed", "thrive", "flourish"],
        examples: [
          "The business began to prosper after the new manager arrived.",
          "They prospered in their new life abroad.",
          "Hard work helps people prosper.",
        ],
        wordPr: "پیشرفت کردن، موفق شدن",
        definitionPr: "موفق یا ثروتمند شدن",
        synonymsPr: ["موفق شدن", "رشد کردن", "پیشرفت کردن"],
        examplesPr: [
          "کسب‌وکار پس از آمدن مدیر جدید پیشرفت کرد.",
          "در زندگی جدیدشان در خارج موفق شدند.",
          "کار سخت به افراد کمک می‌کند پیشرفت کنند.",
        ],
      },
      {
        id: 240,
        pronunciation: "dɪˈvaʊər",
        imageUrl: "",
        word: "devour",
        definition: "to eat up greedily or quickly",
        synonyms: ["consume", "gobble", "eat up"],
        examples: [
          "The boys devoured their pizza.",
          "The fire devoured the whole building.",
          "She devoured the book in one day.",
        ],
        wordPr: "بلعیدن، با ولع خوردن",
        definitionPr: "با سرعت و اشتیاق زیاد خوردن یا مصرف کردن",
        synonymsPr: ["بلعیدن", "خوردن", "در خود کشیدن"],
        examplesPr: [
          "پسرها با ولع پیتزایشان را خوردند.",
          "آتش تمام ساختمان را بلعید.",
          "او در یک روز تمام کتاب را بلعید.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
