export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 205,
        pronunciation: "/ˈtrædʒədi/",
        imageUrl: "",
        word: "tragedy",
        definition:
          "an event causing great suffering, destruction, and distress",
        synonyms: ["disaster", "catastrophe", "calamity"],
        examples: [
          "The earthquake was a terrible tragedy.",
          "Shakespeare wrote many famous tragedies.",
          "The loss of life was a tragedy for all involved.",
        ],
        wordPr: "تراژدی",
        definitionPr: "رویدادی که باعث رنج، تخریب و پریشانی شدید می‌شود",
        synonymsPr: ["فاجعه", "مصیبت"],
        examplesPr: [
          "زلزله یک تراژدی وحشتناک بود.",
          "شکسپیر بسیاری از تراژدی‌های معروف را نوشت.",
          "از دست دادن جان‌ها برای همه افراد درگیر یک تراژدی بود.",
        ],
      },
      {
        id: 206,
        pronunciation: "/pəˈdɛstriən/",
        imageUrl: "",
        word: "pedestrian",
        definition: "a person walking rather than traveling in a vehicle",
        synonyms: ["walker", "hiker", "foot-traveler"],
        examples: [
          "Pedestrians should use the crosswalk.",
          "The city is building more pedestrian bridges.",
          "The area is popular with pedestrians.",
        ],
        wordPr: "عابر پیاده",
        definitionPr: "شخصی که پیاده راه می‌رود به جای سفر با وسیله نقلیه",
        synonymsPr: ["پیاده‌رو", "راه‌پیما"],
        examplesPr: [
          "عابران پیاده باید از خط عابر پیاده استفاده کنند.",
          "شهر در حال ساخت پل‌های عابر پیاده بیشتری است.",
          "این منطقه در میان عابران پیاده محبوب است.",
        ],
      },
      {
        id: 207,
        pronunciation: "/ɡlæns/",
        imageUrl: "",
        word: "glance",
        definition: "to take a brief or hurried look",
        synonyms: ["glimpse", "peek", "look quickly"],
        examples: [
          "She glanced at her watch.",
          "I glanced through the report.",
          "He glanced around the room.",
        ],
        wordPr: "نگاه اجمالی",
        definitionPr: "نگاه مختصر یا عجله‌ای انداختن",
        synonymsPr: ["نگاه کوتاه", "نگاه سریع"],
        examplesPr: [
          "او نگاهی اجمالی به ساعتش انداخت.",
          "من نگاهی اجمالی به گزارش انداختم.",
          "او نگاهی به اطراف اتاق انداخت.",
        ],
      },
      {
        id: 208,
        pronunciation: "/ˈbʌdʒɪt/",
        imageUrl: "",
        word: "budget",
        definition:
          "an estimate of income and expenditure for a set period of time",
        synonyms: ["financial plan", "estimate", "allocation"],
        examples: [
          "We need to stick to our budget.",
          "The government announced its annual budget.",
          "She keeps a monthly household budget.",
        ],
        wordPr: "بودجه",
        definitionPr: "برآورد درآمد و هزینه برای یک دوره زمانی معین",
        synonymsPr: ["برنامه مالی", "تخمین"],
        examplesPr: [
          "ما باید به بودجه خود پایبند باشیم.",
          "دولت بودجه سالانه خود را اعلام کرد.",
          "او بودجه ماهانه خانوار را نگه می‌دارد.",
        ],
      },
      {
        id: 209,
        pronunciation: "/ˈnɪmbəl/",
        imageUrl: "",
        word: "nimble",
        definition: "quick and light in movement or action",
        synonyms: ["agile", "quick", "graceful"],
        examples: [
          "The gymnast was very nimble.",
          "He has a nimble mind.",
          "Her nimble fingers worked quickly.",
        ],
        wordPr: "چابک",
        definitionPr: "سریع و سبک در حرکت یا عمل",
        synonymsPr: ["زیرک", "فرز"],
        examplesPr: [
          "ژیمناست بسیار چابک بود.",
          "او ذهنی چابک دارد.",
          "انگشتان چابک او سریع کار می‌کردند.",
        ],
      },
      {
        id: 210,
        pronunciation: "/məˈnɪpjʊleɪt/",
        imageUrl: "",
        word: "manipulate",
        definition: "to control or influence cleverly or unfairly",
        synonyms: ["control", "influence", "exploit"],
        examples: [
          "He tried to manipulate the results.",
          "She knows how to manipulate people.",
          "The data was carefully manipulated.",
        ],
        wordPr: "دستکاری کردن",
        definitionPr: "به طور هوشمندانه یا ناعادلانه کنترل یا تأثیر گذاشتن",
        synonymsPr: ["کنترل کردن", "استثمار کردن"],
        examplesPr: [
          "او سعی کرد نتایج را دستکاری کند.",
          "او می‌داند چگونه مردم را دستکاری کند.",
          "داده‌ها با دقت دستکاری شدند.",
        ],
      },
      {
        id: 211,
        pronunciation: "/ˈrɛkləs/",
        imageUrl: "",
        word: "reckless",
        definition:
          "without thinking or caring about the consequences of an action",
        synonyms: ["rash", "careless", "irresponsible"],
        examples: [
          "He was charged with reckless driving.",
          "Don't make reckless decisions.",
          "Her reckless behavior worried her parents.",
        ],
        wordPr: "بی‌پروا",
        definitionPr: "بدون فکر کردن یا اهمیت دادن به عواقب یک عمل",
        synonymsPr: ["بی‌مبالات", "بی‌احتیاط"],
        examplesPr: [
          "او به دلیل رانندگی بی‌پروا متهم شد.",
          "تصمیمات بی‌پروا نگیرید.",
          "رفتار بی‌پروای او والدینش را نگران کرد.",
        ],
      },
      {
        id: 212,
        pronunciation: "/ˈhɒrɪd/",
        imageUrl: "",
        word: "horrid",
        definition: "causing horror or disgust",
        synonyms: ["horrible", "terrible", "dreadful"],
        examples: [
          "What a horrid smell!",
          "She was in a horrid mood.",
          "The accident was a horrid sight.",
        ],
        wordPr: "وحشتناک",
        definitionPr: "باعث وحشت یا انزجار شدن",
        synonymsPr: ["زشت", "هولناک"],
        examplesPr: [
          "چه بوی وحشتناکی!",
          "او در حالتی وحشتناک بود.",
          "حادثه منظره‌ای وحشتناک بود.",
        ],
      },
      {
        id: 213,
        pronunciation: "/reɪv/",
        imageUrl: "",
        word: "rave",
        definition: "to talk wildly or irrationally in excitement or anger",
        synonyms: ["rant", "rage", "gush"],
        examples: [
          "He raved about the new restaurant.",
          "She was raving with fever.",
          "Critics raved about the performance.",
        ],
        wordPr: "ستایش کردن",
        definitionPr: "به طور وحشیانه یا غیرمنطقی در هیجان یا خشم صحبت کردن",
        synonymsPr: ["غُر زدن", "هذیان گفتن"],
        examplesPr: [
          "او در مورد رستوران جدید بسیار تعریف کرد.",
          "او در تب هذیان می‌گفت.",
          "منتقدان در مورد اجرا بسیار تعریف کردند.",
        ],
      },
      {
        id: 214,
        pronunciation: "/ˌiːkəˈnɒmɪkəl/",
        imageUrl: "",
        word: "economical",
        definition:
          "giving good value or service in relation to the resources used",
        synonyms: ["efficient", "thrifty", "cost-effective"],
        examples: [
          "This car is very economical on fuel.",
          "She's economical with her words.",
          "We need an economical solution.",
        ],
        wordPr: "اقتصادی",
        definitionPr:
          "ارزش یا خدمات خوب در رابطه با منابع استفاده شده ارائه دادن",
        synonymsPr: ["مقرون‌به‌صرفه", "صرفه‌جو"],
        examplesPr: [
          "این ماشین در مصرف سوخت بسیار اقتصادی است.",
          "او در کلماتش صرفه‌جو است.",
          "ما به یک راه‌حل اقتصادی نیاز داریم.",
        ],
      },
      {
        id: 215,
        pronunciation: "/ˈluːbrɪkeɪt/",
        imageUrl: "",
        word: "lubricate",
        definition: "to apply a substance to reduce friction",
        synonyms: ["grease", "oil", "moisten"],
        examples: [
          "You need to lubricate the gears regularly.",
          "The mechanic lubricated the engine.",
          "This oil lubricates the machine parts.",
        ],
        wordPr: "روغن کاری کردن",
        definitionPr: "استفاده از ماده‌ای برای کاهش اصطکاک",
        synonymsPr: ["چرب کردن", "روغن زدن"],
        examplesPr: [
          "شما باید به طور منظم چرخ‌دنده‌ها را روغن کاری کنید.",
          "مکانیک موتور را روغن کاری کرد.",
          "این روغن قطعات ماشین را روغن کاری می‌کند.",
        ],
      },
      {
        id: 216,
        pronunciation: "/ɪnˈdʒiːniəs/",
        imageUrl: "",
        word: "ingenious",
        definition: "clever, original, and inventive",
        synonyms: ["creative", "innovative", "resourceful"],
        examples: [
          "That's an ingenious solution!",
          "He invented an ingenious device.",
          "The plan was simple yet ingenious.",
        ],
        wordPr: "نبوغ‌آمیز",
        definitionPr: "هوشمند، اصیل و مبتکر",
        synonymsPr: ["خلاق", "مخترع"],
        examplesPr: [
          "این یک راه‌حل نبوغ‌آمیز است!",
          "او دستگاهی نبوغ‌آمیز اختراع کرد.",
          "طرح ساده اما نبوغ‌آمیز بود.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
