export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 373,
        pronunciation: "rɪˈfɜːr",
        imageUrl: "",
        word: "refer",
        definition: "to mention or direct attention to something",
        synonyms: ["mention", "allude", "point to"],
        examples: [
          "Please refer to the manual for instructions.",
          "He referred to the recent study in his speech.",
          "The doctor referred the patient to a specialist.",
        ],
        wordPr: "ارجاع دادن، اشاره کردن",
        definitionPr: "ذکر یا جلب توجه به چیزی",
        synonymsPr: ["اشاره کردن", "ذکر کردن", "ارجاع دادن"],
        examplesPr: [
          "لطفاً برای راهنمایی به دفترچه مراجعه کنید.",
          "او در سخنرانی خود به مطالعه اخیر اشاره کرد.",
          "پزشک بیمار را به متخصص ارجاع داد.",
        ],
      },
      {
        id: 374,
        pronunciation: "dɪˈstrɛs",
        imageUrl: "",
        word: "distress",
        definition: "extreme anxiety, sorrow, or pain",
        synonyms: ["suffering", "anguish", "trouble"],
        examples: [
          "She was in great distress after hearing the news.",
          "The distress caused by the accident was severe.",
          "They called for help in their distress.",
        ],
        wordPr: "رنج، اضطراب",
        definitionPr: "اضطراب، غم یا درد شدید",
        synonymsPr: ["رنج", "غم", "نگرانی"],
        examplesPr: [
          "او بعد از شنیدن خبر در رنج زیادی بود.",
          "رنج ناشی از حادثه شدید بود.",
          "آن‌ها در رنج خود درخواست کمک کردند.",
        ],
      },
      {
        id: 375,
        pronunciation: "dɪˈmɪnɪʃ",
        imageUrl: "",
        word: "diminish",
        definition: "to become smaller or less",
        synonyms: ["decrease", "reduce", "lessen"],
        examples: [
          "The pain will diminish over time.",
          "Her interest in the project diminished quickly.",
          "Resources are diminishing rapidly.",
        ],
        wordPr: "کم شدن، کاهش یافتن",
        definitionPr: "کوچکتر یا کمتر شدن",
        synonymsPr: ["کاهش یافتن", "کم شدن", "کاستن"],
        examplesPr: [
          "درد با گذشت زمان کاهش می‌یابد.",
          "علاقه او به پروژه به سرعت کم شد.",
          "منابع به سرعت در حال کاهش هستند.",
        ],
      },
      {
        id: 376,
        pronunciation: "ˈmæksɪməm",
        imageUrl: "",
        word: "maximum",
        definition: "the greatest amount or degree possible",
        synonyms: ["greatest", "highest", "utmost"],
        examples: [
          "The car can reach a maximum speed of 200 km/h.",
          "You should use the maximum amount allowed.",
          "They worked to the maximum of their abilities.",
        ],
        wordPr: "حداکثر، بیشینه",
        definitionPr: "بیشترین مقدار یا درجه ممکن",
        synonymsPr: ["بیشترین", "حداکثر", "بالاترین"],
        examplesPr: [
          "ماشین می‌تواند به سرعت حداکثر ۲۰۰ کیلومتر بر ساعت برسد.",
          "باید بیشترین مقدار مجاز را استفاده کنید.",
          "آن‌ها تا حد توان خود کار کردند.",
        ],
      },
      {
        id: 377,
        pronunciation: "fliː",
        imageUrl: "",
        word: "flee",
        definition: "to run away from danger or trouble",
        synonyms: ["escape", "run away", "bolt"],
        examples: [
          "The villagers fled when the fire started.",
          "He had to flee the country to avoid arrest.",
          "The criminals fled the scene quickly.",
        ],
        wordPr: "فرار کردن",
        definitionPr: "گریختن از خطر یا مشکل",
        synonymsPr: ["فرار کردن", "گریختن", "دور شدن"],
        examplesPr: [
          "اهالی روستا هنگام شروع آتش سوزی فرار کردند.",
          "او برای اجتناب از دستگیری مجبور به فرار از کشور شد.",
          "مجرمان به سرعت محل را ترک کردند.",
        ],
      },
      {
        id: 378,
        pronunciation: "ˈvʌlnərəbl",
        imageUrl: "",
        word: "vulnerable",
        definition: "open to attack or harm; weak",
        synonyms: ["susceptible", "defenseless", "exposed"],
        examples: [
          "Young children are vulnerable to illness.",
          "The village was vulnerable to floods.",
          "He felt vulnerable without his friends.",
        ],
        wordPr: "آسیب‌پذیر",
        definitionPr: "باز برای حمله یا آسیب؛ ضعیف",
        synonymsPr: ["آسیب‌پذیر", "بی‌دفاع", "در معرض"],
        examplesPr: [
          "کودکان کوچک نسبت به بیماری آسیب‌پذیرند.",
          "روستا نسبت به سیل آسیب‌پذیر بود.",
          "او بدون دوستانش احساس آسیب‌پذیری می‌کرد.",
        ],
      },
      {
        id: 379,
        pronunciation: "ˈsɪgnɪfaɪ",
        imageUrl: "",
        word: "signify",
        definition: "to be a sign of; to mean",
        synonyms: ["mean", "indicate", "represent"],
        examples: [
          "Red lights signify danger.",
          "His silence signified agreement.",
          "The symbol signifies peace.",
        ],
        wordPr: "معنی دادن، نشان دادن",
        definitionPr: "علامت دادن یا معنی داشتن",
        synonymsPr: ["به معنی بودن", "نشان دادن", "علامت دادن"],
        examplesPr: [
          "چراغ قرمز نشان دهنده خطر است.",
          "سکوت او به معنی موافقت بود.",
          "این علامت نشانه صلح است.",
        ],
      },
      {
        id: 380,
        pronunciation: "mɪˈθɑːlədʒi",
        imageUrl: "",
        word: "mythology",
        definition: "a collection of myths or traditional stories",
        synonyms: ["legend", "folklore", "myths"],
        examples: [
          "Greek mythology includes stories of gods and heroes.",
          "Many cultures have rich mythologies.",
          "Mythology often explains natural phenomena.",
        ],
        wordPr: "اسطوره‌شناسی، داستان‌های افسانه‌ای",
        definitionPr: "مجموعه‌ای از اسطوره‌ها یا داستان‌های سنتی",
        synonymsPr: ["اسطوره‌ها", "داستان‌های فولکلور", "افسانه‌ها"],
        examplesPr: [
          "اسطوره‌شناسی یونان داستان‌های خدایان و قهرمانان را شامل می‌شود.",
          "فرهنگ‌های زیادی اسطوره‌های غنی دارند.",
          "اسطوره‌ها اغلب پدیده‌های طبیعی را توضیح می‌دهند.",
        ],
      },
      {
        id: 381,
        pronunciation: "prəˈvaɪd",
        imageUrl: "",
        word: "provide",
        definition: "to supply or make available",
        synonyms: ["supply", "offer", "give"],
        examples: [
          "The school provides books for students.",
          "They provided food and shelter for the refugees.",
          "The service provides 24-hour support.",
        ],
        wordPr: "تأمین کردن، فراهم کردن",
        definitionPr: "تأمین یا در دسترس قرار دادن",
        synonymsPr: ["تأمین کردن", "فراهم کردن", "دادن"],
        examplesPr: [
          "مدرسه کتاب برای دانش‌آموزان تأمین می‌کند.",
          "آن‌ها برای پناهندگان غذا و سرپناه فراهم کردند.",
          "این سرویس پشتیبانی ۲۴ ساعته ارائه می‌دهد.",
        ],
      },
      {
        id: 382,
        pronunciation: "ˈkɑːliːɡ",
        imageUrl: "",
        word: "colleague",
        definition: "a person who works with someone else",
        synonyms: ["coworker", "associate", "partner"],
        examples: [
          "She is a colleague from the marketing department.",
          "My colleagues helped me finish the project.",
          "He got along well with his colleagues.",
        ],
        wordPr: "همکار",
        definitionPr: "شخصی که با فرد دیگری کار می‌کند",
        synonymsPr: ["همکار", "همراه کاری", "شریک کاری"],
        examplesPr: [
          "او همکار از بخش بازاریابی است.",
          "همکارانم به من کمک کردند پروژه را تمام کنم.",
          "او با همکارانش خوب کنار می‌آمد.",
        ],
      },
      {
        id: 383,
        pronunciation: "ˈtɔːrmənt",
        imageUrl: "",
        word: "torment",
        definition: "severe physical or mental suffering",
        synonyms: ["agony", "torture", "anguish"],
        examples: [
          "He lived in torment after losing his family.",
          "The prisoner endured terrible torment.",
          "The noise was a torment to the neighbors.",
        ],
        wordPr: "رنج شدید، عذاب",
        definitionPr: "درد جسمی یا روانی شدید",
        synonymsPr: ["رنج", "عذاب", "درد"],
        examplesPr: [
          "او پس از از دست دادن خانواده‌اش در رنج بود.",
          "زندانی عذاب وحشتناکی را تحمل کرد.",
          "صدا برای همسایگان عذاب‌آور بود.",
        ],
      },
      {
        id: 384,
        pronunciation: "ˈlɔɪəlti",
        imageUrl: "",
        word: "loyalty",
        definition: "faithfulness to a person, cause, or duty",
        synonyms: ["faithfulness", "allegiance", "devotion"],
        examples: [
          "Her loyalty to the company is admirable.",
          "Loyalty is important in friendships.",
          "He showed loyalty during difficult times.",
        ],
        wordPr: "وفاداری",
        definitionPr: "پایبندی به یک شخص، علت یا وظیفه",
        synonymsPr: ["وفاداری", "تعهد", "دوستی"],
        examplesPr: [
          "وفاداری او به شرکت قابل تحسین است.",
          "وفاداری در دوستی‌ها مهم است.",
          "او در زمان‌های سخت وفاداری نشان داد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
