export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 241,
        pronunciation: "pliː",
        imageUrl: "",
        word: "plea",
        definition: "an urgent or emotional request",
        synonyms: ["appeal", "request", "petition"],
        examples: [
          "He made a plea for help.",
          "Her plea for mercy was ignored.",
          "The prisoner entered a plea of not guilty.",
        ],
        wordPr: "درخواست، التماس",
        definitionPr: "درخواست فوری یا احساسی برای چیزی",
        synonymsPr: ["تقاضا", "درخواست", "استدعا"],
        examplesPr: [
          "او تقاضای کمک کرد.",
          "درخواست او برای بخشش نادیده گرفته شد.",
          "زندانی ادعای بی‌گناهی کرد.",
        ],
      },
      {
        id: 242,
        pronunciation: "ˈwɪri",
        imageUrl: "",
        word: "weary",
        definition: "physically or mentally tired",
        synonyms: ["tired", "exhausted", "fatigued"],
        examples: [
          "She felt weary after the long journey.",
          "A weary smile appeared on his face.",
          "The workers were weary from the heat.",
        ],
        wordPr: "خسته",
        definitionPr: "خسته به صورت فیزیکی یا ذهنی",
        synonymsPr: ["فرسوده", "بی‌رمق", "کوفته"],
        examplesPr: [
          "او پس از سفر طولانی احساس خستگی کرد.",
          "لبخندی خسته بر چهره‌اش نقش بست.",
          "کارگران از گرما خسته بودند.",
        ],
      },
      {
        id: 243,
        pronunciation: "kəˈlaɪd",
        imageUrl: "",
        word: "collide",
        definition: "to crash into each other with force",
        synonyms: ["crash", "bump", "strike"],
        examples: [
          "Two cars collided on the highway.",
          "The ships collided during the storm.",
          "Their ideas often collide.",
        ],
        wordPr: "برخورد کردن",
        definitionPr: "با شدت به هم خوردن یا تصادف کردن",
        synonymsPr: ["تصادف کردن", "برخورد کردن", "به هم خوردن"],
        examplesPr: [
          "دو ماشین در بزرگراه با هم برخورد کردند.",
          "کشتی‌ها در طوفان به هم برخورد کردند.",
          "ایده‌های آن‌ها اغلب با هم برخورد می‌کند.",
        ],
      },
      {
        id: 244,
        pronunciation: "kənˈfɜːrm",
        imageUrl: "",
        word: "confirm",
        definition: "to prove or show to be true",
        synonyms: ["verify", "prove", "affirm"],
        examples: [
          "The report confirmed their suspicions.",
          "She confirmed the meeting time.",
          "We must confirm the reservation.",
        ],
        wordPr: "تأیید کردن",
        definitionPr: "اثبات درستی یا واقعی بودن چیزی",
        synonymsPr: ["اثبات کردن", "مطمئن ساختن", "پشتیبانی کردن"],
        examplesPr: [
          "گزارش، شک آن‌ها را تأیید کرد.",
          "او زمان جلسه را تأیید کرد.",
          "ما باید رزرو را تأیید کنیم.",
        ],
      },
      {
        id: 245,
        pronunciation: "ˈverɪfaɪ",
        imageUrl: "",
        word: "verify",
        definition: "to make sure something is true or accurate",
        synonyms: ["check", "confirm", "validate"],
        examples: [
          "We need to verify your identity.",
          "The scientist verified the results.",
          "Can you verify the address?",
        ],
        wordPr: "راستی‌آزمایی کردن",
        definitionPr: "بررسی صحت یا درستی چیزی",
        synonymsPr: ["تأیید کردن", "اثبات کردن", "بررسی کردن"],
        examplesPr: [
          "باید هویت شما را بررسی کنیم.",
          "دانشمند نتایج را راستی‌آزمایی کرد.",
          "می‌تونی آدرس رو تأیید کنی؟",
        ],
      },
      {
        id: 246,
        pronunciation: "ænˈtɪsɪpeɪt",
        imageUrl: "",
        word: "anticipate",
        definition: "to expect or look ahead to something",
        synonyms: ["expect", "predict", "foresee"],
        examples: [
          "We anticipate a rise in sales.",
          "She anticipated the question.",
          "The team anticipated a tough game.",
        ],
        wordPr: "پیش‌بینی کردن",
        definitionPr: "انتظار داشتن چیزی در آینده",
        synonymsPr: ["انتظار داشتن", "پیش‌بینی کردن", "حدس زدن"],
        examplesPr: [
          "ما افزایش فروش را پیش‌بینی می‌کنیم.",
          "او این سؤال را پیش‌بینی کرده بود.",
          "تیم انتظار یک بازی سخت را داشت.",
        ],
      },
      {
        id: 247,
        pronunciation: "dəˈlemə",
        imageUrl: "",
        word: "dilemma",
        definition: "a situation requiring a difficult choice",
        synonyms: ["problem", "predicament", "difficulty"],
        examples: [
          "She faced a dilemma about whether to stay or go.",
          "His dilemma was choosing between love and career.",
          "We are in a moral dilemma.",
        ],
        wordPr: "دوراهی، معضل",
        definitionPr: "وضعیتی که در آن باید بین دو انتخاب سخت تصمیم گرفت",
        synonymsPr: ["معضل", "دشواری", "دوراهی"],
        examplesPr: [
          "او در دوراهی ماندن یا رفتن قرار داشت.",
          "دوراهی او، انتخاب بین عشق و شغل بود.",
          "ما در یک معضل اخلاقی هستیم.",
        ],
      },
      {
        id: 248,
        pronunciation: "ˈdiːtʊr",
        imageUrl: "",
        word: "detour",
        definition: "a roundabout way or deviation from the usual route",
        synonyms: ["diversion", "bypass", "alternate route"],
        examples: [
          "We had to take a detour due to road construction.",
          "The sign indicated a detour ahead.",
          "He made a brief detour to visit a friend.",
        ],
        wordPr: "مسیر فرعی، راه انحرافی",
        definitionPr: "تغییر موقتی از مسیر معمول",
        synonymsPr: ["راه فرعی", "انحراف", "تغییر مسیر"],
        examplesPr: [
          "به‌دلیل ساخت‌وساز جاده مجبور شدیم از مسیر فرعی برویم.",
          "تابلو نشان می‌داد که مسیر انحرافی در پیش است.",
          "او مسیرش را کمی تغییر داد تا به دوستی سر بزند.",
        ],
      },
      {
        id: 249,
        pronunciation: "ˈmerɪt",
        imageUrl: "",
        word: "merit",
        definition: "quality of being good or worthy",
        synonyms: ["value", "excellence", "worth"],
        examples: [
          "The proposal has some merit.",
          "He was promoted based on merit.",
          "Let's judge the idea on its own merit.",
        ],
        wordPr: "شایستگی، ارزش",
        definitionPr: "ویژگی خوب یا قابل تحسین بودن",
        synonymsPr: ["لیاقت", "ارزش", "برتری"],
        examplesPr: [
          "این پیشنهاد ارزش‌هایی دارد.",
          "او بر اساس شایستگی ارتقا یافت.",
          "بیایید ایده را بر اساس ارزش ذاتی آن قضاوت کنیم.",
        ],
      },
      {
        id: 250,
        pronunciation: "trænzˈmɪt",
        imageUrl: "",
        word: "transmit",
        definition:
          "to send or pass something from one place or person to another",
        synonyms: ["send", "transfer", "convey"],
        examples: [
          "The radio transmits signals over long distances.",
          "The virus is transmitted through contact.",
          "They transmitted the message via email.",
        ],
        wordPr: "انتقال دادن، ارسال کردن",
        definitionPr: "فرستادن یا منتقل کردن چیزی از جایی به جای دیگر",
        synonymsPr: ["منتقل کردن", "ارسال کردن", "فرستادن"],
        examplesPr: [
          "رادیو سیگنال‌ها را در مسافت‌های طولانی منتقل می‌کند.",
          "ویروس از طریق تماس منتقل می‌شود.",
          "آن‌ها پیام را از طریق ایمیل ارسال کردند.",
        ],
      },
      {
        id: 251,
        pronunciation: "rɪˈliːv",
        imageUrl: "",
        word: "relieve",
        definition: "to ease pain or remove a burden",
        synonyms: ["ease", "alleviate", "soothe"],
        examples: [
          "This medicine will relieve your headache.",
          "He was relieved of his duties.",
          "A nap can relieve stress.",
        ],
        wordPr: "تسکین دادن، کاهش دادن",
        definitionPr: "کاهش درد یا بار روانی",
        synonymsPr: ["آرام کردن", "سبک کردن", "تسکین بخشیدن"],
        examplesPr: [
          "این دارو سردردت را تسکین می‌دهد.",
          "او از وظایفش معاف شد.",
          "یک چرت کوتاه می‌تواند استرس را کاهش دهد.",
        ],
      },
      {
        id: 252,
        pronunciation: "ˈbæfəl",
        imageUrl: "",
        word: "baffle",
        definition: "to confuse or puzzle completely",
        synonyms: ["confuse", "perplex", "bewilder"],
        examples: [
          "The question baffled me.",
          "Her strange behavior baffled everyone.",
          "The instructions completely baffled him.",
        ],
        wordPr: "گیج کردن، سردرگم کردن",
        definitionPr: "کسی را کاملاً گیج یا متحیر کردن",
        synonymsPr: ["مبهوت کردن", "سردرگم کردن", "شگفت‌زده کردن"],
        examplesPr: [
          "این سؤال من را گیج کرد.",
          "رفتار عجیب او همه را متحیر کرد.",
          "دستورالعمل‌ها او را کاملاً سردرگم کرد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
