export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 385,
        pronunciation: "ˌvɑːlənˈtɪr",
        imageUrl: "",
        word: "volunteer",
        definition: "to offer to do something without being asked or paid",
        synonyms: ["offer", "help", "assist"],
        examples: [
          "She volunteered to help with the event.",
          "Many people volunteer at the charity.",
          "He volunteered for the risky mission.",
        ],
        wordPr: "داوطلب شدن",
        definitionPr: "پیشنهاد انجام کاری بدون درخواست یا دستمزد",
        synonymsPr: ["داوطلب شدن", "کمک کردن", "همکاری کردن"],
        examplesPr: [
          "او داوطلب شد تا در برنامه کمک کند.",
          "بسیاری در خیریه داوطلب می‌شوند.",
          "او برای ماموریت خطرناک داوطلب شد.",
        ],
      },
      {
        id: 386,
        pronunciation: "ˈprɛdʒədɪs",
        imageUrl: "",
        word: "prejudice",
        definition: "an unfair feeling of dislike for a group",
        synonyms: ["bias", "discrimination", "intolerance"],
        examples: [
          "Prejudice can lead to unfair treatment.",
          "She faced prejudice because of her background.",
          "We must fight against racial prejudice.",
        ],
        wordPr: "تعصب، پیش‌داوری",
        definitionPr: "احساس ناعادلانه‌ی عدم علاقه به یک گروه",
        synonymsPr: ["تعصب", "تبعیض", "عدم تحمل"],
        examplesPr: [
          "تعصب می‌تواند به رفتار ناعادلانه منجر شود.",
          "او به دلیل پیشینه‌اش با تعصب مواجه شد.",
          "باید با تعصب نژادی مبارزه کنیم.",
        ],
      },
      {
        id: 387,
        pronunciation: "ʃrɪl",
        imageUrl: "",
        word: "shrill",
        definition: "a high-pitched and piercing sound",
        synonyms: ["piercing", "sharp", "high-pitched"],
        examples: [
          "The shrill scream startled everyone.",
          "She has a shrill voice when excited.",
          "The alarm made a shrill noise.",
        ],
        wordPr: "تیز، گوش‌خراش",
        definitionPr: "صدای زیر و گوش‌خراش",
        synonymsPr: ["تیز", "زیر", "گوش‌خراش"],
        examplesPr: [
          "جیغ گوش‌خراش همه را ترساند.",
          "وقتی هیجان‌زده می‌شود صدایش تیز است.",
          "زنگ هشدار صدای گوش‌خراشی داشت.",
        ],
      },
      {
        id: 388,
        pronunciation: "ˈdʒɑːli",
        imageUrl: "",
        word: "jolly",
        definition: "happy and cheerful",
        synonyms: ["cheerful", "merry", "joyful"],
        examples: [
          "They had a jolly time at the party.",
          "He is always in a jolly mood.",
          "The jolly music lifted everyone's spirits.",
        ],
        wordPr: "شاد، خوشحال",
        definitionPr: "خوشحال و شاداب",
        synonymsPr: ["شاد", "خوشحال", "بشاش"],
        examplesPr: [
          "آن‌ها در مهمانی وقت شادی داشتند.",
          "او همیشه خوشحال است.",
          "موسیقی شاد روحیه همه را بالا برد.",
        ],
      },
      {
        id: 389,
        pronunciation: "ˈwɪti",
        imageUrl: "",
        word: "witty",
        definition: "clever and funny",
        synonyms: ["clever", "humorous", "sharp"],
        examples: [
          "She made a witty remark that made everyone laugh.",
          "He is known for his witty jokes.",
          "A witty person can lighten up the mood.",
        ],
        wordPr: "باهوش و شوخ",
        definitionPr: "باهوش و بامزه",
        synonymsPr: ["باهوش", "شوخ", "طنزآمیز"],
        examplesPr: [
          "او حرف باهوشانه‌ای زد که همه را خنداند.",
          "او به خاطر شوخی‌های باهوشش معروف است.",
          "یک فرد باهوش می‌تواند فضا را شاد کند.",
        ],
      },
      {
        id: 390,
        pronunciation: "ˈhɪndər",
        imageUrl: "",
        word: "hinder",
        definition: "to make it difficult for something to happen",
        synonyms: ["obstruct", "delay", "prevent"],
        examples: [
          "Bad weather hindered the rescue operation.",
          "His injury hindered his performance.",
          "Lack of funds hindered the project.",
        ],
        wordPr: "مانع شدن، مختل کردن",
        definitionPr: "دشوار کردن انجام کاری",
        synonymsPr: ["مانع شدن", "مختل کردن", "جلوگیری کردن"],
        examplesPr: [
          "هوای بد عملیات نجات را مختل کرد.",
          "جراحت او عملکردش را مختل کرد.",
          "کمبود بودجه پروژه را مختل کرد.",
        ],
      },
      {
        id: 391,
        pronunciation: "ˈlɛktʃər",
        imageUrl: "",
        word: "lecture",
        definition: "a talk given to teach or inform",
        synonyms: ["speech", "lesson", "talk"],
        examples: [
          "The professor gave a lecture on history.",
          "We attended a lecture about climate change.",
          "She lectures at the university.",
        ],
        wordPr: "سخنرانی، درس دادن",
        definitionPr: "صحبت برای آموزش یا اطلاع‌رسانی",
        synonymsPr: ["سخنرانی", "درس", "صحبت"],
        examplesPr: [
          "استاد سخنرانی درباره تاریخ داد.",
          "ما در سخنرانی درباره تغییرات اقلیمی شرکت کردیم.",
          "او در دانشگاه درس می‌دهد.",
        ],
      },
      {
        id: 392,
        pronunciation: "əˈbjuːs",
        imageUrl: "",
        word: "abuse",
        definition: "to use wrongly or harmfully",
        synonyms: ["mistreat", "harm", "misuse"],
        examples: [
          "The child was abused by a caretaker.",
          "He abused his power to get what he wanted.",
          "Abuse of drugs is a serious problem.",
        ],
        wordPr: "سوء استفاده کردن، آزار دادن",
        definitionPr: "استفاده نادرست یا آسیب رساندن",
        synonymsPr: ["سوء استفاده کردن", "آزار دادن", "بدرفتاری"],
        examplesPr: [
          "کودک توسط مراقب آزار دید.",
          "او برای رسیدن به خواسته‌اش سوء استفاده کرد.",
          "سوء استفاده از مواد مخدر مشکل جدی است.",
        ],
      },
      {
        id: 393,
        pronunciation: "ˈmʌmbəl",
        imageUrl: "",
        word: "mumble",
        definition: "to speak quietly and unclearly",
        synonyms: ["mutter", "whisper", "murmur"],
        examples: [
          "He mumbled his answer softly.",
          "She mumbled something under her breath.",
          "Stop mumbling and speak clearly.",
        ],
        wordPr: "زیر لب گفتن، من من کردن",
        definitionPr: "صحبت کردن آرام و نامفهوم",
        synonymsPr: ["زیر لب گفتن", "من من کردن", "پچ پچ کردن"],
        examplesPr: [
          "او جوابش را آرام گفت.",
          "او چیزی زیر لب گفت.",
          "دیگر من من نکن و واضح صحبت کن.",
        ],
      },
      {
        id: 394,
        pronunciation: "mjuːt",
        imageUrl: "",
        word: "mute",
        definition: "unable to speak or silent",
        synonyms: ["silent", "dumb", "speechless"],
        examples: [
          "The mute boy used sign language to communicate.",
          "The TV was on mute during the commercial.",
          "He was mute with shock.",
        ],
        wordPr: "لال، بی‌صدا",
        definitionPr: "ناتوان در صحبت کردن یا بی‌صدا",
        synonymsPr: ["بی‌صدا", "لال", "ساکت"],
        examplesPr: [
          "پسر لال برای ارتباط از زبان اشاره استفاده می‌کرد.",
          "تلویزیون هنگام تبلیغات بی‌صدا بود.",
          "او از شدت شوک ساکت شده بود.",
        ],
      },
      {
        id: 395,
        pronunciation: "wæd",
        imageUrl: "",
        word: "wad",
        definition: "a small, soft mass or bundle of something",
        synonyms: ["ball", "bundle", "mass"],
        examples: [
          "He pulled out a wad of cash from his pocket.",
          "She stuffed a wad of paper into her bag.",
          "The wad of cotton was used for cleaning.",
        ],
        wordPr: "کپه، دسته",
        definitionPr: "توده کوچک و نرم یا دسته‌ای از چیزی",
        synonymsPr: ["کپه", "دسته", "توده"],
        examplesPr: [
          "او یک دسته پول نقد از جیبش بیرون آورد.",
          "او یک دسته کاغذ را در کیفش گذاشت.",
          "کپه پنبه برای تمیز کردن استفاده شد.",
        ],
      },
      {
        id: 396,
        pronunciation: "rɪˈteɪn",
        imageUrl: "",
        word: "retain",
        definition: "to keep or continue to have",
        synonyms: ["keep", "hold", "preserve"],
        examples: [
          "She retained her position despite the changes.",
          "The soil retains water well.",
          "Try to retain what you learn.",
        ],
        wordPr: "نگه داشتن، حفظ کردن",
        definitionPr: "نگه داشتن یا ادامه داشتن",
        synonymsPr: ["نگه داشتن", "حفظ کردن", "نگهداری کردن"],
        examplesPr: [
          "او موقعیت خود را با وجود تغییرات حفظ کرد.",
          "خاک خوب آب را نگه می‌دارد.",
          "سعی کن آنچه یاد می‌گیری حفظ کنی.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
