export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 289,
        pronunciation: "ˈɑːrkɪtekt",
        imageUrl: "",
        word: "architect",
        definition: "a person who designs buildings",
        synonyms: ["designer", "planner", "builder"],
        examples: [
          "The architect designed a beautiful new library.",
          "We hired an architect to plan our house.",
          "Famous architects can earn a lot of money.",
        ],
        wordPr: "معمار",
        definitionPr: "فردی که ساختمان‌ها را طراحی می‌کند",
        synonymsPr: ["طراح ساختمان", "نقشه‌کش", "مهندس معماری"],
        examplesPr: [
          "معمار یک کتابخانه جدید و زیبا طراحی کرد.",
          "ما یک معمار برای طراحی خانه استخدام کردیم.",
          "معماران معروف می‌توانند درآمد بالایی داشته باشند.",
        ],
      },
      {
        id: 290,
        pronunciation: "ˈmætrɪˌmoʊni",
        imageUrl: "",
        word: "matrimony",
        definition: "the state of being married",
        synonyms: ["marriage", "wedlock", "union"],
        examples: [
          "They were united in holy matrimony.",
          "Matrimony is a serious commitment.",
          "Many cultures celebrate matrimony with ceremonies.",
        ],
        wordPr: "ازدواج، زناشویی",
        definitionPr: "وضعیت ازدواج یا پیوند زناشویی",
        synonymsPr: ["ازدواج", "زناشویی", "پیوند رسمی"],
        examplesPr: [
          "آن‌ها در یک پیوند مقدس ازدواج کردند.",
          "ازدواج یک تعهد جدی است.",
          "بسیاری از فرهنگ‌ها ازدواج را با مراسم جشن می‌گیرند.",
        ],
      },
      {
        id: 291,
        pronunciation: "ˈbæɡɪdʒ",
        imageUrl: "",
        word: "baggage",
        definition: "suitcases and bags used for traveling",
        synonyms: ["luggage", "bags", "belongings"],
        examples: [
          "She packed her baggage and left.",
          "You can check your baggage at the counter.",
          "He lost all his baggage at the airport.",
        ],
        wordPr: "چمدان، بار سفر",
        definitionPr: "چمدان‌ها و وسایلی که برای سفر استفاده می‌شوند",
        synonymsPr: ["چمدان", "بار", "اثاثیه سفر"],
        examplesPr: [
          "او چمدان‌هایش را بست و رفت.",
          "می‌توانید چمدان‌تان را در باجه تحویل دهید.",
          "او تمام چمدان‌هایش را در فرودگاه گم کرد.",
        ],
      },
      {
        id: 292,
        pronunciation: "ˈskwɑːndər",
        imageUrl: "",
        word: "squander",
        definition: "to waste something in a foolish way",
        synonyms: ["waste", "spend carelessly", "throw away"],
        examples: [
          "He squandered all his money on gambling.",
          "Don’t squander your time.",
          "She squandered a great opportunity.",
        ],
        wordPr: "هدر دادن، اسراف کردن",
        definitionPr: "خرج یا تلف کردن چیزی به شکل نادانسته یا بیهوده",
        synonymsPr: ["تلف کردن", "اسراف کردن", "ولخرجی کردن"],
        examplesPr: [
          "او تمام پولش را در قمار هدر داد.",
          "وقتت را هدر نده.",
          "او یک فرصت بزرگ را از دست داد.",
        ],
      },
      {
        id: 293,
        pronunciation: "əˈbrɔːd",
        imageUrl: "",
        word: "abroad",
        definition: "in or to a foreign country",
        synonyms: ["overseas", "internationally", "outside the country"],
        examples: [
          "She studied abroad for two years.",
          "Many students go abroad to learn English.",
          "They traveled abroad last summer.",
        ],
        wordPr: "خارج از کشور",
        definitionPr: "در یا به کشوری خارجی",
        synonymsPr: ["خارج از کشور", "برون‌مرزی", "بین‌المللی"],
        examplesPr: [
          "او دو سال در خارج از کشور تحصیل کرد.",
          "بسیاری از دانش‌آموزان برای یادگیری انگلیسی به خارج می‌روند.",
          "آن‌ها تابستان گذشته به خارج سفر کردند.",
        ],
      },
      {
        id: 294,
        pronunciation: "ˈfjuːdʒətɪv",
        imageUrl: "",
        word: "fugitive",
        definition: "someone who is running away or escaping",
        synonyms: ["escapee", "runaway", "outlaw"],
        examples: [
          "The fugitive was caught by the police.",
          "He lived as a fugitive for years.",
          "She is a fugitive from justice.",
        ],
        wordPr: "فراری، گریزان",
        definitionPr: "کسی که از قانون یا خطر فرار می‌کند",
        synonymsPr: ["فراری", "گریزان", "متواری"],
        examplesPr: [
          "فراری توسط پلیس دستگیر شد.",
          "او سال‌ها به عنوان یک فراری زندگی کرد.",
          "او از عدالت فراری است.",
        ],
      },
      {
        id: 295,
        pronunciation: "kəˈlæməti",
        imageUrl: "",
        word: "calamity",
        definition: "a great misfortune or disaster",
        synonyms: ["disaster", "catastrophe", "tragedy"],
        examples: [
          "The earthquake was a major calamity.",
          "Losing his job was a calamity for him.",
          "Floods and other calamities affect many people.",
        ],
        wordPr: "فاجعه، مصیبت",
        definitionPr: "بدبختی یا حادثه بسیار بد و ناگوار",
        synonymsPr: ["فاجعه", "حادثه ناگوار", "مصیبت"],
        examplesPr: [
          "زلزله یک فاجعه بزرگ بود.",
          "از دست دادن شغل برای او یک مصیبت بود.",
          "سیل و سایر فجایع افراد زیادی را تحت تأثیر قرار می‌دهند.",
        ],
      },
      {
        id: 296,
        pronunciation: "ˈpɔːpər",
        imageUrl: "",
        word: "pauper",
        definition: "a very poor person",
        synonyms: ["beggar", "poor person", "destitute"],
        examples: [
          "He died a pauper.",
          "The story is about a prince and a pauper.",
          "She helped the pauper with food and clothes.",
        ],
        wordPr: "فقیر، گدا",
        definitionPr: "فردی که بسیار فقیر است",
        synonymsPr: ["فقیر", "محتاج", "گدا"],
        examplesPr: [
          "او فقیرانه درگذشت.",
          "داستان درباره شاهزاده و یک فقیر است.",
          "او به آن فقیر غذا و لباس داد.",
        ],
      },
      {
        id: 297,
        pronunciation: "ˈɛnvi",
        imageUrl: "",
        word: "envy",
        definition: "a feeling of wanting what someone else has",
        synonyms: ["jealousy", "resentment", "covetousness"],
        examples: [
          "He looked at her with envy.",
          "Envy can destroy friendships.",
          "I don't envy his situation.",
        ],
        wordPr: "حسادت، غبطه",
        definitionPr: "احساس آرزوی داشتن چیزی که دیگران دارند",
        synonymsPr: ["حسادت", "رشک", "غبطه"],
        examplesPr: [
          "با حسادت به او نگاه کرد.",
          "حسادت می‌تواند دوستی‌ها را نابود کند.",
          "من به وضعیت او حسادت نمی‌کنم.",
        ],
      },
      {
        id: 298,
        pronunciation: "kəˈlæps",
        imageUrl: "",
        word: "collapse",
        definition: "to fall down or fail suddenly",
        synonyms: ["fall", "crumble", "break down"],
        examples: [
          "The building collapsed after the fire.",
          "She collapsed from exhaustion.",
          "The company collapsed due to poor management.",
        ],
        wordPr: "فروریختن، سقوط کردن",
        definitionPr: "سقوط یا نابودی ناگهانی",
        synonymsPr: ["سقوط کردن", "فروپاشیدن", "از هم پاشیدن"],
        examplesPr: [
          "ساختمان بعد از آتش‌سوزی فرو ریخت.",
          "او از خستگی مفرط از حال رفت.",
          "شرکت به‌دلیل مدیریت ضعیف سقوط کرد.",
        ],
      },
      {
        id: 299,
        pronunciation: "ˈprɑːsɪˌkjuːt",
        imageUrl: "",
        word: "prosecute",
        definition: "to take legal action against someone",
        synonyms: ["sue", "bring to court", "accuse formally"],
        examples: [
          "He was prosecuted for theft.",
          "The company was prosecuted for polluting the river.",
          "They decided not to prosecute.",
        ],
        wordPr: "پیگرد قانونی کردن، تحت تعقیب قرار دادن",
        definitionPr: "اقدام قانونی علیه کسی به دلیل جرم",
        synonymsPr: ["تعقیب قضایی کردن", "شکایت کردن", "دادگاهی کردن"],
        examplesPr: [
          "او به دلیل دزدی تحت پیگرد قرار گرفت.",
          "شرکت به خاطر آلوده کردن رودخانه تحت تعقیب بود.",
          "آن‌ها تصمیم گرفتند پیگرد نکنند.",
        ],
      },
      {
        id: 300,
        pronunciation: "ˈbɪɡəmi",
        imageUrl: "",
        word: "bigamy",
        definition:
          "the crime of marrying someone while already married to another",
        synonyms: ["polygamy (illegal form)", "double marriage"],
        examples: [
          "He was arrested for bigamy.",
          "Bigamy is illegal in most countries.",
          "She didn’t know he had committed bigamy.",
        ],
        wordPr: "چند همسری (غیرقانونی)، دو همسری",
        definitionPr:
          "ازدواج با شخصی در حالی که هنوز با فرد دیگری در ازدواج قانونی هستید",
        synonymsPr: ["چند همسری غیرقانونی", "دو همسری"],
        examplesPr: [
          "او به جرم دو همسری دستگیر شد.",
          "چند همسری در بیشتر کشورها غیرقانونی است.",
          "او نمی‌دانست که شوهرش دو همسری کرده است.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
