export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 49,
        pronunciation: "trəˈdɪʃən",
        imageUrl: "",
        word: "tradition",
        definition: "custom that has been handed down",
        synonyms: ["custom", "heritage"],
        examples: [
          "The family tradition was to have a big dinner on New Year's Eve.",
          "It is a tradition to shake hands when meeting someone.",
          "Many traditions are passed from generation to generation.",
        ],
        wordPr: "سنت",
        definitionPr: "رسم یا عادتی که از گذشته منتقل شده است",
        synonymsPr: ["سنت", "رسم"],
        examplesPr: [
          "سنت خانواده این بود که شب سال نو شام مفصلی بخورند.",
          "دست دادن هنگام ملاقات با کسی یک سنت است.",
          "بسیاری از سنت‌ها از نسلی به نسل دیگر منتقل می‌شوند.",
        ],
      },
      {
        id: 50,
        pronunciation: "ˈrʊrəl",
        imageUrl: "",
        word: "rural",
        definition: "in the country",
        synonyms: ["countryside", "agricultural"],
        examples: [
          "Rural areas often have less access to hospitals.",
          "He grew up in a rural village.",
          "Many people prefer rural life to city life.",
        ],
        wordPr: "روستایی",
        definitionPr: "مربوط به روستا یا خارج از شهر",
        synonymsPr: ["روستایی", "کشاورزی"],
        examplesPr: [
          "مناطق روستایی اغلب دسترسی کمتری به بیمارستان دارند.",
          "او در یک روستای کوچک بزرگ شد.",
          "بسیاری از مردم زندگی روستایی را به زندگی شهری ترجیح می‌دهند.",
        ],
      },
      {
        id: 51,
        pronunciation: "ˈbɜːrdn",
        imageUrl: "",
        word: "burden",
        definition: "what is carried; a load",
        synonyms: ["load", "weight"],
        examples: [
          "The burden of responsibility was too much for him.",
          "She carried the burden of caring for her family.",
          "Debt can be a heavy burden.",
        ],
        wordPr: "بار، مسئولیت",
        definitionPr: "چیزی که حمل می‌شود؛ بار یا مسئولیت",
        synonymsPr: ["بار", "مسئولیت"],
        examplesPr: [
          "بار مسئولیت برای او خیلی زیاد بود.",
          "او بار مراقبت از خانواده‌اش را به دوش می‌کشید.",
          "بدهی می‌تواند بار سنگینی باشد.",
        ],
      },
      {
        id: 52,
        pronunciation: "ˈkæmpəs",
        imageUrl: "",
        word: "campus",
        definition: "grounds of a college, university, or school",
        synonyms: ["school grounds", "university grounds"],
        examples: [
          "The students gathered on the campus for the festival.",
          "There are many trees on the university campus.",
          "The new library is located on the north side of the campus.",
        ],
        wordPr: "محوطه دانشگاه",
        definitionPr: "محوطه یا زمین دانشگاه یا مدرسه",
        synonymsPr: ["محوطه دانشگاه", "محوطه مدرسه"],
        examplesPr: [
          "دانشجویان برای جشنواره در محوطه دانشگاه جمع شدند.",
          "در محوطه دانشگاه درختان زیادی وجود دارد.",
          "کتابخانه جدید در سمت شمالی محوطه دانشگاه قرار دارد.",
        ],
      },
      {
        id: 53,
        pronunciation: "məˈdʒɔːrəti",
        imageUrl: "",
        word: "majority",
        definition: "the larger number; greater part; more than half",
        synonyms: ["most", "greater part"],
        examples: [
          "The majority of people voted for the new law.",
          "A majority of the class passed the exam.",
          "The majority was in favor of the proposal.",
        ],
        wordPr: "اکثریت",
        definitionPr: "بخش بزرگ‌تر؛ بیش از نصف",
        synonymsPr: ["اکثریت", "بیشتر"],
        examplesPr: [
          "اکثریت مردم به قانون جدید رأی دادند.",
          "اکثریت کلاس در امتحان قبول شدند.",
          "اکثریت با این پیشنهاد موافق بودند.",
        ],
      },
      {
        id: 54,
        pronunciation: "əˈsɛmbl",
        imageUrl: "",
        word: "assemble",
        definition: "gather together; bring together",
        synonyms: ["gather", "collect"],
        examples: [
          "The students assembled in the hall.",
          "We need to assemble the parts before starting.",
          "A crowd assembled outside the building.",
        ],
        wordPr: "جمع شدن، گردآوردن",
        definitionPr: "دور هم جمع شدن یا جمع‌آوری کردن",
        synonymsPr: ["جمع شدن", "گردآوردن"],
        examplesPr: [
          "دانش‌آموزان در سالن جمع شدند.",
          "باید قطعات را قبل از شروع جمع کنیم.",
          "جمعیتی بیرون ساختمان جمع شد.",
        ],
      },
      {
        id: 55,
        pronunciation: "ɪkˈsplɔːr",
        imageUrl: "",
        word: "explore",
        definition: "go over carefully; look into closely; examine",
        synonyms: ["investigate", "examine"],
        examples: [
          "They explored the cave for hours.",
          "Scientists are exploring new ways to treat disease.",
          "We want to explore the city during our trip.",
        ],
        wordPr: "کاوش کردن، بررسی کردن",
        definitionPr: "بررسی یا جستجو کردن با دقت",
        synonymsPr: ["کاوش کردن", "بررسی کردن"],
        examplesPr: [
          "آنها ساعت‌ها غار را کاوش کردند.",
          "دانشمندان در حال بررسی روش‌های جدید درمان بیماری هستند.",
          "ما می‌خواهیم در سفرمان شهر را کاوش کنیم.",
        ],
      },
      {
        id: 56,
        pronunciation: "ˈtɒpɪk",
        imageUrl: "",
        word: "topic",
        definition: "subject that people think, write, or talk about",
        synonyms: ["subject", "theme"],
        examples: [
          "The topic of the lecture was climate change.",
          "Let's change the topic.",
          "This is a popular topic among students.",
        ],
        wordPr: "موضوع",
        definitionPr: "چیزی که درباره آن فکر یا صحبت می‌شود",
        synonymsPr: ["موضوع", "بحث"],
        examplesPr: [
          "موضوع سخنرانی تغییرات آب و هوا بود.",
          "بیایید موضوع را عوض کنیم.",
          "این موضوع بین دانشجویان محبوب است.",
        ],
      },
      {
        id: 57,
        pronunciation: "dɪˈbeɪt",
        imageUrl: "",
        word: "debate",
        definition:
          "a discussion in which reasons for and against something are brought out",
        synonyms: ["discussion", "argument"],
        examples: [
          "There was a debate about the new policy.",
          "The candidates debated for two hours.",
          "We had a lively debate in class.",
        ],
        wordPr: "بحث، مناظره",
        definitionPr: "بحثی که در آن دلایل موافق و مخالف بیان می‌شود",
        synonymsPr: ["بحث", "مناظره"],
        examplesPr: [
          "درباره سیاست جدید بحثی صورت گرفت.",
          "نامزدها دو ساعت مناظره کردند.",
          "در کلاس بحث پرشوری داشتیم.",
        ],
      },
      {
        id: 58,
        pronunciation: "ɪˈveɪd",
        imageUrl: "",
        word: "evade",
        definition: "get away from by trickery or cleverness",
        synonyms: ["avoid", "escape"],
        examples: [
          "He tried to evade paying taxes.",
          "She evaded the question.",
          "The thief evaded the police.",
        ],
        wordPr: "طفره رفتن، فرار کردن",
        definitionPr: "فرار کردن یا دوری کردن با زیرکی",
        synonymsPr: ["فرار کردن", "طفره رفتن"],
        examplesPr: [
          "او سعی کرد از پرداخت مالیات طفره برود.",
          "او از پاسخ به سؤال طفره رفت.",
          "دزد از دست پلیس فرار کرد.",
        ],
      },
      {
        id: 59,
        pronunciation: "proʊb",
        imageUrl: "",
        word: "probe",
        definition: "search into; examine thoroughly; investigate",
        synonyms: ["investigate", "examine"],
        examples: [
          "The police probed the crime.",
          "Scientists probed the ocean depths.",
          "The committee will probe the issue.",
        ],
        wordPr: "بررسی کردن، کاوش کردن",
        definitionPr: "بررسی یا جستجو کردن عمیق",
        synonymsPr: ["بررسی کردن", "کاوش کردن"],
        examplesPr: [
          "پلیس جرم را بررسی کرد.",
          "دانشمندان اعماق اقیانوس را کاوش کردند.",
          "کمیته موضوع را بررسی خواهد کرد.",
        ],
      },
      {
        id: 60,
        pronunciation: "rɪˈfɔːrm",
        imageUrl: "",
        word: "reform",
        definition: "make better; improve by removing faults",
        synonyms: ["improve", "correct"],
        examples: [
          "The government plans to reform the tax system.",
          "He promised to reform his bad habits.",
          "The school was reformed after the scandal.",
        ],
        wordPr: "اصلاح کردن",
        definitionPr: "بهتر کردن؛ اصلاح با رفع ایرادات",
        synonymsPr: ["اصلاح کردن", "بهبود دادن"],
        examplesPr: [
          "دولت قصد دارد سیستم مالیاتی را اصلاح کند.",
          "او قول داد عادات بدش را اصلاح کند.",
          "مدرسه پس از رسوایی اصلاح شد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
