export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 468,
        pronunciation: "ˌepɪˈdemɪk",
        imageUrl: "",
        word: "epidemic",
        definition:
          "a sudden increase in the number of cases of a disease in an area",
        synonyms: ["outbreak", "plague", "spread"],
        examples: [
          "The flu epidemic affected thousands of people.",
          "Doctors are trying to control the epidemic.",
          "There was an epidemic of measles in the region.",
        ],
        wordPr: "همه‌گیری، شیوع بیماری",
        definitionPr: "افزایش ناگهانی تعداد موارد بیماری در یک ناحیه",
        synonymsPr: ["شیوع", "همه‌گیری", "اپیدمی"],
        examplesPr: [
          "همه‌گیری آنفولانزا هزاران نفر را تحت تأثیر قرار داد.",
          "پزشکان در تلاش برای کنترل این اپیدمی هستند.",
          "در آن منطقه شیوع سرخک رخ داد.",
        ],
      },
      {
        id: 469,
        pronunciation: "əʊˈbiːsɪti",
        imageUrl: "",
        word: "obesity",
        definition: "the condition of being extremely overweight",
        synonyms: ["overweight", "fatness", "corpulence"],
        examples: [
          "Obesity increases the risk of heart disease.",
          "Childhood obesity is becoming more common.",
          "A poor diet can lead to obesity.",
        ],
        wordPr: "چاقی مفرط",
        definitionPr: "وضعیتی که در آن فرد به شدت اضافه وزن دارد",
        synonymsPr: ["چاقی", "اضافه وزن", "پُری بیش از حد"],
        examplesPr: [
          "چاقی خطر ابتلا به بیماری قلبی را افزایش می‌دهد.",
          "چاقی در کودکان در حال رایج شدن است.",
          "رژیم غذایی ناسالم می‌تواند منجر به چاقی شود.",
        ],
      },
      {
        id: 470,
        pronunciation: "ˈmæɡnɪfaɪ",
        imageUrl: "",
        word: "magnify",
        definition: "to make something appear larger or more important",
        synonyms: ["enlarge", "amplify", "exaggerate"],
        examples: [
          "A microscope magnifies tiny objects.",
          "He tends to magnify his problems.",
          "The glass magnified the image.",
        ],
        wordPr: "بزرگ‌نمایی کردن، اغراق کردن",
        definitionPr: "بزرگتر یا مهم‌تر جلوه دادن چیزی",
        synonymsPr: ["بزرگ کردن", "اغراق کردن", "تقویت کردن"],
        examplesPr: [
          "میکروسکوپ اشیای کوچک را بزرگ‌نمایی می‌کند.",
          "او تمایل دارد مشکلاتش را بزرگ جلوه دهد.",
          "شیشه تصویر را بزرگ کرد.",
        ],
      },
      {
        id: 471,
        pronunciation: "ˈkaɪərəʊˌpræktər",
        imageUrl: "",
        word: "chiropractor",
        definition: "a person who treats back and neck pain by pressing joints",
        synonyms: ["spinal therapist", "manual therapist"],
        examples: [
          "She visited a chiropractor for her back pain.",
          "The chiropractor adjusted his spine.",
          "Many people see chiropractors for posture issues.",
        ],
        wordPr: "کایروپراکتور، متخصص درمان ستون فقرات",
        definitionPr:
          "فردی که دردهای کمر و گردن را با فشار بر مفاصل درمان می‌کند",
        synonymsPr: ["درمانگر ستون فقرات", "متخصص تنظیم مفاصل"],
        examplesPr: [
          "او برای درد کمرش به یک کایروپراکتور مراجعه کرد.",
          "کایروپراکتور ستون فقرات او را تنظیم کرد.",
          "بسیاری از افراد برای مشکلات وضعیت بدنی به کایروپراکتور مراجعه می‌کنند.",
        ],
      },
      {
        id: 472,
        pronunciation: "ˈɒbstəkl",
        imageUrl: "",
        word: "obstacle",
        definition: "something that makes it difficult to achieve something",
        synonyms: ["barrier", "hindrance", "block"],
        examples: [
          "Fear is the biggest obstacle to success.",
          "They faced many obstacles on their way.",
          "Poor communication can be an obstacle to progress.",
        ],
        wordPr: "مانع",
        definitionPr: "چیزی که رسیدن به هدف را دشوار می‌کند",
        synonymsPr: ["مانع", "سد", "بازدارنده"],
        examplesPr: [
          "ترس بزرگ‌ترین مانع برای موفقیت است.",
          "آن‌ها با موانع زیادی در مسیرشان روبرو شدند.",
          "ارتباط ضعیف می‌تواند مانعی برای پیشرفت باشد.",
        ],
      },
      {
        id: 473,
        pronunciation: "ˈvɛntɪleɪt",
        imageUrl: "",
        word: "ventilate",
        definition:
          "to allow fresh air to enter and move through a room or building",
        synonyms: ["air out", "freshen", "aerate"],
        examples: [
          "We need to ventilate this room.",
          "The house was ventilated by large windows.",
          "Proper ventilation prevents mold growth.",
        ],
        wordPr: "تهویه کردن",
        definitionPr: "جریان دادن هوای تازه در یک فضا",
        synonymsPr: ["تهویه کردن", "هوارسانی", "جریان دادن هوا"],
        examplesPr: [
          "باید این اتاق را تهویه کنیم.",
          "خانه از طریق پنجره‌های بزرگ تهویه می‌شد.",
          "تهویه مناسب از رشد کپک جلوگیری می‌کند.",
        ],
      },
      {
        id: 474,
        pronunciation: "ˈdʒɛpədaɪz",
        imageUrl: "",
        word: "jeopardize",
        definition: "to put something at risk",
        synonyms: ["endanger", "risk", "threaten"],
        examples: [
          "He jeopardized his career with that decision.",
          "Don't jeopardize your health with bad habits.",
          "Lying could jeopardize your relationship.",
        ],
        wordPr: "به خطر انداختن",
        definitionPr: "در معرض خطر قرار دادن چیزی",
        synonymsPr: ["به خطر انداختن", "تهدید کردن", "ریسک کردن"],
        examplesPr: [
          "او با آن تصمیم شغلش را به خطر انداخت.",
          "سلامتت را با عادت‌های بد به خطر نینداز.",
          "دروغ گفتن می‌تواند رابطه‌ات را به خطر بیندازد.",
        ],
      },
      {
        id: 475,
        pronunciation: "ˈnɛɡətɪv",
        imageUrl: "",
        word: "negative",
        definition: "not desirable or optimistic; expressing denial or refusal",
        synonyms: ["pessimistic", "adverse", "unfavorable"],
        examples: [
          "She had a negative attitude.",
          "The results were negative.",
          "Negative comments affect morale.",
        ],
        wordPr: "منفی",
        definitionPr: "ناخوشایند یا نشان‌دهنده رد یا انکار",
        synonymsPr: ["بدبینانه", "ناخواسته", "منفی"],
        examplesPr: [
          "او نگرش منفی داشت.",
          "نتایج منفی بودند.",
          "نظرات منفی روحیه را کاهش می‌دهد.",
        ],
      },
      {
        id: 476,
        pronunciation: "ˈpɛnʃən",
        imageUrl: "",
        word: "pension",
        definition:
          "a regular payment made during retirement from an investment fund",
        synonyms: ["retirement pay", "annuity", "benefit"],
        examples: [
          "He receives a monthly pension.",
          "They live on their pensions.",
          "The company offers a good pension plan.",
        ],
        wordPr: "حقوق بازنشستگی",
        definitionPr: "پرداخت منظم در دوران بازنشستگی",
        synonymsPr: ["مستمری", "حقوق بازنشستگی", "حق بازنشستگی"],
        examplesPr: [
          "او حقوق بازنشستگی ماهیانه دریافت می‌کند.",
          "آن‌ها از حقوق بازنشستگی خود زندگی می‌کنند.",
          "شرکت طرح بازنشستگی خوبی ارائه می‌دهد.",
        ],
      },
      {
        id: 477,
        pronunciation: "ˈvaɪtəl",
        imageUrl: "",
        word: "vital",
        definition: "absolutely necessary or essential",
        synonyms: ["essential", "critical", "important"],
        examples: [
          "Oxygen is vital to human life.",
          "It is vital to follow the rules.",
          "He played a vital role in the project.",
        ],
        wordPr: "حیاتی، ضروری",
        definitionPr: "کاملاً ضروری یا اساسی",
        synonymsPr: ["ضروری", "مهم", "حیاتی"],
        examplesPr: [
          "اکسیژن برای زندگی انسان ضروری است.",
          "پیروی از قوانین حیاتی است.",
          "او نقش حیاتی در پروژه داشت.",
        ],
      },
      {
        id: 478,
        pronunciation: "mjuːˈnɪsɪpəl",
        imageUrl: "",
        word: "municipal",
        definition: "relating to a city or town or its governing body",
        synonyms: ["civic", "urban", "public"],
        examples: [
          "Municipal elections will be held next week.",
          "He works in the municipal building.",
          "The municipal government provides services.",
        ],
        wordPr: "شهری، مربوط به شهرداری",
        definitionPr: "مربوط به یک شهر یا ارگان اداره‌کننده آن",
        synonymsPr: ["شهری", "مدنی", "عمومی"],
        examplesPr: [
          "انتخابات شهری هفته آینده برگزار می‌شود.",
          "او در ساختمان شهرداری کار می‌کند.",
          "دولت شهری خدماتی ارائه می‌دهد.",
        ],
      },
      {
        id: 479,
        pronunciation: "ˈɔːrəl",
        imageUrl: "",
        word: "oral",
        definition: "spoken rather than written; relating to the mouth",
        synonyms: ["spoken", "verbal", "vocal"],
        examples: [
          "She gave an oral presentation.",
          "Oral hygiene is important.",
          "The exam had an oral section.",
        ],
        wordPr: "شفاهی، دهانی",
        definitionPr: "گفتاری و نه نوشتاری؛ مربوط به دهان",
        synonymsPr: ["گفتاری", "زبانی", "بیانی"],
        examplesPr: [
          "او یک ارائه شفاهی داشت.",
          "بهداشت دهان اهمیت دارد.",
          "آزمون بخش شفاهی داشت.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
