export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 397,
        pronunciation: "prɪˈsiːd",
        imageUrl: "",
        word: "precede",
        definition: "to come before something in time or order",
        synonyms: ["come before", "lead", "antecede"],
        examples: [
          "A short introduction precedes the main text.",
          "Thunder often precedes lightning.",
          "The meeting will precede the conference.",
        ],
        wordPr: "قبل از، مقدم بودن",
        definitionPr: "قبل از چیزی آمدن از لحاظ زمان یا ترتیب",
        synonymsPr: ["مقدم بودن", "قبلاً آمدن", "پیش آمدن"],
        examplesPr: [
          "مقدمه کوتاهی قبل از متن اصلی آمده است.",
          "رعد معمولا قبل از برق می‌آید.",
          "جلسه قبل از کنفرانس برگزار می‌شود.",
        ],
      },
      {
        id: 398,
        pronunciation: "ˌædəˈlɛsənt",
        imageUrl: "",
        word: "adolescent",
        definition: "a young person who is developing into an adult",
        synonyms: ["teenager", "youth", "juvenile"],
        examples: [
          "Adolescents face many changes during puberty.",
          "She works with adolescent students.",
          "The adolescent years can be challenging.",
        ],
        wordPr: "نوجوان",
        definitionPr: "فرد جوانی که در حال تبدیل شدن به بزرگسال است",
        synonymsPr: ["نوجوان", "جوان", "کودک بزرگ"],
        examplesPr: [
          "نوجوانان در دوره بلوغ تغییرات زیادی دارند.",
          "او با دانش‌آموزان نوجوان کار می‌کند.",
          "سال‌های نوجوانی ممکن است چالش‌برانگیز باشند.",
        ],
      },
      {
        id: 399,
        pronunciation: "ˌkoʊˌɛdʒʊˈkeɪʃənəl",
        imageUrl: "",
        word: "coeducational",
        definition: "relating to education of both males and females together",
        synonyms: ["mixed-gender", "integrated"],
        examples: [
          "They attend a coeducational school.",
          "Coeducational classes encourage social skills.",
          "Many universities are coeducational.",
        ],
        wordPr: "مختلط (آموزش پسران و دختران با هم)",
        definitionPr: "مربوط به آموزش پسران و دختران با هم",
        synonymsPr: ["مختلط", "آموزش مشترک"],
        examplesPr: [
          "آن‌ها در یک مدرسه مختلط تحصیل می‌کنند.",
          "کلاس‌های مختلط مهارت‌های اجتماعی را تشویق می‌کنند.",
          "بسیاری از دانشگاه‌ها مختلط هستند.",
        ],
      },
      {
        id: 400,
        pronunciation: "ˈrædɪkəl",
        imageUrl: "",
        word: "radical",
        definition: "very new and different from the usual",
        synonyms: ["extreme", "drastic", "fundamental"],
        examples: [
          "They proposed radical changes to the system.",
          "Radical ideas often face resistance.",
          "He supports radical reforms.",
        ],
        wordPr: "اساسی، بنیادی، رادیکال",
        definitionPr: "جدید و متفاوت از حالت معمول",
        synonymsPr: ["بنیادی", "شدید", "اساسی"],
        examplesPr: [
          "آن‌ها تغییرات اساسی در سیستم پیشنهاد کردند.",
          "ایده‌های رادیکال اغلب با مقاومت روبرو می‌شوند.",
          "او از اصلاحات رادیکال حمایت می‌کند.",
        ],
      },
      {
        id: 401,
        pronunciation: "spɑnˈteɪniəs",
        imageUrl: "",
        word: "spontaneous",
        definition: "happening naturally without planning",
        synonyms: ["impulsive", "unplanned", "instinctive"],
        examples: [
          "They had a spontaneous celebration.",
          "Spontaneous laughter filled the room.",
          "Her decision was spontaneous.",
        ],
        wordPr: "خودجوش، بی‌برنامه",
        definitionPr: "به طور طبیعی و بدون برنامه رخ دادن",
        synonymsPr: ["خودجوش", "بی‌برنامه", "غریزی"],
        examplesPr: [
          "آن‌ها جشن خودجوشی برگزار کردند.",
          "خنده‌های بی‌برنامه اتاق را پر کرد.",
          "تصمیم او خودجوش بود.",
        ],
      },
      {
        id: 402,
        pronunciation: "skɪm",
        imageUrl: "",
        word: "skim",
        definition: "to read or glance through quickly",
        synonyms: ["scan", "glance", "browse"],
        examples: [
          "She skimmed the article before class.",
          "I like to skim through books.",
          "He skimmed the report for key points.",
        ],
        wordPr: "مرور سریع، مرور اجمالی",
        definitionPr: "سریع خواندن یا نگاه کردن اجمالی",
        synonymsPr: ["مرور سریع", "نگاه اجمالی", "ورق زدن"],
        examplesPr: [
          "او مقاله را قبل از کلاس مرور کرد.",
          "من دوست دارم کتاب‌ها را سریع مرور کنم.",
          "او گزارش را برای نکات اصلی مرور کرد.",
        ],
      },
      {
        id: 403,
        pronunciation: "ˈvæksɪneɪt",
        imageUrl: "",
        word: "vaccinate",
        definition: "to give a vaccine to prevent disease",
        synonyms: ["inoculate", "immunize", "inject"],
        examples: [
          "Children should be vaccinated against measles.",
          "The government vaccinated millions last year.",
          "He was vaccinated before traveling.",
        ],
        wordPr: "واکسینه کردن",
        definitionPr: "تزریق واکسن برای پیشگیری از بیماری",
        synonymsPr: ["واکسینه کردن", "ایمن سازی", "تزریق واکسن"],
        examplesPr: [
          "کودکان باید در برابر سرخک واکسینه شوند.",
          "دولت سال گذشته میلیون‌ها نفر را واکسینه کرد.",
          "او قبل از سفر واکسینه شد.",
        ],
      },
      {
        id: 404,
        pronunciation: "ʌnˈtaɪdi",
        imageUrl: "",
        word: "untidy",
        definition: "not neat or organized",
        synonyms: ["messy", "disorganized", "cluttered"],
        examples: [
          "His room is untidy and messy.",
          "Don't leave your desk untidy.",
          "The papers were left untidy on the table.",
        ],
        wordPr: "نامرتب، به هم ریخته",
        definitionPr: "نامنظم یا نامرتب بودن",
        synonymsPr: ["نامرتب", "بی‌نظم", "به هم ریخته"],
        examplesPr: [
          "اتاق او نامرتب و به هم ریخته است.",
          "میز خود را نامرتب نگذار.",
          "برگه‌ها به صورت نامرتب روی میز گذاشته شده بود.",
        ],
      },
      {
        id: 405,
        pronunciation: "juːˈtɛnsl",
        imageUrl: "",
        word: "utensil",
        definition: "a tool used in the kitchen or for eating",
        synonyms: ["tool", "implement", "instrument"],
        examples: [
          "Forks and knives are common utensils.",
          "Kitchen utensils should be kept clean.",
          "He bought new utensils for cooking.",
        ],
        wordPr: "ابزار آشپزخانه، وسیله",
        definitionPr: "ابزاری که در آشپزخانه یا برای خوردن استفاده می‌شود",
        synonymsPr: ["ابزار", "وسیله", "دستگاه"],
        examplesPr: [
          "چنگال و چاقو ابزارهای معمول هستند.",
          "ابزار آشپزخانه باید تمیز نگه داشته شوند.",
          "او ابزار جدیدی برای آشپزی خرید.",
        ],
      },
      {
        id: 406,
        pronunciation: "ˈsensətɪv",
        imageUrl: "",
        word: "sensitive",
        definition: "easily affected or influenced by feelings",
        synonyms: ["delicate", "touchy", "responsive"],
        examples: [
          "She is very sensitive to criticism.",
          "The skin on the face is sensitive.",
          "Be sensitive to others' feelings.",
        ],
        wordPr: "حساس",
        definitionPr: "آسان تحت تأثیر احساسات قرار گرفتن",
        synonymsPr: ["حساس", "ظریف", "آسیب‌پذیر"],
        examplesPr: [
          "او به انتقاد بسیار حساس است.",
          "پوست صورت حساس است.",
          "به احساسات دیگران حساس باش.",
        ],
      },
      {
        id: 407,
        pronunciation: "ˈtɛmpərət",
        imageUrl: "",
        word: "temperate",
        definition: "having moderate temperature or behavior",
        synonyms: ["mild", "moderate", "restrained"],
        examples: [
          "The region has a temperate climate.",
          "She has a temperate personality.",
          "Temperate zones have mild weather.",
        ],
        wordPr: "معتدل",
        definitionPr: "دارای دما یا رفتار معتدل",
        synonymsPr: ["معتدل", "ملایم", "محدود"],
        examplesPr: [
          "این منطقه آب و هوای معتدلی دارد.",
          "او شخصیت معتدلی دارد.",
          "منطقه‌های معتدل آب و هوای ملایمی دارند.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
