export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 73,
        pronunciation: "/poʊstˈpoʊn/",
        imageUrl: "",
        word: "postpone",
        definition: "to delay or put off to a later time",
        synonyms: ["delay", "defer", "put off"],
        examples: [
          "We decided to postpone our trip until the weather improves.",
          "The meeting was postponed because of the holiday.",
          "He keeps postponing his visit to the dentist.",
        ],
        wordPr: "به تعویق انداختن",
        definitionPr: "به تأخیر انداختن یا به زمان دیگری موکول کردن",
        synonymsPr: ["تأخیر انداختن", "معوق گذاشتن"],
        examplesPr: [
          "ما تصمیم گرفتیم سفرمان را تا بهبود هوا به تعویق بیندازیم.",
          "جلسه به دلیل تعطیلات به تعویق افتاد.",
          "او مدام مراجعه به دندانپزشک را به تأخیر می‌اندازد.",
        ],
      },
      {
        id: 74,
        pronunciation: "/kənˈsent/",
        imageUrl: "",
        word: "consent",
        definition: "to give permission or agree to something",
        synonyms: ["agree", "approve", "permit"],
        examples: [
          "She finally consented to let me borrow her car.",
          "The patient must give consent before the surgery.",
          "He refused to consent to the new policy.",
        ],
        wordPr: "رضایت دادن",
        definitionPr: "اجازه دادن یا موافقت کردن با چیزی",
        synonymsPr: ["موافقت کردن", "اجازه دادن"],
        examplesPr: [
          "او بالاخره رضایت داد که ماشینش را قرض بگیرم.",
          "بیمار باید قبل از عمل رضایت دهد.",
          "او از موافقت با سیاست جدید خودداری کرد.",
        ],
      },
      {
        id: 75,
        pronunciation: "/ˈmæsɪv/",
        imageUrl: "",
        word: "massive",
        definition: "very large in size, amount, or degree",
        synonyms: ["huge", "enormous", "immense"],
        examples: [
          "The massive oak tree stood in the middle of the field.",
          "They spent a massive amount of money on the project.",
          "The earthquake caused massive destruction.",
        ],
        wordPr: "عظیم",
        definitionPr: "بسیار بزرگ در اندازه، مقدار یا درجه",
        synonymsPr: ["بسیار بزرگ", "غول‌آسا"],
        examplesPr: [
          "درخت بلوط عظیم در وسط زمین ایستاده بود.",
          "آن‌ها مبلغ هنگفتی را برای پروژه خرج کردند.",
          "زلزله خرابی عظیمی به بار آورد.",
        ],
      },
      {
        id: 76,
        pronunciation: "/ˈkæpsjuːl/",
        imageUrl: "",
        word: "capsule",
        definition: "a small container or case, especially for medicine",
        synonyms: ["pill", "tablet", "dose"],
        examples: [
          "Take one capsule every six hours.",
          "The seeds are enclosed in a hard capsule.",
          "The astronaut's capsule landed safely.",
        ],
        wordPr: "کپسول",
        definitionPr: "ظرف یا محفظه کوچک، مخصوصاً برای دارو",
        synonymsPr: ["قرص", "حبوب"],
        examplesPr: [
          "هر شش ساعت یک کپسول مصرف کنید.",
          "دانه‌ها در یک کپسول سخت محصور شده‌اند.",
          "کپسول فضانورد به سلامت فرود آمد.",
        ],
      },
      {
        id: 77,
        pronunciation: "/prɪˈzɜːrv/",
        imageUrl: "",
        word: "preserve",
        definition:
          "to keep something in its original state or in good condition",
        synonyms: ["conserve", "maintain", "protect"],
        examples: [
          "We must preserve our natural resources.",
          "The museum works to preserve ancient artifacts.",
          "He tries to preserve family traditions.",
        ],
        wordPr: "حفظ کردن",
        definitionPr: "نگه داشتن چیزی در حالت اولیه یا در شرایط خوب",
        synonymsPr: ["محافظت کردن", "نگهداری کردن"],
        examplesPr: [
          "ما باید منابع طبیعی‌مان را حفظ کنیم.",
          "موزه برای حفظ آثار باستانی تلاش می‌کند.",
          "او سعی می‌کند سنت‌های خانوادگی را حفظ کند.",
        ],
      },
      {
        id: 78,
        pronunciation: "/dɪˈnaʊns/",
        imageUrl: "",
        word: "denounce",
        definition: "to publicly declare something to be wrong or evil",
        synonyms: ["condemn", "criticize", "censure"],
        examples: [
          "The president denounced the violent protests.",
          "She was denounced as a traitor.",
          "Many leaders denounced the new law.",
        ],
        wordPr: "محکوم کردن",
        definitionPr: "اعلام عمومی چیزی به عنوان اشتباه یا شر",
        synonymsPr: ["سرزنش کردن", "تقبیح کردن"],
        examplesPr: [
          "رئیس‌جمهور اعتراضات خشونت‌آمیز را محکوم کرد.",
          "او به عنوان خائن محکوم شد.",
          "بسیاری از رهبران قانون جدید را محکوم کردند.",
        ],
      },
      {
        id: 79,
        pronunciation: "/juːˈniːk/",
        imageUrl: "",
        word: "unique",
        definition: "being the only one of its kind; unlike anything else",
        synonyms: ["distinctive", "singular", "unparalleled"],
        examples: [
          "Each person's fingerprints are unique.",
          "This painting is unique; there are no others like it.",
          "She has a unique talent for music.",
        ],
        wordPr: "منحصر به فرد",
        definitionPr: "تنها نمونه از نوع خود؛ متفاوت از هر چیز دیگر",
        synonymsPr: ["بی‌نظیر", "متفاوت"],
        examplesPr: [
          "اثر انگشت هر فرد منحصر به فرد است.",
          "این نقاشی منحصر به فرد است؛ هیچ نمونه دیگری مانند آن وجود ندارد.",
          "او استعداد منحصر به فردی در موسیقی دارد.",
        ],
      },
      {
        id: 80,
        pronunciation: "/ˈtɔːrənt/",
        imageUrl: "",
        word: "torrent",
        definition: "a strong and fast-moving stream of water or other liquid",
        synonyms: ["flood", "downpour", "deluge"],
        examples: [
          "The rain turned the streets into torrents.",
          "A torrent of lava flowed from the volcano.",
          "He was swept away by the torrent.",
        ],
        wordPr: "سیل",
        definitionPr: "جریان قوی و سریع آب یا مایع دیگر",
        synonymsPr: ["باران شدید", "طغیان"],
        examplesPr: [
          "باران خیابان‌ها را به سیلاب تبدیل کرد.",
          "جریان گدازه‌ای از آتشفشان سرازیر شد.",
          "او توسط سیلاب با خود برده شد.",
        ],
      },
      {
        id: 81,
        pronunciation: "/rɪˈzent/",
        imageUrl: "",
        word: "resent",
        definition:
          "to feel bitterness or indignation at a circumstance, action, or person",
        synonyms: ["begrudge", "dislike", "take offense"],
        examples: [
          "She resents being treated like a child.",
          "He resents his brother's success.",
          "They resent the new regulations.",
        ],
        wordPr: "رنجیدن",
        definitionPr: "احساس تلخی یا ناراحتی از یک موقعیت، عمل یا شخص",
        synonymsPr: ["کینه داشتن", "ناراحت شدن"],
        examplesPr: [
          "او از این که مانند یک کودک با او رفتار می‌شود رنجیده است.",
          "او از موفقیت برادرش ناراحت است.",
          "آن‌ها از مقررات جدید ناراحتند.",
        ],
      },
      {
        id: 82,
        pronunciation: "/məˈlest/",
        imageUrl: "",
        word: "molest",
        definition: "to disturb or harass someone, especially in a sexual way",
        synonyms: ["harass", "abuse", "bother"],
        examples: [
          "The man was arrested for molesting a child.",
          "She accused her boss of molesting her.",
          "The law protects people from being molested.",
        ],
        wordPr: "آزار دادن",
        definitionPr: "آزار یا مزاحمت کسی، به ویژه از نظر جنسی",
        synonymsPr: ["اذیت کردن", "تحرش کردن"],
        examplesPr: [
          "آن مرد به دلیل آزار یک کودک دستگیر شد.",
          "او رئیس خود را متهم به آزار جنسی کرد.",
          "قانون از افراد در برابر آزار محافظت می‌کند.",
        ],
      },
      {
        id: 83,
        pronunciation: "/ˈɡluːmi/",
        imageUrl: "",
        word: "gloomy",
        definition: "dark or poorly lit; feeling sad or without hope",
        synonyms: ["dark", "depressing", "dreary"],
        examples: [
          "The room was gloomy with only one small window.",
          "He felt gloomy after hearing the bad news.",
          "The weather was gloomy and rainy.",
        ],
        wordPr: "تاریک و افسرده",
        definitionPr: "تاریک یا کم‌نور؛ احساس غم یا ناامیدی",
        synonymsPr: ["غمگین", "اندوهگین"],
        examplesPr: [
          "اتاق با تنها یک پنجره کوچک تاریک بود.",
          "او پس از شنیدن خبر بد احساس افسردگی کرد.",
          "هوا تاریک و بارانی بود.",
        ],
      },
      {
        id: 84,
        pronunciation: "/ˌʌnfɔːrˈsiːn/",
        imageUrl: "",
        word: "unforeseen",
        definition: "not anticipated or predicted",
        synonyms: ["unexpected", "unanticipated", "sudden"],
        examples: [
          "The project was delayed due to unforeseen circumstances.",
          "Unforeseen expenses can ruin a budget.",
          "No one could have prepared for this unforeseen disaster.",
        ],
        wordPr: "پیش‌بینی نشده",
        definitionPr: "غیرمنتظره یا غیرقابل پیش‌بینی",
        synonymsPr: ["ناگهانی", "غیرمنتظره"],
        examplesPr: [
          "پروژه به دلیل شرایط پیش‌بینی نشده به تأخیر افتاد.",
          "هزینه‌های پیش‌بینی نشده می‌توانند بودجه را نابود کنند.",
          "هیچ کس نمی‌توانست برای این فاجعه پیش‌بینی نشده آماده باشد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
