export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 301,
        pronunciation: "ˈpɑːsəbl",
        imageUrl: "",
        word: "possible",
        definition: "able to be done or achieved",
        synonyms: ["feasible", "achievable", "attainable"],
        examples: [
          "It is possible to finish the work by Friday.",
          "Anything is possible if you try hard enough.",
          "We explored every possible option.",
        ],
        wordPr: "ممکن",
        definitionPr: "قابل انجام یا دست‌یافتنی",
        synonymsPr: ["ممکن", "شدنی", "قابل تحقق"],
        examplesPr: [
          "امکان دارد تا جمعه کار را تمام کنیم.",
          "اگر به اندازه کافی تلاش کنید، همه چیز ممکن است.",
          "ما تمام گزینه‌های ممکن را بررسی کردیم.",
        ],
      },
      {
        id: 302,
        pronunciation: "kəmˈpel",
        imageUrl: "",
        word: "compel",
        definition: "to force someone to do something",
        synonyms: ["force", "oblige", "coerce"],
        examples: [
          "The law compels parents to send their children to school.",
          "He was compelled to speak the truth.",
          "They compelled the suspect to confess.",
        ],
        wordPr: "وادار کردن",
        definitionPr: "مجبور کردن کسی به انجام کاری",
        synonymsPr: ["مجبور کردن", "واداشتن", "تحمیل کردن"],
        examplesPr: [
          "قانون والدین را مجبور می‌کند فرزندانشان را به مدرسه بفرستند.",
          "او مجبور شد حقیقت را بگوید.",
          "آن‌ها مظنون را به اعتراف وادار کردند.",
        ],
      },
      {
        id: 303,
        pronunciation: "ˈɔːkwərd",
        imageUrl: "",
        word: "awkward",
        definition: "not graceful; causing difficulty or embarrassment",
        synonyms: ["clumsy", "uncomfortable", "embarrassing"],
        examples: [
          "There was an awkward silence after his comment.",
          "He felt awkward at the party.",
          "She made an awkward attempt to apologize.",
        ],
        wordPr: "ناجور، ناراحت‌کننده",
        definitionPr: "ناهماهنگ یا باعث خجالت و ناراحتی",
        synonymsPr: ["دست‌وپاچلفتی", "ناراحت‌کننده", "خجالت‌آور"],
        examplesPr: [
          "بعد از صحبت او، سکوتی awkward برقرار شد.",
          "او در مهمانی احساس ناراحتی کرد.",
          "او به شکل ناجوری سعی کرد عذرخواهی کند.",
        ],
      },
      {
        id: 304,
        pronunciation: "ˈvɛntʃər",
        imageUrl: "",
        word: "venture",
        definition: "a risky or daring journey or action",
        synonyms: ["undertaking", "adventure", "enterprise"],
        examples: [
          "He ventured into the dark cave.",
          "Starting a new business is a venture.",
          "They ventured out despite the storm.",
        ],
        wordPr: "ماجراجویی، ریسک کردن",
        definitionPr: "اقدام یا سفر خطرناک یا پرریسک",
        synonymsPr: ["ماجراجویی", "ریسک", "پیش‌قدمی"],
        examplesPr: [
          "او وارد غار تاریک شد.",
          "شروع یک کسب‌وکار جدید یک ماجراجویی است.",
          "با وجود طوفان، آن‌ها به بیرون رفتند.",
        ],
      },
      {
        id: 305,
        pronunciation: "ˈɔːsəm",
        imageUrl: "",
        word: "awesome",
        definition: "causing a feeling of wonder or admiration",
        synonyms: ["amazing", "impressive", "awe-inspiring"],
        examples: [
          "The view from the mountain was awesome.",
          "He has an awesome talent for music.",
          "It was an awesome experience.",
        ],
        wordPr: "شگفت‌انگیز، تحسین‌برانگیز",
        definitionPr: "برانگیزنده شگفتی یا تحسین",
        synonymsPr: ["فوق‌العاده", "شگفت‌انگیز", "اعجاب‌آور"],
        examplesPr: [
          "منظره از کوه شگفت‌انگیز بود.",
          "او استعداد فوق‌العاده‌ای در موسیقی دارد.",
          "تجربه‌ای شگفت‌انگیز بود.",
        ],
      },
      {
        id: 306,
        pronunciation: "ɡaɪd",
        imageUrl: "",
        word: "guide",
        definition: "a person who leads or shows the way",
        synonyms: ["leader", "escort", "mentor"],
        examples: [
          "Our guide led us through the jungle.",
          "He works as a tour guide.",
          "The teacher guided the students carefully.",
        ],
        wordPr: "راهنما",
        definitionPr: "فردی که مسیر را نشان می‌دهد یا هدایت می‌کند",
        synonymsPr: ["راهنما", "هدایت‌کننده", "معلم"],
        examplesPr: [
          "راهنمای ما ما را از جنگل عبور داد.",
          "او به‌عنوان راهنمای تور کار می‌کند.",
          "معلم با دقت دانش‌آموزان را هدایت کرد.",
        ],
      },
      {
        id: 307,
        pronunciation: "kwɛntʃ",
        imageUrl: "",
        word: "quench",
        definition: "to satisfy thirst or extinguish something",
        synonyms: ["satisfy", "extinguish", "relieve"],
        examples: [
          "She drank water to quench her thirst.",
          "The firefighters quenched the fire.",
          "Cold lemonade quenched his thirst.",
        ],
        wordPr: "فرونشاندن، رفع کردن (تشنگی یا آتش)",
        definitionPr: "برطرف کردن عطش یا خاموش کردن آتش",
        synonymsPr: ["خاموش کردن", "فرونشاندن", "تسکین دادن"],
        examplesPr: [
          "او برای رفع تشنگی آب نوشید.",
          "آتش‌نشان‌ها آتش را خاموش کردند.",
          "لیموناد سرد تشنگی او را برطرف کرد.",
        ],
      },
      {
        id: 308,
        pronunciation: "bɪˈtreɪ",
        imageUrl: "",
        word: "betray",
        definition: "to be disloyal or reveal secrets",
        synonyms: ["deceive", "double-cross", "expose"],
        examples: [
          "He betrayed his best friend.",
          "She betrayed his trust.",
          "The spy betrayed his country.",
        ],
        wordPr: "خیانت کردن",
        definitionPr: "بی‌وفایی کردن یا افشای راز کسی",
        synonymsPr: ["خیانت کردن", "لو دادن", "افشا کردن"],
        examplesPr: [
          "او به بهترین دوستش خیانت کرد.",
          "او اعتمادش را خیانت کرد.",
          "جاسوس به کشورش خیانت کرد.",
        ],
      },
      {
        id: 309,
        pronunciation: "ˈʌtər",
        imageUrl: "",
        word: "utter",
        definition: "to say or speak something",
        synonyms: ["say", "speak", "express"],
        examples: [
          "He didn’t utter a word.",
          "She uttered a cry of fear.",
          "He uttered his opinion frankly.",
        ],
        wordPr: "بیان کردن، گفتن",
        definitionPr: "چیزی را به زبان آوردن یا گفتن",
        synonymsPr: ["گفتن", "بیان کردن", "اظهار کردن"],
        examplesPr: [
          "او هیچ حرفی نزد.",
          "او فریادی از ترس برآورد.",
          "او نظرش را صریح بیان کرد.",
        ],
      },
      {
        id: 310,
        pronunciation: "ˈpæsɪˌfaɪ",
        imageUrl: "",
        word: "pacify",
        definition: "to make someone calm or peaceful",
        synonyms: ["calm", "soothe", "appease"],
        examples: [
          "The mother pacified the crying baby.",
          "They tried to pacify the angry crowd.",
          "Her words pacified him.",
        ],
        wordPr: "آرام کردن، تسکین دادن",
        definitionPr: "آرام یا ساکت کردن کسی",
        synonymsPr: ["تسکین دادن", "آرام کردن", "دلجویی کردن"],
        examplesPr: [
          "مادر کودک گریان را آرام کرد.",
          "آن‌ها سعی کردند جمعیت خشمگین را آرام کنند.",
          "حرف‌هایش او را آرام کرد.",
        ],
      },
      {
        id: 311,
        pronunciation: "rɪˈspɑːnd",
        imageUrl: "",
        word: "respond",
        definition: "to reply or react to something",
        synonyms: ["reply", "react", "answer"],
        examples: [
          "He didn’t respond to my message.",
          "She responded quickly to the emergency.",
          "How did he respond to the news?",
        ],
        wordPr: "پاسخ دادن، واکنش نشان دادن",
        definitionPr: "پاسخ یا واکنشی به چیزی نشان دادن",
        synonymsPr: ["پاسخ دادن", "جواب دادن", "واکنش نشان دادن"],
        examplesPr: [
          "او به پیام من پاسخ نداد.",
          "او سریع به وضعیت اضطراری واکنش نشان داد.",
          "او چطور به این خبر واکنش نشان داد؟",
        ],
      },
      {
        id: 312,
        pronunciation: "ˈbɛkən",
        imageUrl: "",
        word: "beckon",
        definition: "to signal someone with a gesture to come closer",
        synonyms: ["signal", "gesture", "call"],
        examples: [
          "She beckoned him to come closer.",
          "The teacher beckoned the student to the front.",
          "He beckoned with his hand.",
        ],
        wordPr: "اشاره کردن (دعوت به آمدن)",
        definitionPr: "با حرکت یا اشاره کسی را به سوی خود فرا خواندن",
        synonymsPr: ["اشاره کردن", "فراخواندن", "علامت دادن"],
        examplesPr: [
          "او با اشاره از او خواست نزدیک‌تر بیاید.",
          "معلم با اشاره دانش‌آموز را به جلو فراخواند.",
          "او با دست اشاره کرد.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
