export const revalidate = 60;

export function GET(request: Request) {
  const data = {
    words: [
      {
        id: 253,
        pronunciation: "ˈwɔːrdən",
        imageUrl: "",
        word: "warden",
        definition: "a person responsible for the supervision of a place",
        synonyms: ["guard", "supervisor", "officer"],
        examples: [
          "The prison warden is in charge of the facility.",
          "A park warden helped us find the trail.",
          "The warden checked the cells every hour.",
        ],
        wordPr: "سرپرست، نگهبان",
        definitionPr: "فرد مسئول نظارت یا مراقبت از مکان یا گروهی",
        synonymsPr: ["نگهبان", "سرپرست", "مسئول"],
        examplesPr: [
          "رئیس زندان مسئول اداره تأسیسات است.",
          "نگهبان پارک به ما کمک کرد مسیر را پیدا کنیم.",
          "نگهبان هر ساعت سلول‌ها را بررسی می‌کرد.",
        ],
      },
      {
        id: 254,
        pronunciation: "əkˈnɑːlɪdʒ",
        imageUrl: "",
        word: "acknowledge",
        definition: "to recognize or admit the truth of something",
        synonyms: ["admit", "recognize", "accept"],
        examples: [
          "He acknowledged his mistake.",
          "She refused to acknowledge the truth.",
          "Please acknowledge receipt of the package.",
        ],
        wordPr: "اذعان کردن، تأیید کردن",
        definitionPr: "پذیرفتن یا تصدیق کردن حقیقت چیزی",
        synonymsPr: ["قبول کردن", "تصدیق کردن", "تأیید کردن"],
        examplesPr: [
          "او به اشتباه خود اذعان کرد.",
          "او از پذیرفتن حقیقت خودداری کرد.",
          "لطفاً دریافت بسته را تأیید کنید.",
        ],
      },
      {
        id: 255,
        pronunciation: "ˈdʒʌstɪs",
        imageUrl: "",
        word: "justice",
        definition: "fair treatment according to the law",
        synonyms: ["fairness", "equity", "lawfulness"],
        examples: [
          "They demanded justice for the victim.",
          "Justice must be served.",
          "The justice system needs reform.",
        ],
        wordPr: "عدالت",
        definitionPr: "برخورد عادلانه طبق قانون",
        synonymsPr: ["برابری", "درستی", "عدالت‌محوری"],
        examplesPr: [
          "آن‌ها خواستار عدالت برای قربانی شدند.",
          "عدالت باید اجرا شود.",
          "سیستم قضایی نیاز به اصلاح دارد.",
        ],
      },
      {
        id: 256,
        pronunciation: "dɪˈlɪŋkwənt",
        imageUrl: "",
        word: "delinquent",
        definition: "a young person who breaks the law or behaves badly",
        synonyms: ["offender", "wrongdoer", "lawbreaker"],
        examples: [
          "The police arrested a group of delinquents.",
          "Delinquent behavior is common in troubled youth.",
          "Parents worry about delinquent influences.",
        ],
        wordPr: "بزهکار",
        definitionPr: "فرد (معمولاً نوجوان) که قانون را نقض می‌کند",
        synonymsPr: ["قانون‌شکن", "مجرم نوجوان", "بزه‌کار"],
        examplesPr: [
          "پلیس گروهی از بزهکاران را دستگیر کرد.",
          "رفتار بزهکارانه در جوانان مشکل‌دار رایج است.",
          "والدین نگران تأثیرات بزهکارانه هستند.",
        ],
      },
      {
        id: 257,
        pronunciation: "rɪˈdʒekt",
        imageUrl: "",
        word: "reject",
        definition: "to refuse to accept or believe",
        synonyms: ["refuse", "decline", "dismiss"],
        examples: [
          "She rejected the offer.",
          "He was hurt when they rejected his idea.",
          "The bank rejected his loan application.",
        ],
        wordPr: "رد کردن",
        definitionPr: "نپذیرفتن یا قبول نکردن چیزی",
        synonymsPr: ["قبول نکردن", "نپذیرفتن", "مردود شمردن"],
        examplesPr: [
          "او پیشنهاد را رد کرد.",
          "وقتی ایده‌اش را رد کردند، ناراحت شد.",
          "بانک درخواست وام او را رد کرد.",
        ],
      },
      {
        id: 258,
        pronunciation: "dɪˈpraɪv",
        imageUrl: "",
        word: "deprive",
        definition: "to take something away from someone",
        synonyms: ["deny", "strip", "remove"],
        examples: [
          "The new law deprived them of their rights.",
          "Don’t deprive children of education.",
          "She was deprived of sleep for days.",
        ],
        wordPr: "محروم کردن",
        definitionPr: "گرفتن چیزی از کسی، معمولاً چیز با ارزش یا ضروری",
        synonymsPr: ["بی‌بهره کردن", "محروم کردن", "سلب کردن"],
        examplesPr: [
          "قانون جدید آن‌ها را از حقوقشان محروم کرد.",
          "کودکان را از آموزش محروم نکن.",
          "او روزها از خواب محروم بود.",
        ],
      },
      {
        id: 259,
        pronunciation: "spaʊs",
        imageUrl: "",
        word: "spouse",
        definition: "a husband or wife",
        synonyms: ["partner", "husband", "wife"],
        examples: [
          "Each spouse must sign the agreement.",
          "He introduced me to his spouse.",
          "Spouses should support each other.",
        ],
        wordPr: "همسر",
        definitionPr: "زن یا شوهر",
        synonymsPr: ["شریک زندگی", "زن", "شوهر"],
        examplesPr: [
          "هر دو همسر باید قرارداد را امضا کنند.",
          "او من را به همسرش معرفی کرد.",
          "همسران باید از یکدیگر حمایت کنند.",
        ],
      },
      {
        id: 260,
        pronunciation: "voʊˈkeɪʃən",
        imageUrl: "",
        word: "vocation",
        definition: "a job or career, especially one that is meaningful",
        synonyms: ["occupation", "calling", "profession"],
        examples: [
          "Teaching is more than a job; it's a vocation.",
          "She found her true vocation in nursing.",
          "He treats his art as a vocation.",
        ],
        wordPr: "شغل، حرفه (با علاقه)",
        definitionPr: "شغلی که فرد به آن علاقه یا احساس تعهد دارد",
        synonymsPr: ["حرفه", "دعوت درونی", "وظیفه شغلی"],
        examplesPr: [
          "معلمی فقط یک شغل نیست، بلکه یک حرفه با معناست.",
          "او حرفه واقعی‌اش را در پرستاری یافت.",
          "او با هنر خود مانند یک حرفه برخورد می‌کند.",
        ],
      },
      {
        id: 261,
        pronunciation: "ʌnˈsteɪbl",
        imageUrl: "",
        word: "unstable",
        definition: "not steady or firm; likely to change suddenly",
        synonyms: ["unsteady", "insecure", "volatile"],
        examples: [
          "The chair is unstable.",
          "The political situation remains unstable.",
          "He has an unstable personality.",
        ],
        wordPr: "ناپایدار، بی‌ثبات",
        definitionPr: "چیزی که احتمال تغییر ناگهانی یا عدم پایداری دارد",
        synonymsPr: ["متزلزل", "بی‌ثبات", "نامطمئن"],
        examplesPr: [
          "صندلی ناپایدار است.",
          "وضعیت سیاسی همچنان بی‌ثبات است.",
          "او شخصیت ناپایداری دارد.",
        ],
      },
      {
        id: 262,
        pronunciation: "ˈhɑːmɪsaɪd",
        imageUrl: "",
        word: "homicide",
        definition: "the killing of one person by another",
        synonyms: ["murder", "manslaughter", "killing"],
        examples: [
          "The police are investigating a case of homicide.",
          "He was arrested for homicide.",
          "Homicide rates have increased this year.",
        ],
        wordPr: "قتل، کشتار",
        definitionPr: "کشتن یک انسان توسط انسان دیگر",
        synonymsPr: ["قتل", "آدم‌کشی", "قتل عمد یا غیرعمد"],
        examplesPr: [
          "پلیس در حال بررسی یک پرونده قتل است.",
          "او به جرم قتل دستگیر شد.",
          "نرخ قتل در سال جاری افزایش یافته است.",
        ],
      },
      {
        id: 263,
        pronunciation: "ˈpiːnəlaɪz",
        imageUrl: "",
        word: "penalize",
        definition: "to punish or treat unfairly",
        synonyms: ["punish", "discipline", "fine"],
        examples: [
          "The player was penalized for a foul.",
          "You’ll be penalized for late payment.",
          "The new law penalizes tax evaders.",
        ],
        wordPr: "مجازات کردن",
        definitionPr: "تنبیه یا جریمه کردن کسی به خاطر تخلف",
        synonymsPr: ["تنبیه کردن", "جریمه کردن", "مجازات کردن"],
        examplesPr: [
          "بازیکن به خاطر خطا جریمه شد.",
          "در صورت پرداخت دیرهنگام، جریمه می‌شوید.",
          "قانون جدید فرار مالیاتی را مجازات می‌کند.",
        ],
      },
      {
        id: 264,
        pronunciation: "ˌbenɪˈfɪʃieri",
        imageUrl: "",
        word: "beneficiary",
        definition: "a person who receives benefits or advantages",
        synonyms: ["recipient", "heir", "inheritor"],
        examples: [
          "She is the sole beneficiary of his will.",
          "The children are the beneficiaries of the trust.",
          "The company was the main beneficiary of the deal.",
        ],
        wordPr: "ذی‌نفع، بهره‌مند",
        definitionPr: "کسی که از چیزی سود یا مزیت می‌برد",
        synonymsPr: ["دریافت‌کننده", "وارث", "ذی‌حق"],
        examplesPr: [
          "او تنها ذی‌نفع وصیت‌نامه اوست.",
          "کودکان ذی‌نفعان این صندوق هستند.",
          "شرکت اصلی‌ترین بهره‌مند این معامله بود.",
        ],
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
